### ISSUE TITLE
CDR Reporting bug for everyone other than admin users!

### ISSUE THREAD

**Issue by landman16** [iNextrix/ASTPP#100]
**Im running: CentOS 7 + ASTPP 3.0**

Hi there the current bug seams to be present in version 3.0

Admins: CDR reporting works great
Providers: CDR Reporting DOESNT WORK
Resellers: CDR Reporting DOESNT WORK
Customers: CDR Reporting DOESNT WORK

Thiis would spell utter desaster as far as accounting was concirned, if a customer was not able to obtain CDR reprorts on thier accounts 

Can you confirm if this indeed a bug or if its somthing i am missing?

**Comment by dev-astpp** [comment]
You mean cdrs report searching is not working?
If yes then, Please take latest source and test it out.

**Comment by landman16** [comment]
im using the latest version im using version v3.0, still the issue is present.

**Comment by dev-astpp** [comment]
Its fixed 
Please take latest source and test it out.
