### ISSUE TITLE
There is also a fault in the database module 

### ISSUE THREAD

**Issue by landman16** [iNextrix/ASTPP#101]
**Im running: CentOS 7 + ASTPP 3.0**

There is also a fault with the below file 

/etc/odbc.ini

open the above file in a text editor and change;

this line

/var/usr/mysql/mysql.sock

to this 

/var/lib/mysql/mysql.sock

And wham the database module starts working again, As the connection can be made to the DB ........... Dowh! This bug is one that comes right out the box :-X

This software looks great, but it could never be placed into a live enviroment as its extreamly buggy!!! but deffo a project i will be watching for improvements.

At this moment in time A2Billing works for me, but looks crap! so this was why i was looking for another option.

**Comment by dev-astpp** [comment]
This issue has been fixed now !

**Comment by dev-astpp** [comment]
There is not any update for this issue from this user, So now we are closing this issue
