### ISSUE TITLE
upload logo bug

### ISSUE THREAD

**Issue by landman16** [iNextrix/ASTPP#102]
**Im running: CentOS 7 + ASTPP 3.0**

there is an options in the admin panel to update the logo for branding (i think thats what its for) that doesnt work ether, I ended up having to manually upload my logo to replace the ASTPP one.

**Comment by dev-astpp** [comment]
We will fix it soon !

**Comment by Levadiani** [comment]
And please add function for change title of web-pages.

**Comment by dev-astpp** [comment]
@Levadiani 
Are you talk about admin title from this page?

**Comment by dev-astpp** [comment]
Fixed. Please take latest source and test it out.
