### ISSUE TITLE
Email Sending Not Working Ether

### ISSUE THREAD

**Issue by landman16** [iNextrix/ASTPP#103]
**Im running: CentOS 7 + ASTPP 3.0**

Email SMTP not sending out emails, I mean i had a few emails come through. But not after working out from a lot of google digging around, that these are what has to be changed in the admin panel to get it to "kind of" work

SEND EMAIL ALERTS=DISABLED = WORKING ALERT HUMMMMM
SEND EMAIL ALERTS-ENABLED = NO EMAILS WILL SENT OUT TO ANYONE

USE SMTP = DISABLED = USES SMTP TO SEND OUT EMAILS
USE SMTP = ENABLED = SENDS EMAILS VIA SENDMAIL

Again maybe an slight over-sight, but this is just cack handed coding! This could have been changed quite easily. I mean i kind of got the emails sending out, but it wasnt at all reliable at all,

**Comment by dev-astpp** [comment]
We are already working on this bug.

**Comment by unridaz** [comment]
landman, perhaps you could elaborate on how you got this working in my google groups thread:
https://groups.google.com/forum/#!topic/astpp/PY6K_Q-xNrM

I have tried all sorts of things enabled/disabled, but I don't get any hint of email, or any errors in my logs..

**Comment by smrdoshi** [comment]
Are you using SMTP with google account?

**Comment by dev-astpp** [comment]
Didn't get further information to reproduce this issue, So we are closing this issue
