### ISSUE TITLE
Issue with odbc.in/mysql.sock resulting in DB connection errors - how to fix

### ISSUE THREAD

**Issue by landman16** [iNextrix/ASTPP#107]
Dear Community,

This bug is present right out of the box (even in v3.0 the latest version), so if your using CentOS 7 you will for sure most possibly have this issue. The symptoms will be you wont hear anything when trying to call using a sip trunk, even though it may seam to have registered. You also may well not be able to call out at all. And if you trail the ASTPP log files by exicuting the following command in SSH/terminal "fs_cli" removing the " of course, you will see fatal database connection errors.

This bug is still present, but thought i would share how to fix it on your own without having to wait for ASTPP to reply that can often take a while.

Locate your odbc.ini file (useually in /etc) if your using CentOS 7

Find the following line of code:

Socket = /var/etc/mysql/mysql.sock (or what ever it says)

And replace it with your mysql.sock path (useually: /var/lib/mysql/mysql.sock)

Then save the file, reboot to make sure the changes take effect, although ive never needed to reboot and then you should be fixed :-)

**Comment by dev-astpp** [comment]
This issue has been fixed now !

**Comment by dev-astpp** [comment]
There is not any update for this issue, So now we are closing this issue
