### ISSUE TITLE
VP8, H263-1998 - Session is connected to a media bug.  Re-Negotiation implicity disabled.

### ISSUE THREAD

**Issue by epipenau** [iNextrix/ASTPP#114]
Hi,

I have tried enabling the video codecs in the sip profile but the video fails to initiate.  Using Zoiper on Android.

**Comment by dev-astpp** [comment]
You can maybe look at https://wiki.freeswitch.org/wiki/RTP_Issues and https://wiki.freeswitch.org/wiki/Sofia.conf.xml to try some profile parameters and see if they can resolve it.
