### ISSUE TITLE
Update Script & Permissions 777

### ISSUE THREAD

**Issue by unridaz** [iNextrix/ASTPP#115]
Hello,

Aren't there some security issues with giving the entire ASTPP folder permissions 777?

I also noted that it appears you have now added this line to the update script.

Do you think perhaps this should either not be forced upon the user during updates or at least with a checking or configurable setting mechanism?

**Comment by smrdoshi** [comment]
True. This has to be corrected. Will do needful for that.

**Comment by smrdoshi** [comment]
Done. Changed it to 755.
