### ISSUE TITLE
A small Bug in 'astpp.callingcard.functions.lua'

### ISSUE THREAD

**Issue by QQ110902** [iNextrix/ASTPP#120]
line 374----------
`if (calleridinfo ~= nil) then
                    if (calleridinfo['cid_name'] ~= '')  then
                        session:execute("set", "origination_caller_id_name="..calleridinfo['cid_name']);    
                    end
                    if (calleridinfo['cid_number'] ~= '')  then
                        session:execute("set", "origination_caller_id_number="..calleridinfo['cid_number']);      
                    end
                end`

there no 'cid_name' and 'cid_number' fields in the database
the correct fields is 'callerid_name' and 'callerid_number' in 'accounts_callerid' table

**Comment by dev-astpp** [comment]
We will fix this issue soon.

**Comment by smrdoshi** [comment]
These are the variables which are getting value from other file and method. It doesn't have to do anything with database field.

**Comment by QQ110902** [comment]
`calleridinfo = get_override_callerid(userinfo)`

`function get_override_callerid(userinfo)
    local callerid
    local query  = "SELECT * FROM "..TBL_ACCOUNTS_CALLERID.." WHERE accountid = "..userinfo['id'].." AND status=0 LIMIT 1";    
    Logger.debug("[GET_OVERRIDE_CALLERID] Query :" .. query)
    assert (dbh:query(query, function(u)
	    callerid = u
    end))    
    return callerid
end`

**Comment by smrdoshi** [comment]
Once calleridinfo get the value, it is extract the values from array and pushing into cid_name and cid_number with some conditions.

**Comment by QQ110902** [comment]
Please look carefully at the code.

 calleridinfo get value from function get_override_callerid, this function just query the database. and return recordset callerid from table TBL_ACCOUNTS_CALLERID  to array calleridinfo.

this bug occur a error to set a callerid to customer. have a try pls.

**Comment by dedayoa** [comment]
This bug needs to be resolved all the way from the front end.

- On "Force caller ID" overlay edit, why is "caller ID name" compulsory, when it is a "Yes|No" field at the higher level. I think the 2.0 implementation was better, where it was not a compulsory field.

- I assume selecting "enable: Yes" means "force caller ID"...but this breaks the call raising the lua error reported.

- calls only go through if "enable" is "NO", but then caller IDs are not forced. Rather the "caller ID caller name" and "caller ID caller number" on the SIP device is what is sent - and this can be edited by the customer.

Meaning forcing caller ID does not presently work.

**Comment by dedayoa** [comment]
Thanks for the fixes @smrdoshi
Happy new month!
