### ISSUE TITLE
Emails with TLDs over 6 characters aren't considered valid

### ISSUE THREAD

**Issue by thefinn93** [iNextrix/ASTPP#122]
ASTPP says my (perfectly valid) email on the `janky.solutions` domain is invalid. I have located the offending regex on [email_helper.php](https://github.com/iNextrix/ASTPP/blob/master/web_interface/astpp/system/helpers/email_helper.php#L40) line 40. It also fails to validate several of the [examples of valid email addresses on Wikipedia](https://en.wikipedia.org/wiki/Email_address#Examples).

**Comment by dev-astpp** [comment]
We have tested it and created one account with your domain.
It's working fine.
If it's something else then please revert back with exact steps to reproduce same issue at our end.
![screenshot from 2016-11-04 17 23 52](https://cloud.githubusercontent.com/assets/20809954/20004705/e62f4480-a2b3-11e6-8509-42431f9f2b1b.png)
