### ISSUE TITLE
IP Settings prefix displaying in CDR

### ISSUE THREAD

**Issue by derksandre** [iNextrix/ASTPP#134]
Hi, I was instructed to report this issue here.
We are testing using multi tenant Asterisk box with ASTPP and separating tenants by prefix to the same IP.  The prefix however is showing as part of the called number in CDR reports. (we have tried number translation in customer and trunk and not working).  Thank you for all your efforts.

**Comment by smrdoshi** [comment]
This issue has been fixed and merged.
