### ISSUE TITLE
LUA script parse/execute error ​IF "Force Caller Id" set to Enable (yes)

### ISSUE THREAD

**Issue by celosam** [iNextrix/ASTPP#137]
Hi, I was instructed to report this issue here.

​IF > Force Caller Id > Enable (yes)

fs_cli shows:

_2016-10-21 10:52:57.783004 [DEBUG] switch_cpp.cpp:1360 [ASTPP] [GET_OVERRIDE_CALLERID] Query :SELECT \* FROM accounts_callerid WHERE accountid = 4 AND status=0 LIMIT 1
2016-10-21 10:52:57.783004 [ERR] mod_lua.cpp:203 /usr/local/freeswitch/scripts/astpp/scripts/astpp.xml.lua:247: attempt to concatenate field 'cid_name' (a nil value)
stack traceback:
        /usr/local/freeswitch/scripts/astpp/scripts/astpp.xml.lua:247: in function 'freeswitch_xml_callerid'
        ...ocal/freeswitch/scripts/astpp/scripts/astpp.dialplan.lua:376: in main chunk
        [C]: in function 'dofile'
        /usr/local/freeswitch/scripts/astpp/astpp.lua:76: in main chunk
2016-10-21 10:52:57.783004 [ERR] mod_lua.cpp:270 LUA script parse/execute error!_

Thanks.

**Comment by QQ110902** [comment]
#120

**Comment by celosam** [comment]
Samir, thank you very much!
