### ISSUE TITLE
Error 500 when trying to edit SIP profile

### ISSUE THREAD

**Issue by dedayoa** [iNextrix/ASTPP#138]
PHP Parse error:  syntax error, unexpected '}' in /var/www/html/astpp/application/modules/freeswitch/views/view_fssipprofile_edit.php on line 150.

I seem to have fixed this by simply removing the '}'
I don't have an IDE to do a more thorough debug.

**Comment by smrdoshi** [comment]
Changes merged to v3.0 branch.
