### ISSUE TITLE
0000041: Live Call Report and inbound-bypass-media

### ISSUE THREAD

**Issue by smrdoshi** [iNextrix/ASTPP#14]
Hi,

Everytime I make a STANDARD/CALLINGCARD call, I see in LIVE CALL REPORT "Read Codec PCMU" and "Write Codec PCMU" I want other codecs to be used, like G729 and G723.

SCENARIO 1

I have the following configuration in SIP Profile:
inbound-codec-prefs G729,G723,PCMU,PCMA
outbound-codec-prefs G729,G723,PCMU,PCMA

In trunks "Codecs G729,G723,G711"

SCENARIO 2

I changed codecs in SIP Profile inbound-codec-prefs/outbound-codec-prefs G729 
reload mod_sofia

I made a call and I got "INCOMPATIBLE_DESTINATION"

I changed inbound-bypass-media true and inbound-late-negociation true in SIP Profile 
reload mod_sofia

I made a STANDARD call and It got connected, but it did not appear in LIVE CALL REPORT, so I don't know which codecs were used.
I make a CALLINGCARD call and It got connected, I see in LIVE CALL REPORT "Read Codec PCMU" and "Write Codec PCMU"

Am I doing something wrong or it's a bug?

Thank you!

**Comment by ChaudharyG** [comment]
Same problem i have. I have set code g729 inbound-bypass-media true, all these below calls were connected but on soft phone status were "Calling". My scenario is mention below. 

SoftWitch In (G729) --Out --G729 (media=true) ----> ASTPP (in/out g729)----> Vendor   


![image](https://cloud.githubusercontent.com/assets/15512968/17699025/fdf39808-63db-11e6-9ce7-3659d49f7b9d.png)

**Comment by smrdoshi** [comment]
Issue has been fixed in version v3.5. Upgrade to latest version and test it out.

**Comment by meshtask** [comment]
Hi,
I am having same issue with ASTPP 3.6 fresh install.
when inbound-bypass-media=true for g729 passthrough,
calls disappear from ASTPP Live Call Reports.
Any solution please?
