### ISSUE TITLE
Termination Rate Import Mapper

### ISSUE THREAD

**Issue by countrdd** [iNextrix/ASTPP#142]
In Version 2.3, I created a termination rate import with mapper, this allowed me to easily import/update termination rates from my carriers, with out having to edit/modify the format of their rate decks. I would like to apply this change to the v3.0 system. Below is the screen shot of what the mapper looks like, The table at the bottom is a few of the records in the said rate deck. This allows me.

If this is a mod that would go into the main distro let me know and I will get it completed.

![screen shot 2016-11-01 at 6 51 39 am](https://cloud.githubusercontent.com/assets/3502770/19887600/c7550290-9fff-11e6-802d-5d1c379f3c6e.png)

**Comment by smrdoshi** [comment]
@countrdd, Yeah of course. This will be nice feature to have as this will make import process easy. Please carry on with your development and once done send us pull request. We will look at code and flow and once everything will be fine, we will merge it with branch.

**Comment by countrdd** [comment]
Just did a pull request, hope I did it correctly.

**Comment by countrdd** [comment]
These have been updated.

**Comment by countrdd** [comment]
Anymovement on this?

**Comment by smrdoshi** [comment]
Nope. This feature will merged and released under 4.0. We are excited to
merge new features in 4.0.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.

**Comment by smrdoshi** [comment]
Feature merged into version 3.5.
