### ISSUE TITLE
Summary Report Timezone

### ISSUE THREAD

**Issue by watoan** [iNextrix/ASTPP#143]
https://groups.google.com/forum/#!topic/astpp/yfMSOL_tIT4

By default:
My system time is in GMT+0
admin account of ASTPP is in GMT+0
one customer account is in GMT+0

In this case, everything working well, including the CDR report and summary report(group by hour), all of them showing correct time in GMT+0.

Now I want to see data in GMT+6:
I tried to change the "admin" account timezone to be GMT+6, go to CDR report, time is changed as GMT+6, it is perfect.

But when I check the customer summary report, I tried to searched again with the same criteria, but the "hour" column still the same, it is showing in GMT+0.

**Comment by dev-astpp** [comment]
Still there is some issue which not display record proper

**Comment by smrdoshi** [comment]
Issue has been fixed in version v3.5. Upgrade to latest version and test it out.
