### ISSUE TITLE
MySQL Table cdrs - trunkip and callerip inserting the same value

### ISSUE THREAD

**Issue by watoan** [iNextrix/ASTPP#147]
https://groups.google.com/forum/#!topic/astpp/Sbpw7D_HNKQ

Test call from IP 1.1.1.1 sending to ASTPP(FS) with IP 2.2.2.2, then the call send to outbound trunk with gateway IP 3.3.3.3 (actually there is only 1 trunk and 1 gw in my system).

Supposed the "trunkip" = 3.3.3.3, and "callerip" = 1.1.1.1

but I see both of them are showing 1.1.1.1

**Comment by smrdoshi** [comment]
In version 3.5 added code to reloadacl upon delete.
