### ISSUE TITLE
Signup not assigning correct Rate Group

### ISSUE THREAD

**Issue by ricky560** [iNextrix/ASTPP#150]
Hello,

I have configured sign under Configuration>Settings>Signup

![signup](https://cloud.githubusercontent.com/assets/21016358/20073146/0ee5d37a-a4f9-11e6-8e15-1b540f25c793.png)

When I test signing up a new user it assigns the default Rate Group instead of the one set in the Global settings

**Comment by smrdoshi** [comment]
Issue has been fixed in version v3.5. Upgrade to latest version and test it out.
