### ISSUE TITLE
Included seconds not detected

### ISSUE THREAD

**Issue by juancarlosg6** [iNextrix/ASTPP#151]
Hi, when assign in the included second variable Origination Rate, this is not debit on general cdr, then is not possible to do a correct billing to a customer, because we have no the correc value on the CDR.

**Comment by dev-astpp** [comment]
As per concept of ASTPP if you have set included second in Origination Rate then it will deduct amount after completion of Included second and display in CDRs.

For example you have set 5 second as included second then make call of 15 second, So it will charge for 10 second to that customer.

For any other thing you should need to modify code.

**Comment by juancarlosg6** [comment]
Yes, i understand the concept, but i create a Origination Rate and code included a 10 second, if do a call of 8 second, the system charge the 8 seconds in this case the system must exclude this 8 seconds on not will be billed, but when i go and see the CDR i see the billed 8 second, then this report is bad and incorrect.

**Comment by dev-astpp** [comment]
In CDR it just display for record purpose. You can verify your balance after call it should not deduct any amount as per your above scenario.

**Comment by juancarlosg6** [comment]
Ok, i understand now but then how we can create a report for a billed customer if i cannot see the correct value on reporst or CDR, then we must login with the customer account the see correct information in CDR display to them, or too in this CDR is showed the full billed seconds, or may be have another step to do this, thansk.

**Comment by smrdoshi** [comment]
For the free calls, we have call type = FREE. That means that call was free. Billable outbound calls will always have call type = STANDARD and incoming did call will have call type=DID. 

Hope this will clear your doubts.
