### ISSUE TITLE
ERROR code php

### ISSUE THREAD

**Issue by ramifourati** [iNextrix/ASTPP#156]
Hi,

After installing astpp and try to create anything from trunk, rate groups, customer or provider we are getting this error after we click on save

A Database Error Occurred
Error Number: 1366

Incorrect integer value: '' for column 'includedseconds' at row 1

Insert into routes (pricelist_id,pattern,comment,status,connectcost,includedseconds,cost,init_inc,inc,trunk_id,creation_date) values('1','^33.*','france','0','0','','0','','','1','2016-11-15 11:40:40') ON DUPLICATE KEY UPDATE pricelist_id = '1',pattern = '^33.*',comment = 'france',status = '0',connectcost = '0',includedseconds = '',cost = '0',init_inc = '',inc = '',trunk_id = '1',creation_date = '2016-11-15 11:40:40'

Filename: /var/www/html/astpp/modules/rates/models/rates_model.php

Line Number: 355

and this error for creating a customer when we click on save 

A Database Error Occurred
Error Number: 1366

Incorrect integer value: '' for column 'id' at row 1

INSERT INTO `accounts` (`id`, `type`, `number`, `password`, `pin`, `first_name`, `last_name`, `company_name`, `telephone_1`, `telephone_2`, `email`, `address_1`, `address_2`, `city`, `province`, `postal_code`, `country_id`, `timezone_id`, `currency_id`, `status`, `is_recording`, `allow_ip_management`, `dialed_modify`, `maxchannels`, `interval`, `first_used`, `validfordays`, `expiry`, `pricelist_id`, `posttoexternal`, `sweep_id`, `invoice_day`, `balance`, `credit_limit`, `local_call`, `charge_per_min`, `notify_flag`, `notify_credit_limit`, `notify_email`, `reseller_id`, `creation`) VALUES ('', '0', '4544774292', 'IuTeY62yJJUA2M9SXBAEfTv-iV7wpju5f20rmb-OBE0', '333573', 'test', '', '', '', '', 'test@test.com', '', '', '', '', '', '85', '27', '139', '0', '0', '0', '', '0', '', '0000-00-00 00:00:00', '', '2036-11-15 13:59:57', '1', '0', '2', '15', '', '0', 0, '', '0', '', '', 0, '2016-11-15 13:59:57')

Filename: /var/www/html/astpp/modules/accounts/models/accounts_model.php

Line Number: 65

Help please

**Comment by dev-astpp** [comment]
Please change sql_mode to "NO_ENGINE_SUBSTITUTION"
It should work.
