### ISSUE TITLE
Issues with variables replacements  in ASTPP 3.0

### ISSUE THREAD

**Issue by bingy92** [iNextrix/ASTPP#157]
Hi guys!

I've just updated my ASTPP 3.0 environment with the latest Github v3.0 source. I am still seeing some issues with variables replacements in email alerting.

Example:
Hi John Doe, This is a quick notification about the low balance of #AMOUNT# in your account. Please refill you account from our website to ensure your services will remain consistent. You can login into customer portal and refill your account. For more info, Please visit on our website www.inextrix.com or contact to our support at sa...@inextrix.com Thanks, iNextrix Technologies. Pvt. Ltd. 

Any help/suggestions is welcomed.

Thanks!

**Comment by dev-astpp** [comment]
It not working for 1-2 variables only that will be fixed soon. For other its working proper.
Thanks.

**Comment by bingy92** [comment]
Thanks much for the update, appreciate it.

Regards,
Phil

**Comment by drenda** [comment]
Some news about this bug? Thanks

**Comment by smrdoshi** [comment]
Yeah. The work is in progress for this bug fixing. By this week patch will
be committed to git.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.

**Comment by smrdoshi** [comment]
Issue has been fixed in version v3.5. Upgrade to latest version and test it out.
