### ISSUE TITLE
0000007: Blocking account when the amount of a call is too high

### ISSUE THREAD

**Issue by dev-astpp** [iNextrix/ASTPP#17]
Every sip server receive many attack every day. Having said that securing sip server is the first thing, would be nice have a function that automatically block an account when the amount of a call is greater then a specific amount set in customer settings.

When the account is blocked an email should be sent to the customer and to the administrator.

**Comment by Hemdip** [comment]
@dev-astpp , It has been fixed in V-4.0, We have implemented fraud detection addon to achieve this.
