### ISSUE TITLE
Old jQuery version

### ISSUE THREAD

**Issue by dedayoa** [iNextrix/ASTPP#170]
Hello,
While trying out the database backup function on the latest version of ASTPP (I just did an update about 10mins ago), I realized that the "save" button didn't work.
On checking on developer console, I see a
`Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher`

Although the error thrown when the button is clicked is 
`Uncaught SyntaxError: Unexpected token A in JSON at position 0`

However, I think both are related.
Are there any deps forcing ASTPP to stay at 1.7.1 ?

**Comment by dedayoa** [comment]
So I updated flexigrid to the latest I could find https://github.com/JcluoIvan/Flexigrid (works with 1.8.3 but still lower than 1.9.1 required by bootstrap), and jquery to the latest 1.X.X (1.12.4), but got "Connection error" on the flexgrid and a "bloated" grid.

Seems this will be non-trivial. I'll be willing to commit some time, if you could help out with pointers.

**Comment by hardikinextrix** [comment]
We have upgrade Bootstrap and Jquery version on new release.
