### ISSUE TITLE
Customer Profile Number Translation /IP Prefix Issue.

### ISSUE THREAD

**Issue by countrdd** [iNextrix/ASTPP#171]
Customer Profile Number Translation allows special characters (i.e. *,- etc) in the field, but if you have a special character in this field IP settings with a prefix authentication fails. 

Note: * was able to be used in v2.3, but it looks like in 3.0 it cannot be used and I get a regex error.

The prefix field in the IP Settings needs to be changed from type number to type text.

This is useful because if you have a multitenant PBX you can append the string to the dial string in your pbx (Thirdlane,FreePBX, etc) and then the call will be authenticated and billed to the appropriate account. 

This also makes it easy to distinguish between dialed digits and the account number. 
[
![screen shot 2017-01-08 at 8 09 50 am](https://cloud.githubusercontent.com/assets/3502770/21750139/15396384-d57a-11e6-842d-17b5faf3f402.png)

![screen shot 2017-01-08 at 8 06 38 am](https://cloud.githubusercontent.com/assets/3502770/21750101/89e004fa-d579-11e6-99a9-c8bf28f73808.png)

](url)

**Comment by smrdoshi** [comment]
That's right. If number translation allowing then IP setting page should
allow such translation.
Thanks for the suggestion. We will do needful for that.


Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.

**Comment by countrdd** [comment]
I have been trying to debug why I cannot use a * in the translation string, I was able to in 2.3…but 3.0 I get a regex error and the calls fails.  Any Ideas?

**Comment by smrdoshi** [comment]
In IP Settings?

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.

**Comment by countrdd** [comment]
It is passing the IP ACL with no issues, it is where it is trying to bridge the call…interestingly enough if I use a – the call goes right thru. I think it has something to do with the way the Number Translation from the Customer Profile is being handled.

017-01-09 11:55:24.190391 [NOTICE] switch_cpp.cpp:1360 [ASTPP] test
2017-01-09 11:55:24.190391 [DEBUG] switch_cpp.cpp:1360 [ASTPP] [Dialplan] Generated XML 3 :
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<document type="freeswitch/xml">
<section name="dialplan" description="ASTPP Dialplan">
<context name="default">
<extension name="17407742151">
<condition field="destination_number" expression="4051258985*17407742151">
<action application="set" data="effective_destination_number=17407742151"/>
<action application="sched_hangup" data="+75295.746835443 normal_clearing"/>
<action application="set" data="callstart=2017-01-09 11:55:24"/>
<action application="set" data="hangup_after_bridge=true"/>
<action application="set" data="continue_on_fail=true"/>
<action application="set" data="account_id=98"/>
<action application="set" data="parent_id=0"/>
<action application="set" data="entity_id=0"/>
<action application="set" data="call_processed=internal"/>
<action application="set" data="call_direction=outbound"/>
<action application="set" data="accountname=HOme"/>
<action application="set" data="origination_rates=ID:245888|CODE:^1.*|DESTINATION:USA|CONNECTIONCOST:0.00000|INCLUDEDSECONDS:0|COST:0.03950|INC:6|INITIALBLOCK:0|RATEGROUP:8|MARKUP:0|ACCID:98"/>
<action application="set" data="calltype=STANDARD"/>
<action application="set" data="termination_rates=ID:1079770|CODE:^1740774.*|DESTINATION:NPANXX -1740774|CONNECTIONCOST:0.00000|INCLUDEDSECONDS:0|COST:0.01991|INC:6|INITIALBLOCK:0|TRUNK:17|PROVIDER:103"/>
<action application="set" data="trunk_id=17"/>
<action application="set" data="provider_id=103"/>
<action application="set" data="absolute_codec_string=G729,PCMU"/>
<action application="bridge" data="sofia/gateway/alcazar/17407742151"/>
</condition>
</extension>
</context>
</section>
</document>
2017-01-09 11:55:24.190391 [DEBUG] freeswitch_lua.cpp:382 DBH handle 0x1aa2190 released.
Dialplan: sofia/default/7407793343@174.101.122.190:5061 parsing [default->17407742151] continue=false
Dialplan: sofia/default/7407793343@174.101.122.190:5061 Regex (FAIL) [17407742151] destination_number(4051258985*17407742151) =~ /4051258985*17407742151/ break=on-false
2017-01-09 11:55:24.190391 [INFO] switch_core_state_machine.c:311 No Route, Aborting
2017-01-09 11:55:24.190391 [NOTICE] switch_core_state_machine.c:312 Hangup sofia/default/7407793343@174.101.122.190:5061 [CS_ROUTING] [NO_ROUTE_DESTINATION]

**Comment by smrdoshi** [comment]
How are you getting number?
<condition field="destination_number" expression="4051258985*17407742151">

First thing I am not able to enter * in IP Setting module and I am sure you
are not dialling * in your destination number. So how are you getting
number with *?

Moreover if IP based authentication done, it will never pass number with
ACL prefix in destination number checking field of dialplan.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.

**Comment by countrdd** [comment]
See Below

**Comment by countrdd** [comment]
2017-01-09 12:25:30.990399 [WARNING] switch_cpp.cpp:1360 [ASTPP] [DONUMBERTRANSLATION] number translation : 4051258985*/*
2017-01-09 12:25:30.990399 [WARNING] switch_cpp.cpp:1360 [ASTPP] [DONUMBERTRANSLATION] Before number translation : 4051258985*17407742151
2017-01-09 12:25:30.990399 [WARNING] switch_cpp.cpp:1360 [ASTPP] [DONUMBERTRANSLATION] After  number translation : 17407742151

It looks like the DONUMBERTRANSLATION Function does not like the * in the dialstring prefix. Is *

function do_number_translation(number_translation,destination_number)
    local tmp
    Logger.debug
    tmp = split(number_translation,",")
    for tmp_key,tmp_value in pairs(tmp) do
      tmp_value = string.gsub(tmp_value, "\"", "")
      tmp_str = split(tmp_value,"/")
      local prefix = string.sub(destination_number,0,string.len(tmp_str[1]));
      if (prefix == tmp_str[1] or tmp_str[1] == '*') then
        Logger.warning("[DONUMBERTRANSLATION] number translation : " .. number_translation)
       Logger.warning("[DONUMBERTRANSLATION] Before number translation : " .. destination_number)
      if(tmp_str[2] ~= nil) then
            if (tmp_str[2] == '*') then
             destination_number = string.sub(destination_number,(string.len(tmp_str[1])+1))
            else
                if (tmp_str[1] == '*') then
                 destination_number = tmp_str[2] .. destination_number
                else
                 destination_number = tmp_str[2] .. string.sub(destination_number,(string.len(tmp_str[1])+1))
                end
            end
      else
          destination_number = string.sub(destination_number,(string.len(tmp_str[1])+1))
      end
       Logger.warning("[DONUMBERTRANSLATION] After  number translation : " .. destination_number)
      end
    end
    return destination_number
end

**Comment by countrdd** [comment]
Google Chrome – Field Override with inspect.

[cid:image001.png@01D26A4A.A5A761A0]

**Comment by smrdoshi** [comment]
I got it. Yeah we have condition for * to handle for number translation. So
if you will use * in ACL then it might create problem. If possible use any
other char in place of using *. That should work.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.

**Comment by countrdd** [comment]
Ok.

I just have to touch about 20 systems to fix the issue, so that sets back my migration schedule…dang it!

You may want to do some HTML5 validation on the IP ACL Field to allow – but not *

It is really nice when you are using an account code prefix to have a separator in the prefix so that way you can easily figure out account code and number dialed in the logs.


Dusty


P.S. I have been using my rate import mapper with out any issues so far. Love to see that get in the main code base.

**Comment by smrdoshi** [comment]
That's right. Maybe you use # or - for now in place of using *.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.

**Comment by countrdd** [comment]
I am Guessing you like it when people actually do the debug vs just complaining about an issue in the issues logs or forums… ☺

**Comment by smrdoshi** [comment]
Yeah of course.  :) That gives us encouragement to do better work and shows
us that we are not alone who keeps only putting efforts to make this
product good.

Thanks for your support. Keep it it. :)

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.

**Comment by smrdoshi** [comment]
That is fixed in version v3.5. Upgrade to latest version and test it out.
