### ISSUE TITLE
Wrong pagination in SIP profile

### ISSUE THREAD

**Issue by drenda** [iNextrix/ASTPP#176]
Hi,
in the list of parameters of SIP profile the pagination is wrong. With the default data of ASTPP for example, I see 5 pages, but when I move to others pages entries shown are the same.

Thanks

**Comment by smrdoshi** [comment]
That is not a bug. As we wanted to display all variables of sip profile on
same page, we removed page limit but grid still doing internal paging and
display all records on same page.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.
