### ISSUE TITLE
Sofia password param required

### ISSUE THREAD

**Issue by drenda** [iNextrix/ASTPP#177]
Hi, in my fresh installation of ASTPP I see this error several times when I do changes in my cofiguration (gateways, trunk, etc).

`2017-01-23 19:25:30.329538 [ERR] sofia.c:3692 ERROR: password param is REQUIRED!
2017-01-23 19:25:30.349531 [WARNING] sofia.c:3484 Ignoring duplicate gateway 'example.com'`

**Comment by smrdoshi** [comment]
You can ignore it. That is default one. That will not create any impact on
your call or process.


Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.

**Comment by drenda** [comment]
Thanks
