### ISSUE TITLE
Add SSL support for email SMTP

### ISSUE THREAD

**Issue by drenda** [iNextrix/ASTPP#178]
Please add SSL support for email SMTP.

Thanks

**Comment by smrdoshi** [comment]
That is already added. You can define smtp server with ssl like ssl://
smtp.gmail.com.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.

**Comment by drenda** [comment]
Thanks
