### ISSUE TITLE
Accounts not getting billed for monthly DID charge

### ISSUE THREAD

**Issue by andrewbenhanan** [iNextrix/ASTPP#180]
Hello, we are running ASTPP 3.0 on Centos with the WHMCS integration module purchased from Inextrix. We have just discovered that our customers are NOT being billed monthly for the DID's that they have. The accounts are in prepaid mode, and so we don't expect to see invoices, however, doing calculations, we have confirmed no DID monthly charges are happening.

**Comment by smrdoshi** [comment]
Please report it to support@inextrix.com. Our technical team will look at
that and update you.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.

**Comment by andrewbenhanan** [comment]
I opened a support ticket. But I will email as well.

**Comment by smrdoshi** [comment]
Thanks. We will check it out and update you there.


Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.
