### ISSUE TITLE
Account Type in ASTPP 3.0 auto changing from Prepaid to Postpaid (Posttoexternal = 0, changes to 1)

### ISSUE THREAD

**Issue by andrewbenhanan** [iNextrix/ASTPP#181]
Running ASTPP 3.0 on Centos x64. Running with the WHMCS integration Module as well. We notice that every few days, the account type changes from prepaid to postpaid (in the database under accounts table : posttoexternal = 0 changes to posttoexternal =1) I have to manually go to the DB to change them back to 'posttoexternal=0'. It doesn't seem to keep.

**Comment by smrdoshi** [comment]
Please report it to support@inextrix.com. Our technical team will look at
that and update you.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.
