### ISSUE TITLE
CDR Report ISSUE

### ISSUE THREAD

**Issue by ramifourati** [iNextrix/ASTPP#183]
Hi
There's a difference between the CDR report using the admin portal and the customer portal.
In the admin portal it shows more in the debit and duration then the customer portal and this is
for all the customers that i have is there a bug?? for exemple this is one of my customer 
the admin portal duration 30931:25 debit 115.7 customer portal duration  28395:18 debit 100.3

Please help me to fix this

**Comment by smrdoshi** [comment]
That looks like bug. We will investigate further and update you.


Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.

**Comment by ramifourati** [comment]
Hi, even if i increase the initial increment and the default increment
its always the same for customer portal always less. When do you think this bug can be fixed

Kind Regards

**Comment by smrdoshi** [comment]
I just verified the code for generating report in admin and customer portal and both looks fine. Both code are appending same conditions (account id, from call start date and end call start date) and thus both must be returning same results. 

I also checked on some servers to validate but there also got same result. 

Can you please confirm the search params which you are using to filter the data to generate report?

**Comment by ramifourati** [comment]
In the admin portal i put for exemple from the 1st feb to 28th feb i choose the acccount and make a search
and in the customer portal i choose the same date however in the from date when i choose i get the time 12:00:00 and not 00:00:00 so i change that manually and the results are not the same for the debit and the duration. in the customer portal i get debit=465.8174 , duration=107223:06 and in the admin portal debit=503.6076, duration=113334:17

**Comment by ramifourati** [comment]
Samir sorry for this you are correct its fine except there's a bug in the customer portal from date time and to date time, when i choose the from date everytime i get 12:00:00 time and to date i get 11:59:59 so i have to manually change those from date to 00:00:00 and to date 23:59:59 is there a way to make this automatic same as the admin portal? Thank you for your help and sorry to waist your time on this

**Comment by smrdoshi** [comment]
That's right. That's by default picking 12:00:00. We will correct that and
update source.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.

**Comment by smrdoshi** [comment]
Issue has been fixed in version v3.5. Upgrade to latest version and test it out.
