### ISSUE TITLE
how it will setup  with external server freeswitch install ?

### ISSUE THREAD

**Issue by dipenpatel235** [iNextrix/ASTPP#188]
hello..
i have installed astpp in one server
now what next steps i required to connect with other server freeswitch ?
i want to make it saperate astpp server. and want to connect with multiple freeswitch.

Let me know if you have any documnetation related link for that or any guideline.

Thanks

**Comment by smrdoshi** [comment]
There is no documentation available for now but you can refer manual
installation documentation steps and configure require things for
freeswitch on freeswitch servers like lua scripts and connect it with
database etc.

Hope this will helps.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorised to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful.

**Comment by dipenpatel235** [comment]
ok...thanks
