### ISSUE TITLE
Bad limit counter

### ISSUE THREAD

**Issue by Neurotec** [iNextrix/ASTPP#190]
hi, we create 5 trunks using the same Gateway,
every trunk has he own limit.
but when astpp launch the call it use *limit_execute*, example:
*limit_execute(db FS-OUT gw_FS-OUT 20 bridge sofia/gateway/FS-OUT/5742792866)*
we see this line repeat for every trunk call out, but there is a problem it use the same resource *gw_FS-OUT* for every call, so this not limit well.

you can check, calling from *fs_cli* *limit_usage db FS-OUT gw_FS-OUT* you see we always using the same counter for each trunk limit.

our solution was edit, astpp.xml.lua:

~~~lua
able.insert(xml, [[<action application="limit_execute" data="db ]]..outbound_info['path']..[[ gw_]]..outbound_info['path']..[[ ]]..outbound_info['maxchannels']..[[ bridge sofia/gateway/]]..outbound_info['path']..[[/]]..temp_destination_number..[["/>]]);
~~~

replace with, variable resource *outbound_info['path']* with *outbound_info['trunk_id']*
~~~lua
able.insert(xml, [[<action application="limit_execute" data="db ]]..outbound_info['path']..[[ gw_]]..outbound_info['trunk_id']..[[ ]]..outbound_info['maxchannels']..[[ bridge sofia/gateway/]]..outbound_info['path']..[[/]]..temp_destination_number..[["/>]]);
~~~

**Comment by smrdoshi** [comment]
I guess you have gateways created with same name right?
If so then yeah this will happen.

Its good idea to use id in place of gateway name. We will update that.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by smrdoshi** [comment]
Fixed. We changed code.
