### ISSUE TITLE
Termination prefix ignored in CallingCard calls

### ISSUE THREAD

**Issue by saifulmr** [iNextrix/ASTPP#191]
Hi,
In termination rates, if I set a prefix on a destination, then the call proceeds to the trunk without the prefix. Prefix is ignored. 
However, if I want to strip digits it works. 
I did some tests myself and figured out that only CallingCard are not using the Prepend digits for outbound calls to trunks.
Logs - https://pastebin.com/nvYCM1zT

However, calls made through IP Map (ACL) is working fine with the Prepend digits for outbound calls to trunks.
Logs - https://pastebin.com/g9pjUVQi

I am using latest version of ASTPP.

**Comment by smrdoshi** [comment]
Patch applied
