### ISSUE TITLE
Reseller module ISSUES

### ISSUE THREAD

**Issue by rayedbs** [iNextrix/ASTPP#192]
a very big issue with reseller module: BALANCE  does not get updated = LOST of money
Scenario Level1:
- Admin create Reseller R1, refill it with 100 euro
- R1 create costumer C1 , Refill it with 10 euro
-C1 make a call
=> balance C1 decreased, Balance R1 decreased. WORK FINE

Scenario Level2:
- Admin create Reseller R1, refill it with 100 euro
- R1 create Sub Reseller  R1-1 , Refill it with 50 euro
- R1-1 create costumer C1 , Refill it with 10 euro
-C1 make a call
=> balance C1 decreased, Balance R1-1 decreased, BUT balance R1 does not!!! 

this mean that every costumer of resellers after level1 will make unlimited calls not billed!!!!
please help with this issue

**Comment by smrdoshi** [comment]
Patch applied.

**Comment by rayedbs** [comment]
Thank you Mr, Samir! great work.
