### ISSUE TITLE
ANY ONE CAN TELL US WHY ASTPP CAN NOT HANDLE MORE THEN 200 CALLS!!!

### ISSUE THREAD

**Issue by rayedbs** [iNextrix/ASTPP#198]

**Comment by darrenrusso** [comment]
Well probably it could be your server specification or something else. 
I am having ASTPP installed on one of my server and its having more than 200 calls running. 

At the moment:

# fs_cli -p abc -x 'show calls count'
256 total.

**Comment by rayedbs** [comment]
thank you very much for you response!
i have 8 core * 1.4Ghz CPU and 16 Go Ram
at nearly 150 cc the load become huge 90% !!!
what can be responsible for this! plz?
when i made htop i see freeswitch deamon use all ressources!
please can you help me

**Comment by darrenrusso** [comment]
I have 8 core, 3.60 Ghz CPU and 16 GB RAM.

Here is log of top of my server:

top - 17:05:06 up 15 days, 23:47,  2 users,  load average: 1.89, 1.26, 0.94
Tasks: 223 total,   2 running, 221 sleeping,   0 stopped,   0 zombie
%Cpu(s):  5.0 us,  1.2 sy,  0.0 ni, 92.7 id,  1.1 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 16172044 total,  1406616 free,  5542544 used,  9222884 buff/cache
KiB Swap:  3905532 total,  2506096 free,  1399436 used. 10125012 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                            
11319 root      -2 -10 5259276 1.179g   6124 S  30.8  7.6   9930:30 freeswitch                                                                         
28909 mysql     20   0 8563412 3.602g   6292 S   3.5 23.4 792:51.26 mysqld                                                                             
   17 root      20   0       0      0      0 S   0.7  0.0  81:38.73 rcu_sched                                                                          
   18 root      20   0       0      0      0 S   0.7  0.0  29:00.78 rcuos/0                                                                            
  514 root      20   0  157684   2316   1544 R   0.7  0.0   0:00.07 top                                                                                
  550 zabbix    20   0   82716   1428   1300 S   0.7  0.0   5:29.21 zabbix_agentd                                                                      
  553 apache    20   0  387640  10920   4040 S   0.7  0.1   1:20.23 php-fpm                                                                            
10117 apache    20   0  387016  10256   4040 S   0.7  0.1   1:19.05 php-fpm                                                                            
10144 apache    20   0  387640  11000   4060 S   0.7  0.1   1:19.25 php-fpm                                                                            
11635 apache    20   0  387896  11100   4032 S   0.7  0.1   1:19.51 php-fpm                                                                            
11810 apache    20   0  387900  11192   4056 S   0.7  0.1   1:19.51 php-fpm                                                                            
    1 root      20   0  228396  41836   1960 S   0.0  0.3   4:02.64 systemd                                                                            
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.26 kthreadd                                                                           
    3 root      20   0       0      0      0 S   0.0  0.0   0:20.60 ksoftirqd/0                                                                        
    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H                                                                       
    7 root      rt   0       0      0      0 S   0.0  0.0   0:01.39 migration/0                                                                        
    8 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh                                                                             
    9 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcuob/0                                                                            
   10 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcuob/1                                                                            
   11 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcuob/2                                                                            
   12 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcuob/3                                                                            
   13 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcuob/4                                                                            
   14 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcuob/5                                                                            
   15 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcuob/6                                                                            
   16 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcuob/7   

Well i am not sure what it could be in your case. But i do believe when number of CPS increase that time CPU goes high and then it comes back to normal condition.

**Comment by rayedbs** [comment]
thank you very much,
any suggestion for limiting Cps?

**Comment by kierandavies** [comment]
I manage to get over 1000 calls running on a VM. I simply added this to my SIP_Profile and my CPU utilisation shot down.

bypass_media = true

**Comment by rayedbs** [comment]
@kierandavies 
Sorry but this config is done from the begaining for me: but even with bypass_media mode, it is nor possible to handle this number off calls with a real server!!!!!
did you do anything else??
thank you

**Comment by smrdoshi** [comment]
@rayedbs 

Did you check which processes are taking more load on your server when you reach 200 CC?

**Comment by dedayoa** [comment]
Barring any other problem, the typical culprit is audio transcoding. With your specs, you SHOULD be able to handle more than 200 concurrent calls, but toss in transcoding and well things start to heat up.
Try to stick with 1 codec across the board - if you can.
As for bypass_media, you can read more at https://wiki.freeswitch.org/wiki/Bypass_Media.

**Comment by smrdoshi** [comment]
No further activity. Closing the issue.
