### ISSUE TITLE
inbound GSM to Outbound PCMU,PCMA

### ISSUE THREAD

**Issue by dipenpatel235** [iNextrix/ASTPP#205]
hello..
i have setup free switch as per your setup step.

now my gateway required PCMU,PCMA codec.

so i have set below setting in sip profile
inbound-codec-prefs=GSM  (that i have set in sip phone )
outbound-codec-prefs=PCMU,PCMA
disable-transcoding=true

But still not connect GSM to PCMU,PCMA 

Let me know if anything is wrong by me.
Thanks

**Comment by smrdoshi** [comment]
I doubt if that will work or not. Capture sip log of your call and send.
Use pastebin.com.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by dipenpatel235** [comment]
ok...
thanks please see below pastbin log
Sending GSM inbound codec and want to send to gateway PCMU,PCMA

https://pastebin.com/bL1gW1RV

**Comment by smrdoshi** [comment]
1. 2017-05-27 01:46:02.775480 [DEBUG] mod_sofia.c:437 Channel
   sofia/default/917586911121 hanging up, cause: RECOVERY_ON_TIMER_EXPIRE
   2. 2017-05-27 01:46:02.775480 [DEBUG] switch_core_state_machine.c:60
   sofia/default/917586911121 Standard HANGUP, cause: RECOVERY_ON_TIMER_EXPIRE


Enable sip log using "sofia global siptrace on" command in fs_cli and
provide sip log of your call.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by dipenpatel235** [comment]
ok..
please download below log after done sofia global siptrace on
https://pastebin.com/9Q31yEM7

Thanks

**Comment by Neurotec** [comment]
Hi
When a call have two kinds of codecs  you must enable transcoding.
disable-transcoding=false
By default freeswitch have inbound-late-negotiaton=true change to false this will forcé match codecs before start routing.

If nothing works you can add into gateways extra, absolutec_codec_string="PCMU,PCMA"

El 26 de mayo de 2017 2:07:18 GMT-05:00, Dipen Patel <notifications@github.com> escribió:
>hello..
>i have setup free switch as per your setup step.
>
>now my gateway required PCMU,PCMA codec.
>
>so i have set below setting in sip profile
>inbound-codec-prefs=GSM  (that i have set in sip phone )
>outbound-codec-prefs=PCMU,PCMA
>disable-transcoding=true
>
>But still not connect GSM to PCMU,PCMA 
>
>Let me know if anything is wrong by me.
>Thanks
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/iNextrix/ASTPP/issues/205

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by dipenpatel235** [comment]
hello..
thanks for that info..
add into gateways extra, absolutec_codec_string="PCMU,PCMA" 
i can't seen extra option in Gateway so i have added in Dialplan Variable.

here i attached mine settings screenshot.
Please look it.

![gateway](https://cloud.githubusercontent.com/assets/8135097/26537786/d31cdd32-445f-11e7-969a-4722160efda3.PNG)
![profile1](https://cloud.githubusercontent.com/assets/8135097/26537787/d31ccc84-445f-11e7-9e5b-b8c9d8525aa4.PNG)
![profile2](https://cloud.githubusercontent.com/assets/8135097/26537788/d3230ba8-445f-11e7-9af3-5d5948f69bc0.PNG)
![profile3](https://cloud.githubusercontent.com/assets/8135097/26537789/d328c778-445f-11e7-8fcd-0a18d711bd0f.PNG)
