### ISSUE TITLE
cdrs table field for "callerid" has a limit of 30 characters.

### ISSUE THREAD

**Issue by SpaceJelly** [iNextrix/ASTPP#209]
This is a modification request, not an issue as such however it'd be a really simple and nice tweak.

In the cdrs table, the field for "callerid" has a limit of 30 characters. It would be really good to increase this field length to say 120 characters.

The reason for this is that many of our customers have PBX's that can send name and number for the relevant extensions that call out:
EG: "Mr William Smith" <+441234567890>

This enables us to give personalised billing to each customer by listing not only the numbers dialled but what extension made the call.

As the example above is over 30 characters, it gets truncated. If it was larger, then it wouldn't suffer this issue.

Thanks!

**Comment by smrdoshi** [comment]
Issue has been fixed in version v3.5. Upgrade to latest version and test it out.
