### ISSUE TITLE
Termination Rates Not Found

### ISSUE THREAD

**Issue by HorselessName** [iNextrix/ASTPP#217]
Dialed number (041996826260) termination rates not found!!

I'm dialing and it's not working.
How do i fix this ?

Rate Group is Created and Trunk Select.
Origination Rate is created, Force Trunk is selected.
Termination Group is created and selected.

It's all configured correctly, but when i try to call, that error appears.
I tried to search for a solution, but still did'nt found it.

**Comment by HorselessName** [comment]
1. Rate group is mapped with proper trunk.
2. Origination rates exist for the dialled number.
3. Termination rates has the same prefix and cost is less than Origination rates.
4. termination rates have same trunk mapped in rate group.

**Comment by smrdoshi** [comment]
Provider call log.

**Comment by HorselessName** [comment]
Hi. I fixed it.
The problem was that Termination Rates per minute cost was bigger than the Origination Rates ones.
Thank you!

**Comment by smrdoshi** [comment]
Perfect!!
