### ISSUE TITLE
Translation to another Language

### ISSUE THREAD

**Issue by HorselessName** [iNextrix/ASTPP#218]
I would like to translate ASTPP to PT_BR
Do i have permission to do that ?
And if the answer is yes... How ?

Where are the language files located ?

**Comment by smrdoshi** [comment]
Of course you can do that. You can use github to do the work and once you done, send us merge request. We will review your work and merge it to main source. 

All important language files are located at below places : 
/var/www/html/astpp/application/modules/<MODULENAME>/language/
/var/www/html/astpp/application/language/

You will need to create new folder with Brazilian Portuguese language code. 

Let us know if you need further help. We will be more than happy to assist you further.

**Comment by HorselessName** [comment]
Ok.

**Comment by rxsantos** [comment]
Hi smrdoshi, 
I tried to put the translations I did in git but without success.
Is there another way to send translations?

**Comment by leandrowcampos** [comment]
@rxsantos, share in link on group https://groups.google.com/forum/#!topic/astpp/U_7rR6e3FO4 or attach here for we test.

**Comment by smrdoshi** [comment]
Hi Guys, 

We just add Portuguese Brazilian language support in Version 3.5. 
You can get the latest source and start using it. 

Special thanks to Mr. Roberto Xavier @rxsantos for contribution.

**Comment by adrianodvieira** [comment]
Hi!
I updated the version to 3.5, appears no bottom corner of the screen the flag of Brazil, however, I click on the flag and do not translate Astpp into Portuguese.
Tks

**Comment by smrdoshi** [comment]
Follow below steps to do that :

sudo locale-gen es_ES
sudo locale-gen es_ES.UTF-8
sudo locale-gen fr_FR
sudo locale-gen fr_FR.UTF-8
sudo locale-gen pt_BR
sudo locale-gen pt_BR.UTF-8
sudo update-locale

restart nginx and then try. It should work.

Please provide feedback.



‌
<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance on the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by adrianodvieira** [comment]
Hi!

Done in the procedure, but did not succeed, system does not apply the Portuguese language.

@rxsantos only succeeded by reinstalling the system.

Tks

**Comment by smrdoshi** [comment]
Can we get access of your system?

If possible then send me your server access information on
samir.doshi@inextrix.com.




<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance on the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by adrianodvieira** [comment]
Hi!
I send access to e-mail!
tks

**Comment by adrianodvieira** [comment]
It Worked!
tks @smrdoshi
