### ISSUE TITLE
V3.5 Credit refill issue

### ISSUE THREAD

**Issue by SpaceJelly** [iNextrix/ASTPP#219]
Hey there, 

Just created a new customer on v3.5. (Updated from 3 this morning) 

Created as postpaid as all of ours are centrally billed via a custom external billing engine (use astpp for call handling only)

Added credit refill and rather than the customers value being a positive figure as it always has been on earlier versions it actually showed as a negative!

So, customer balance = 0
Credit 500
New customer balance = -500!

Should be + 500

Cheers!

Neil

**Comment by smrdoshi** [comment]
Hi Neil, 

We have changed bit of concept to manage postpaid customer balance. So that is the impact of it. 
I gave you solution for existing customers in other issue #220

**Comment by SpaceJelly** [comment]
ok, so you're saying that you've made a very serious change to the way the system works and have not mentioned this?! 

That's not very good at all and this change has a serious impact in how we use the software.

Please, revert back to how it used to work for postpaid as it makes no sense at all as it is.

**Comment by smrdoshi** [comment]
True. We completely missed to update in changelog. However we noticed that issue as soon as you reported and checked all possible place if we missed anything else. 

That is not possible to revert the changes as that is impacting on entire accounting part of application. You can simply modify your custom function and do needful adjustments.

**Comment by SpaceJelly** [comment]
ok, so it will stay. Could you briefly document the changes for postpaid
customers then just so there's no further misunderstandings!

EG: What happens to balance when call made, what happens when invoice
generated. What happens when invoice paid, etc.

As mentioned, we use external software to bill and monitor balances so
understanding these changes is critical!

Thanks :)

**Comment by smrdoshi** [comment]
Note. I will get you information and also document it and release the
change to avoid confusion.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=samir.doshi@inextrix.com&idSignature=22>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.
