### ISSUE TITLE
Not able to import DID csv file

### ISSUE THREAD

**Issue by heintonny** [iNextrix/ASTPP#22]
From the "DID" menu I try to import a csv files with DID's.

I get the following PHP permission error:

A PHP Error was encountered

Severity: Warning

Message:
move_uploaded_file(/var/www/html/astpp/assets/Rates_File/uploaded_files/ASTPP-DIDs-2016-08-04
14:20:20.csv): failed to open stream: Permission denied

Filename: controllers/did.php

Line Number: 594

A PHP Error was encountered

Severity: Warning

Message: move_uploaded_file(): Unable to move '/tmp/php9D5jDv' to
'/var/www/html/astpp/assets/Rates_File/uploaded_files/ASTPP-DIDs-2016-08-04
14:20:20.csv'

Filename: controllers/did.php

Line Number: 594

Steps to Reproduce: 
Import a csv file with DID's

Additional Information: 
This is a new installation done by ASTPP Support.

**Comment by dev-astpp** [comment]
Its just permission issue give 777 permission to your directory it will work
