### ISSUE TITLE
V3.5 Cannot Call Out - Insufficient Credit Error

### ISSUE THREAD

**Issue by SpaceJelly** [iNextrix/ASTPP#220]
Hi there,

Looks like there's a problem with the credit lookup. 

Account has credit, is postpaid and credit is 500

However when trying to call getting this in the logs!

2017-09-05 17:22:54.181254 [WARNING] switch_cpp.cpp:1360 [ASTPP] [DOAUTHORIZATION] [8212272956] Insufficent balance (0) to make calls..!!
784929ca-9256-11e7-9785-791b0b72e60d 2017-09-05 17:22:54.181254 [WARNING] mod_dptools.c:1713 Accountcode 8212272956 doesn't have sufficiant fund!!

Attaching full log and image showing credit.
[errorlog.txt](https://github.com/iNextrix/ASTPP/files/1278151/errorlog.txt)
![hascredit](https://user-images.githubusercontent.com/29196157/30071777-fa7ae560-925f-11e7-877c-385ab3f4a8ea.PNG)

Thanks! Neil

**Comment by SpaceJelly** [comment]
ok, As per my other entry where crediting creates a negative figure, if I revert the balance value back to a negative figure then it works!

So for now all my balances look like this!
![balances](https://user-images.githubusercontent.com/29196157/30072184-71b867c8-9261-11e7-80c8-303c689ddf10.PNG)

**Comment by smrdoshi** [comment]
Please execute below query to update postpaid customer balance, 
update `accounts`  balance = balance*(-1) where posttoexternal=1; That will resolve the issue.
