### ISSUE TITLE
Cant import new rates version 3.5

### ISSUE THREAD

**Issue by genlangtechnologies** [iNextrix/ASTPP#221]
Error Number: 1054

Unknown column 'old_cost' in 'field list'

INSERT INTO routes (pattern, comment, connectcost, includedseconds, cost, init_inc, inc, precedence, last_modified_date, pricelist_id, trunk_id, reseller_id, creation_date) VALUES ('^27106150.*','CELL C - GEOGRAPHIC','0','0','0.290928','1','1','','2017-09-07 17:35:28','6','0','0','2017-09-07 17:35:28'),('^27128820.*','CELL C - GEOGRAPHIC','0','0','0.290928','1','1','','2017-09-07 17:35:28','6','0','0','2017-09-07 .. """""" cut out the bulk of the import """"".........*','CELL C - MOBILE','0','0','0.3819','1','1','','2017-09-07 17:35:28','6','0','0','2017-09-07 17:35:28') ON DUPLICATE KEY UPDATE old_cost = IF(VALUES(cost) != cost,cost,old_cost), effective_date = IF(VALUES(cost) > cost,'',(IF(VALUES(cost) < cost,'',effective_date))), comment=VALUES(comment), connectcost=VALUES(connectcost), includedseconds=VALUES(includedseconds), cost=VALUES(cost), init_inc=VALUES(init_inc), inc=VALUES(inc), last_modified_date=VALUES(last_modified_date), status=IF(VALUES(cost) = '-1','1','0')

Filename: /var/www/html/astpp/modules/rates/models/rates_model.php

Line Number: 375

**Comment by Exgard** [comment]
Hi.
this is a issue, because,in the database, doesn't exist the column "old_cost".
i fix, this issue, adding the colum old_cost in the database routes.
how:
1) i search the password of user root for mysql.
vim /var/lib/astpp/astpp-config.conf
2) execute the command: mysql -u root -p, after write the password of mysql root user
3) execute the command: **use astpp;**
4) execute: **show tables;**
5) execute: **alter table routes add old_cost varchar (255);**
6) try again.

Best Regard.

**Comment by smrdoshi** [comment]
We have resolved that issue in github source code last week. You can run
update script to update your server source to latest one.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=samir.doshi@inextrix.com&idSignature=22>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.
