### ISSUE TITLE
Cannot create DID

### ISSUE THREAD

**Issue by tridcatij** [iNextrix/ASTPP#223]
Hello, was trying to add DID on the fresh ASTPP install.

> A Database Error Occurred
> 
> Error Number: 1054
> 
> Unknown column 'leg_timeout' in 'field list'
> 
> `INSERT INTO 'dids' ('id', 'number', 'country_id', 'city', 'province', 'provider_id', 'accountid', 'connectcost', 'includedseconds', 'cost', 'init_inc', 'inc', 'setup', 'monthlycost', 'leg_timeout', 'call_type', 'extensions', 'maxchannels', 'status', 'assign_date') VALUES ('', '6546546544', '200', '', '', '3', '2', '0', '', '0', '', '', '0', '0', '0', '3', '', '', '0', '2017-09-11 09:11:34')`
> 
> Filename: /var/www/html/astpp/modules/did/models/did_model.php
> 
> Line Number: 33

**Comment by smrdoshi** [comment]
Please check which version of ASTPP are you using. 

If you are on 3.0 then run update.sh script to update to latest version.

**Comment by tridcatij** [comment]
It's helped, thank you.

Btw, during update there were some errors on Centos 7:

`./update.sh: line 68: apt-get: command not found`
`./update.sh: line 69: apt-get: command not found`
`./update.sh: line 71: dig: command not found`
`./update.sh: line 73: ifconfig: command not found`

**Comment by smrdoshi** [comment]
Please download update.sh file again and try again. It should work now.

**Comment by tridcatij** [comment]
Thank you. All is fine now.
