### ISSUE TITLE
Incorrect Termination's rate value on edit.

### ISSUE THREAD

**Issue by tridcatij** [iNextrix/ASTPP#224]
Hello again.
Centos 7, fresh ASTPP 3.5

Just created new termination rate with value **0.01** and saved it. In the rates' table all is fine, but if I want to edit this rate - in the modal window there is bit different value - **0.00999966**

**Comment by smrdoshi** [comment]
What's your system base currency and admin currency?

You can get base currency information from : Settings -> Global
Admin currency from admin profile.




<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=samir.doshi@inextrix.com&idSignature=22>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by tridcatij** [comment]
Global was EUR, admin's - USD. Changing admin's to the EUR fixed the issue.
