### ISSUE TITLE
Unable to register gateway with numeric name

### ISSUE THREAD

**Issue by drenda** [iNextrix/ASTPP#225]
Using a number as name for a gateway, the registration always fails.

**Comment by smrdoshi** [comment]
I don't think ASTPP or FS needs to do anything with your gateway username.
It must be your provider who might not be able to authenticate your gateway
information and sending forbidden.

Look into sip log and check what happening when you try to register
gateway.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=samir.doshi@inextrix.com&idSignature=22>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by drenda** [comment]
Hi,
I was referring to the "name", not the username. Provider information are ok. If the name is a number the registration fails, if I change just the name with a string, then the registration works.

**Comment by smrdoshi** [comment]
Ah i see. That's strange.
Capture the sip request while doing registration with numeric name and send
us.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=samir.doshi@inextrix.com&idSignature=22>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.
