### ISSUE TITLE
Disable invoice module

### ISSUE THREAD

**Issue by drenda** [iNextrix/ASTPP#227]
Would  be interesting have the ability to disable the issue of invoices. Sometimes invoices are issued by external applications and would be interesting ASTPP permit to avoid the generation and keep just the history of refill.

Thanks

**Comment by tridcatij** [comment]
You could just comment this task in the crontab.

**Comment by drenda** [comment]
I'm sorry but I don't see any reference to this task in the crontab.

**Comment by tridcatij** [comment]
On `crontab -e` you should see these ASTPP tasks:

> Generate Invoice
> 0 1 * * * cd /var/www/html/astpp/cron/ && php cron.php GenerateInvoice
> Low balance notification
> 0 1 * * * cd /var/www/html/astpp/cron/ && php cron.php UpdateBalance
> Low balance notification
> 0 0 * * * cd /var/www/html/astpp/cron/ && php cron.php LowBalance
> Update currency rate
> 0 0 * * * cd /var/www/html/astpp/cron/ && php cron.php CurrencyUpdate
> Email Broadcasting
> \* * * * * cd /var/www/html/astpp/cron/ && php cron.php BroadcastEmail
>

The first one is responsible for invoices

**Comment by drenda** [comment]
Ok got it. I was looking into /etc/crontab

Thanks, I'll try with that.

**Comment by drenda** [comment]
I tried but unfortunately as soon as I do a refill, the invoice is issued.

**Comment by smrdoshi** [comment]
You cannot disable invoice module as all accounting linked with it.
Disabling cron will only stop creating auto invoice generation which is
defined in invoice billing cycle of customer.

The idea way to disable that module is to modify code and remove/comment
the code.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=samir.doshi@inextrix.com&idSignature=22>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.
