### ISSUE TITLE
footer problem after update to 3.5

### ISSUE THREAD

**Issue by rockycrash83** [iNextrix/ASTPP#233]
Hi, after update ASTPP from 3.0 to 3.5 have problem with footer , when viewed, the footer overrides the bottom menu, screenshot attache. 
![footer](https://user-images.githubusercontent.com/32088749/30579455-71acaa12-9d21-11e7-9ebb-ddbab712fb23.png)

**Comment by smrdoshi** [comment]
We are unable to understand the issue. Can you check in
http://latest.astppbilling.org to confirm?
If you are getting it then provide us steps to reproduce the issue.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=samir.doshi@inextrix.com&idSignature=22>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by smrdoshi** [comment]
Waiting for the feedback.
