### ISSUE TITLE
Incorrect path in the Debian 8 install documentation

### ISSUE THREAD

**Issue by tridcatij** [iNextrix/ASTPP#236]
Hi there are incorrect paths in the docs for Debian 8 manual install:
`cp /usr/src/ASTPP/misc/odbc/cent_odbc.ini /etc/odbc.ini`
` cp /usr/src/ASTPP/misc/odbc/cent_odbcinst.ini /etc/odbcinst.ini`

Should be:
`cp /usr/src/ASTPP/misc/odbc/deb_odbc.ini /etc/odbc.ini`
` cp /usr/src/ASTPP/misc/odbc/deb_odbcinst.ini /etc/odbcinst.ini`

**Comment by kavinchauhan** [comment]
Hi @tridcatij 
Thanks for your kind attention on it.
It's corrected now.
