### ISSUE TITLE
Free Codes

### ISSUE THREAD

**Issue by countrdd** [iNextrix/ASTPP#237]
The blocked codes on the customer is a nice feature, it would also be nice to allow free codes per customer.

I.e. In my area my npa-nxx is 740779, I can dial free to 740772, 740773 etc. So it would be nice to have this factored in and calls from the subscriber would be free but my costs would still be calculated on the cdr.

Even better would be to allow a limit of X seconds for these free calls to the group. I.e.

60000 seconds a month total for any calls going to 740772/740773 after that bill accordingly.

**Comment by smrdoshi** [comment]
You can do that using package module where you can define number of free seconds and prefixes. Correct me if I wrong in understanding your concern.

**Comment by countrdd** [comment]
We have some clients that have multiple locations and depending on the Caller DID used when they dial out. It may actually be better to add this to the DID instead. By doing it in packages,  it would require a large amount of maintenance and packages to be developed and would not work via the packages module.

**Comment by smrdoshi** [comment]
Your explanation for feature request is not pretty clear. Would you please
give some example and explain?



<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.
