### ISSUE TITLE
 Blocked Codes

### ISSUE THREAD

**Issue by gudge25** [iNextrix/ASTPP#238]
Fresh install  2 times 3.5 ver
autoinstaller+ manual installation 
the same issue
 Blocked Codes  cannot be  added 
it doesn't save

**Comment by smrdoshi** [comment]
Hi @gudge25 

I just tried on demo and its working. 
http://latest.astppbilling.org/accounts/customer_blocked_prefixes/2/

Please provide steps to reproduce the issue and also operating system on which ASTPP is setup.

**Comment by gudge25** [comment]
Centos 7 
Log into astpp
Account -> customers-> select customer -> Blocked  codes --- > SELECT ADD and then add from the list

**Comment by smrdoshi** [comment]
Tried same thing and its working.

Hmm maybe browser?
Which browser are you using? and can you try with other browser?



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=samir.doshi@inextrix.com&idSignature=22>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by gudge25** [comment]
maybe your OS is not CENTOS 7?

**Comment by gudge25** [comment]
Chrome  + Firefox -- same isuue

**Comment by gudge25** [comment]
5 times reinstall no luck

**Comment by dedayoa** [comment]
Sorry to bump your thread, but I've been wondering, "what does **blocked codes** do?"

**Comment by smrdoshi** [comment]
@dedayoa blocked codes means block prefix feature of customer. 
If you do not want to allow UK calls to specific customer then can just add UK code in block code module for customer and then system will stop calling to that destination. 

@gudge25 Is your issue resolved?
