### ISSUE TITLE
cant  Upload  file Using   termination_rate_mapper

### ISSUE THREAD

**Issue by gudge25** [iNextrix/ASTPP#241]
/rates/termination_rate_mapper_preview_file/

Blank screen   While Uploading

[Untitled 1.csv.zip](https://github.com/iNextrix/ASTPP/files/1359246/Untitled.1.csv.zip)

**Comment by kritapsdravnieks** [comment]
Try to strip down your rate file below 10k lines. Found this limitation while back.

**Comment by smrdoshi** [comment]
@gudge25 

Does it work?

**Comment by gudge25** [comment]
yes i tried second time  and bingo

**Comment by watoan** [comment]
I faced the same here, running 3.6 with debian 8
After select the csv file and click Import, blank page, no error shown even turned on dispay_errors from php.ini, no error in nginx log
Please help, thanks.

Location: /rates/termination_rate_import_mapper/

**Comment by kristapsdravnieks** [comment]
do 
cd /usr/src/ASTPP
chmod +x update.sh
./update.sh

If there you have skipped any step for setting folder permission or something, update script will fix it for you.
