### ISSUE TITLE
Annual DID billing

### ISSUE THREAD

**Issue by dedayoa** [iNextrix/ASTPP#243]
Dear Team,
In my case, I bill my customers for DIDs once a year. Currently, having to deduct DID fees monthly (or daily) means customers can draw from the balance for DIDs as call credit.
I would like to implement this. What special case/side effects should I look out for in getting this done.
Is there a "technique" to get this done, without going the route of coding this?
Regards,

**Comment by smrdoshi** [comment]
Nope that's not possible to do that without code modifications.



<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by AlexHeylin** [comment]
You could - set DIDs to zero cost and manually invoice once per year.

**Comment by dedayoa** [comment]
@AlexHeylin That my current process. Would be nice to have it all automated though. It will become problematic as users grow.
