### ISSUE TITLE
Rate Import with Mapper.  (Updated Fix Supplied)

### ISSUE THREAD

**Issue by countrdd** [iNextrix/ASTPP#244]
It is saying the records are processed, but nothing is actually inserted into the outbound routes table.

**Comment by countrdd** [comment]
When I print the Result from the bulk insert this is what is coming back.

A PHP Error was encountered

Severity: Warning

Message: Missing argument 2 for rates_model::bulk_insert_termination_rate(), called in /var/www/html/astpp/application/modules/rates/controllers/rates.php on line 1331 and defined

Filename: models/rates_model.php

Line Number: 312

A PHP Error was encountered

Severity: Notice

Message: Undefined variable: count

Filename: models/rates_model.php

Line Number: 331


Fix: 
at Line number 1287 Add:  $row_count=0
at Line number 1325 Add: $row_count++
at line number 1333 add second argument $row_count
 $result = $this->rates_model->bulk_insert_termination_rate ( $new_final_arr,$row_count );

**Comment by countrdd** [comment]
Also, Found another bug....
Lines 1299, 1301, 1303, 1306 and 1309
"0" should be replaced with "".

If not the logic is setting the value to 0, and then adding then concatenating the default/prefix value to 0. Making a default value of 6 into 60.

**Comment by countrdd** [comment]
Index: web_interface/astpp/application/modules/rates/controllers/rates.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- web_interface/astpp/application/modules/rates/controllers/rates.php	(revision 86e17fcc5ba948f12ebafa461213ae37b52c6c21)
+++ web_interface/astpp/application/modules/rates/controllers/rates.php	(revision )
@@ -1284,6 +1284,7 @@
 		$csv_tmp_data = $this->csvreader->parse_file ( $full_path . $terminationrate_file_name, $new_final_arr_key, $check_header );
 		
 		$i = 0;
+		$row_count = 0;
 		foreach ( $csv_tmp_data as $key => $csv_data ) {
 			if (isset ( $csv_data [$this->input->post ( "pattern-select" )] ) && $csv_data [$this->input->post ( "pattern-select" )] != '' && $i != 0 && $i != 1) {
 				$str = null;
@@ -1294,12 +1295,14 @@
 				$csv_data ['prepend'] = ($this->input->post ( "prepend-prefix" )) ? $this->input->post ( "prepend-prefix" ) . $csv_data ['prepend'] : $csv_data ['prepend'];
 				$csv_data ['comment'] = ($this->input->post ( "comment-select" )) ? $csv_data [$this->input->post ( "comment-select" )] : "";
 				$csv_data ['comment'] = ($this->input->post ( "comment-prefix" )) ? $this->input->post ( "comment-prefix" ) . $csv_data ['comment'] : $csv_data ['comment'];
-				$csv_data ['connectcost'] = ($this->input->post ( "connectcost-select" )) ? $csv_data [$this->input->post ( "connectcost-select" )] : "0";
+				$csv_data ['connectcost'] = ($this->input->post ( "connectcost-select" )) ? $csv_data [$this->input->post ( "connectcost-select" )] : "";
 				$csv_data ['connectcost'] = ($this->input->post ( "connectcost-prefix" )) ? $this->input->post ( "connectcost-prefix" ) . $csv_data ['connectcost'] : $csv_data ['connectcost'];
-				$csv_data ['includedseconds'] = ($this->input->post ( "includedseconds-select" )) ? $csv_data [$this->input->post ( "includedseconds-select" )] : "0";
+				$csv_data ['includedseconds'] = ($this->input->post ( "includedseconds-select" )) ? $csv_data [$this->input->post ( "includedseconds-select" )] : "";
 				$csv_data ['includedseconds'] = ($this->input->post ( "includedseconds-prefix" )) ? $this->input->post ( "includedseconds-prefix" ) . $csv_data ['includedseconds'] : $csv_data ['includedseconds'];
-				$csv_data ['inc'] = ($this->input->post ( "inc-select" )) ? $csv_data [$this->input->post ( "inc-select" )] : "0";
+				$csv_data ['inc'] = ($this->input->post ( "inc-select" )) ? $csv_data [$this->input->post ( "inc-select" )] : "";
 				$csv_data ['inc'] = ($this->input->post ( "inc-prefix" )) ? $this->input->post ( "inc-prefix" ) . $csv_data ['inc'] : $csv_data ['inc'];
+				 $csv_data ['init_inc'] = ($this->input->post ( "init_inc-select" )) ? $csv_data [$this->input->post ( "init_inc-select" )] : "";
+				 $csv_data ['init_inc'] = ($this->input->post ( "init_inc-prefix" )) ? $this->input->post ( "init_inc-prefix" ) . $csv_data ['init_inc'] : $csv_data ['init_inc'];
 				$csv_data ['precedence'] = ($this->input->post ( "precedence-select" )) ? $csv_data [$this->input->post ( "precedence-select" )] : "";
 				$csv_data ['precedence'] = ($this->input->post ( "precedence-prefix" )) ? $this->input->post ( "precedence-prefix" ) . $csv_data ['precedence'] : $csv_data ['precedence'];
 				$csv_data ['strip'] = ($this->input->post ( "strip-select" )) ? $csv_data [$this->input->post ( "strip-select" )] : "";
@@ -1321,6 +1324,8 @@
 					$new_final_arr [$i] ['inc'] = isset ( $csv_data ['inc'] ) ? $csv_data ['inc'] : 0;
 					$new_final_arr [$i] ['precedence'] = isset ( $csv_data ['precedence'] ) ? $csv_data ['precedence'] : '';
 					$new_final_arr [$i] ['strip'] = isset ( $csv_data ['strip'] ) ? $csv_data ['strip'] : '';
+					$new_final_arr [$i] ['init_inc'] = isset ( $csv_data ['init_inc'] ) ? $csv_data ['init_inc'] : 0;
+					$row_count ++;
 				}
 			}
 			
@@ -1328,7 +1333,7 @@
 		}
 		// print_r($new_final_arr);exit;
 		if (! empty ( $new_final_arr )) {
-			$result = $this->rates_model->bulk_insert_termination_rate ( $new_final_arr );
+			$result = $this->rates_model->bulk_insert_termination_rate ( $new_final_arr,$row_count );
 		} else {
 			
 			$this->session->set_flashdata ( 'astpp_errormsg', 'Error - Nothing selected to import/process!' );

**Comment by countrdd** [comment]
[ASTPP35.patch.txt](https://github.com/iNextrix/ASTPP/files/1375040/ASTPP35.patch.txt)

**Comment by devangn** [comment]
Thank @countrdd 
Is that possible for you to send PR for this modification so that we can verify and merge it with source?

**Comment by countrdd** [comment]
I have not masters pR's yet.
