### ISSUE TITLE
Mass Create Customer From Reseller Panel

### ISSUE THREAD

**Issue by rokibsdsl** [iNextrix/ASTPP#249]
Customer "Mass Create" From Reseller Panel does not work. From Admin panel works fine.

**Comment by smrdoshi** [comment]
Issue has been resolved now.

**Comment by rokibsdsl** [comment]
The sip devices not created though....There should be an option to generate sip devices like Admin Panel.
Because it is called mass create....so it will be painful to create sip devices for each customer manually.

**Comment by smrdoshi** [comment]
Ok noted. Right that is missing. 
We will add that.

**Comment by smrdoshi** [comment]
Done
