### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by tridcatij** [iNextrix/ASTPP#251]
Hello,
Does ASTPP support PHP7+? Is it safe to update from 5.6?

**Comment by smrdoshi** [comment]
Nope ASTPP does not work on PHP 7. It will be supported from ASTPP 4.0.




<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

<https://mailtrack.io/trace/link/ad1c36e9435bde72b7e074728e8be526962889a6?url=http%3A%2F%2F%2F&userId=1840855&signature=08a4f685e35256c2>Best
Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com
<https://mailtrack.io/trace/link/8e7ee259cdf61cc77c16ac94cc35824d8700095f?url=http%3A%2F%2Fwww.inextrix.com&userId=1840855&signature=b9ff352c8cc3984c>


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by tridcatij** [comment]
Just migrated to 7.0.24.

For those who might be interested - you need to change mysql driver to the mysqli and make some changes in the CI files, like these one - [StackOverflow](https://stackoverflow.com/questions/43840941/codeigniter-hmvc-error-after-updating-php-to-php-7)

**Comment by smrdoshi** [comment]
Hi @tridcatij 

that's great news. 

It will be great if you contribute those modified files to community. 

You can directly create merge request in github and we will merge it. but in case If you do not know much about merge request then you can send us code directly, we will plug it and release the code in open source.
