### ISSUE TITLE
Change CDR CSV export duration field from minutes to seconds?

### ISSUE THREAD

**Issue by kritapsdravnieks** [iNextrix/ASTPP#255]
Hi!
Can anyone suggest, how to change CDR CSV export duration field from minutes to seconds?
Ideally would be to make in configurable.

**Comment by smrdoshi** [comment]
Open search panel of CDR report, change Minute to Seconds in Display
records in dropdown and then export.


‌
<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

<https://mailtrack.io/trace/link/615621e17ce2e84493562fa2888efae2af05d663?url=http%3A%2F%2F%2F&userId=1840855&signature=581ae72f477dbc9d>Best
Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com
<https://mailtrack.io/trace/link/4c7c7b766a21eb2b96eada37296d9b6c1e5bc65b?url=http%3A%2F%2Fwww.inextrix.com&userId=1840855&signature=ff87599ddd1eeba7>


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.
