### ISSUE TITLE
Database Download

### ISSUE THREAD

**Issue by AlexHeylin** [iNextrix/ASTPP#257]
Fails because the function is passed the file name without the full path.
Adding in the path (statically for quick fix) worked.

**web_interface/astpp/application/modules/systems/controllers/systems.php**
Starting at line 571:
```
		$result_array = $result->result_array ();
		if ($result->num_rows () > 0) {
			$path = $result_array [0] ['path'];
// For some reason we're getting just the file name - so fix this up
$path = '/var/www/html/astpp/database_backup/' . $path ;
			$filename = basename ( $path );
			$len = filesize ( $path );
```

**Comment by smrdoshi** [comment]
We used variable in place of static path. 
Please update source code and confirm. If working then close the issue.
