### ISSUE TITLE
$cost always logged as 0 in astpp.cdr.php 

### ISSUE THREAD

**Issue by AlexHeylin** [iNextrix/ASTPP#259]
Need to move logger line below assignment of $cost?  As is $cost has the value of 0 that's assigned at the top of file.

	// Calculate parent cost if customer have any parent
	$parent_cost = ($parentid > 0) ? calc_cost ( $dataVariable, $origination_rate [$parentid], $logger, $decimal_points ) : $provider_cost;
	$logger->log ( "Parent - Debit :" . $debit . " Cost : " . $cost . " Provider Cost : " . $parent_cost );
	
	// Initialize final cost variable to use for billing
	$cost = ($parent_cost > 0) ? $parent_cost : $provider_cost;

Thanks

**Comment by AlexHeylin** [comment]
Should it also be below
// Outbound call entry for all type of calls
	$logger->log ( "*********************** OUTBOUND CALL ENTRY START *************" );
?

**Comment by smrdoshi** [comment]
I don't understand what difference will it make if we will move longer to other line? 

Are you getting $cost 0 in CDR or just in logger?

**Comment by AlexHeylin** [comment]
I was getting zero cost in CDR (now fixed) but as it is now, the logger
reports zero all the time. I know it's minor but wouldn't it be better if
the logger was accurate?
Thanks Samir
Alex


On 15 Nov 2017 08:54, "Samir Doshi" <notifications@github.com> wrote:

I don't understand what difference will it make if we will move longer to
other line?

Are you getting $cost 0 in CDR or just in logger?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/iNextrix/ASTPP/issues/259#issuecomment-344526607>, or mute
the thread

**Comment by smrdoshi** [comment]
Ah ok. Got your point. 
Will do needful.
