### ISSUE TITLE
astpp 3.5 web not open

### ISSUE THREAD

**Issue by dipenpatel235** [iNextrix/ASTPP#260]
Hello.
I have installed astpp3.5 on centos 7 64 bit
all steps are successfully executed.

now when i am trying to open my link http://myip:8089 then it show 500 internal error.
here i have attached screen shot.

So not getting idea what is wrong.
please help
Thanks
Dipen

![500_internal_error](https://user-images.githubusercontent.com/8135097/32658512-4dee1424-c640-11e7-871c-45cd36022513.png)

**Comment by tridcatij** [comment]
Check your `php.ini`
There should be `short_open_tag = On`

**Comment by smrdoshi** [comment]
This is not a bug. If you have problem in setup then use report your query in google group. https://groups.google.com/forum/#!forum/astpp
