### ISSUE TITLE
Crontab entries missing user which makes cron stop working entirely

### ISSUE THREAD

**Issue by AlexHeylin** [iNextrix/ASTPP#261]
The crontab entries are added without a user name which causes
cron[510]: Error: bad username; while reading /etc/crontab
cron[510]: (*system*) ERROR (Syntax error, this crontab file will be ignored)
in syslog.  This explains why my cron.hourly hasn't been running.

Inserting a valid user (like root - NOT recommended for production) between the `* * *` and the `cd` makes it work
```bash
# Generate Invoice
0 1 * * * root cd /var/www/html/astpp/cron/ && php cron.php GenerateInvoice
# Low balance notification
0 1 * * * root cd /var/www/html/astpp/cron/ && php cron.php UpdateBalance
# Low balance notification
0 0 * * * root cd /var/www/html/astpp/cron/ && php cron.php LowBalance
# Update currency rate
0 0 * * * root cd /var/www/html/astpp/cron/ && php cron.php CurrencyUpdate
# Email Broadcasting
0 0 * * * root cd /var/www/html/astpp/cron/ && php cron.php BroadcastEmail
```

**Comment by ketan-kothari** [comment]
@AlexHeylin 

You can setup astpp script in cron like below which is already in installation script. Also that is working fine on centos/debian.

setup_cron()
{
		if [ ${DIST} = "DEBIAN" ]; then
			CRONPATH='/var/spool/cron/crontabs/astpp'
		elif [ ${DIST} = "CENTOS" ]; then
			CRONPATH='/var/spool/cron/astpp'
		fi
		echo "# Generate Invoice   
		0 1 * * * cd /var/www/html/astpp/cron/ && php cron.php GenerateInvoice
		# Low balance notification
		0 1 * * * cd /var/www/html/astpp/cron/ && php cron.php UpdateBalance
		# Low balance notification
		0 0 * * * cd /var/www/html/astpp/cron/ && php cron.php LowBalance		
		# Update currency rate
		0 0 * * * cd /var/www/html/astpp/cron/ && php cron.php CurrencyUpdate
		# Email Broadcasting
		* * * * * cd /var/www/html/astpp/cron/ && php cron.php BroadcastEmail
		" > $CRONPATH
		chmod 600 $CRONPATH
		crontab $CRONPATH
}
Still if you are getting any issue then you need to look in cron configuration on your server.
