### ISSUE TITLE
CurrencyUpdate will always fail because Yahoo have withdrawn the feed.  

### ISSUE THREAD

**Issue by AlexHeylin** [iNextrix/ASTPP#262]
Suggest using http://fixer.io/ with is provided by European Central Bank.
API can be a bit slow - but should live for a long time.

**Comment by smrdoshi** [comment]
Oh yeah. We getting "It has come to our attention that this service is being used in violation of the Yahoo Terms of Service. As such, the service is being discontinued. For all future markets and equities data research, please refer to finance.yahoo.com.". 

Thanks for letting us know. 

We will look at fixer.io. 

Does anyone have any other alternative which we can consider for implementation? If so then please let us know.

**Comment by AlexHeylin** [comment]
Thanks Samir.
I realise this is a feature request, but as this will get rewritten anyway
- would it be possible to have an option to allow a percentage decrease to
allow for currency exchange fees?
Thanks
Alex

**Comment by smrdoshi** [comment]
That's fine. We understand it may impact to many users who are using exchange on daily basis. We just want to know if someone else have any other service information which we can look at. As soon as service will be finalized, we will update the souce code and release updated currency script. 

Regarding percentage decrease, please explain with example for better understanding.

**Comment by AlexHeylin** [comment]
Re exchange loss (charge / fee) percentage -

Say the GBP/USD rate is 1.30 but we pay 3% fee, and we know we won't get
exactly the market rate anyway we might set a 4% "currency loss / fee" to
ensure we always cover the fees etc in the conversion.

$effective_rate = $market_rate * ( (100 - $currency_loss) / 100)

$effective_rate = 1.3 * ( ( 100 - 4) / 100 )
$effective_rate = 1.3 * ( 96 / 100 )
$effective_rate = 1.3 * ( 0.96 )

$effective_rate = 1.248


Now say we're doing USD/GBP at 0.8, still with 4% loss

$effective_rate = $market_rate * ( (100 - $currency_loss) / 100)

$effective_rate = 0.8 * ( ( 100 - 4) / 100 )
$effective_rate = 0.8 * ( 0.96 )

$effective_rate = 0.768

Currently reading in the daily market rate would lead to us understating
our costs (in USD) which would lead to overstating our profits in base
currency of GBP.
Apologies if I've misunderstood something in ASTPP, but I've only been
using it for a couple of weeks.
Thanks very much

**Comment by liveincan** [comment]
Have you considered Open Exchange Rates? The Forever Free Plan comes with, Hourly rate updates, Daily historical data and 1,000 API requests per month. The free plan link is a bit obscure so here it is:
https://openexchangerates.org/signup/free

**Comment by smrdoshi** [comment]
We have integrated fixer.io for upcoming version 3.6. The changes are
completed and committed to branch.


‌
<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance on the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.
