### ISSUE TITLE
Minor: Invoices page counts deleted invoices but (correctly) doesn't show them

### ISSUE THREAD

**Issue by AlexHeylin** [iNextrix/ASTPP#269]
To reproduce delete some invoices in ASTPP, check invoices table in DB and count those deleted & not deleted. Now check invoices page - only non-deleted invoices show in table, but in the table footer deleted invoices are counted in the numbers.

**Comment by smrdoshi** [comment]
We don't have delete invoice feature. How did delete those invoice? :)

**Comment by AlexHeylin** [comment]
Using the delete icon. See image in the docs you wrote ;-)
https://astppdoc.atlassian.net/wiki/plugins/servlet/mobile?contentId=2425077#content/view/2425077

**Comment by smrdoshi** [comment]
Oh that's draft invoice. I thought you found that button for confirmed
invoice ;)

Anyway we will check it out that issue.


<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

<https://mailtrack.io/trace/link/b514083b872cff3535aba27e87dcfcad0a1ba2c1?url=http%3A%2F%2F%2F&userId=1840855&signature=37d60ee6002c4b3f>Best
Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com
<https://mailtrack.io/trace/link/85c752481fafb4744d596a05ea81467c984d5dbe?url=http%3A%2F%2Fwww.inextrix.com&userId=1840855&signature=890f05b7d0d00dba>


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by smrdoshi** [comment]
Fixed.
