### ISSUE TITLE
Number Translation of Trunks for outgoing calls not working

### ISSUE THREAD

**Issue by watoan** [iNextrix/ASTPP#27]
Target: add prefix 1234 for DNIS for all outgoing calls
Example: destination number is 87654321, sending outgoing call to supplier becomes 123487654321
Action: Tried to put /1234 or "/1234" in number translation of trunks settings

But not working, outgoing call still sending out 87654321 without prefix

attached FS debug log for reference

[with_quote_log.txt](https://github.com/iNextrix/ASTPP/files/406296/with_quote_log.txt)
[without_quote_log.txt](https://github.com/iNextrix/ASTPP/files/406297/without_quote_log.txt)

**Comment by smrdoshi** [comment]
We have updated the source code to fix the issue. Please use the latest source code. 

Use "*/1234" in place of "/1234".

**Comment by watoan** [comment]
Updated and tried with latest script, now ASTPP sending the outbound number as 12347654321 (missing the first digit "8")

BTW, should I use with quotes "*/1234" or without quotes */1234 ??
I tested both got the same result, but which one is the correct syntax?

**Comment by smrdoshi** [comment]
Alright we got the problem and fixed it. Please update source code and test it out.
