### ISSUE TITLE
Immediate Dialtone After Dial

### ISSUE THREAD

**Issue by slango-im** [iNextrix/ASTPP#270]
Hi!

Sometimes termination providers have long IDD (initial dial delay). And calling card customers can be confused by silence.

Can ASTPP provide an immediate dial tone (even if fake) for the user to hear immediately and trying to dial?

**Comment by dedayoa** [comment]
What you're looking for is https://wiki.freeswitch.org/wiki/Variable_instant_ringback
You should add `session:execute("set","instant_ringback=true");`
just after L392 inside freeswitch/scripts/astpp/lib/astpp.callingcards.function.lua

I haven't tested this but it's (similar) worked for me on other projects.

**Comment by slango-im** [comment]
Thank you, @dedayoa dedayoa!

**Comment by dedayoa** [comment]
You're welcome @slango-im

**Comment by slango-im** [comment]
@dedayoa , just wanted to follow up on this. I added this line of code to the "astpp.callingcards.function.lua" file the instant ringback did not work. 

Were you able to make it work on another freeswitch?

**Comment by slango-im** [comment]
Any updates on this - perhaps ASTPP does not support this? 

We added `session:execute("set","instant_ringback=true");` but it still does not work.

**Comment by devangn** [comment]
@slango-im If the delay is from DID provider side than call will take time to reach to ASTPP server and no change to dialplan will work if call is not reaching to ASTPP server.

**Comment by eduardofoliveira** [comment]
@slango-im 
For outgoing calls ringing as soon as you select the gateway it is possible to make the following configuration:

In the Gateway DialPlan Variable:

bypass_media=false,instant_ringback=true,ringback=${us-ring}
