### ISSUE TITLE
BUG: DID mass csv import does not work as expected

### ISSUE THREAD

**Issue by Slamis** [iNextrix/ASTPP#271]
Example entry:
**DID,Country,Account,Per Minute Cost(CURRENCY),Initial Increment,Increment,Setup Fee(CURRENCY),Monthly Fee(CURRENCY),Call Type,Destination,Status
43232039578515,United Kingdom,9312436009,0,0,0,0,6,DID@IP/URL,43232039578515@some_url,Active
12123352312333,United States,9312436009,0,0,0,0,10,DID@IP/URL,12123352312333@some_url,Active**

In preview - all looks OK but after the actual import:
1. It ignores the Call type. always set as PSTN 
2. DID is not associated with the account

Also provider association is not working as well.

We use the latest Version 3.5

**Comment by Slamis** [comment]
Also, Why the provider is set in the import GUI? It means separation of DID csv per provider...
Can a provider field be added?

**Comment by smrdoshi** [comment]
This is not a bug. 

You will require to upload DIDs for each provider. 
You can customize code further and add provider field in import process.

**Comment by Slamis** [comment]
You totally missed my q. :) 
Please see the first part of the ticket.
The import it self works not good.

**Comment by Slamis** [comment]
You totally missed my q. :) 
Please see the first part of the ticket.
The import it self works not good.
Example entry:
DID,Country,Account,Per Minute Cost(CURRENCY),Initial Increment,Increment,Setup Fee(CURRENCY),Monthly Fee(CURRENCY),Call Type,Destination,Status
43232039578515,United Kingdom,9312436009,0,0,0,0,6,DID@IP/URL,43232039578515@some_url,Active
12123352312333,United States,9312436009,0,0,0,0,10,DID@IP/URL,12123352312333@some_url,Active

In preview - all looks OK but after the actual import:

It ignores the Call type. always set as PSTN
DID is not associated with the account
Also provider association is not working as well.

We use the latest Version 3.5

**Comment by Slamis** [comment]
Hi

Any Updates?

**Comment by ketan-kothari** [comment]
Please get the patch or update the source and verify, the issue is resolved.
