### ISSUE TITLE
V 3.5 - "File Uploading Fail Please Try Again" - Import of Termination Rates fails

### ISSUE THREAD

**Issue by ibwl** [iNextrix/ASTPP#274]
System is a fresh and clean install (CENTOS 7- ASTPP 3.5) as per

https://astppdoc.atlassian.net/wiki/spaces/ASTPP/pages/25427994/CentOS+7+Installation+v3.5

No matter what I try - even uploading the sample file for termination rates - the message "File Uploading Fail Please Try Again" shows up.

**Comment by ibwl** [comment]
It seems to be a permission issue:
/var/www/html/astpp/assets/Rates_File/uploaded_files

For some reason the web server process tries to write the .csv to above folder with user:group apache:apache. Apache is neither being used nor installed (as nginx is the default webserver now). Changing the group to apache and allowing group write permissions temporarily fixes the problem but this should be resolved for good in the code. Thanks!

**Comment by smrdoshi** [comment]
Resolved in v3.6.
