### ISSUE TITLE
Error with Debit Calculation for Durations > 4500 Seconds (v3.5)

### ISSUE THREAD

**Issue by sessionhub** [iNextrix/ASTPP#276]
Hi
Please there is a serious billing issue with v3.5
When Call Duration is greater than ~4500, the **debit** is ALWAYS == 1

'SELECT accountid, disposition, billseconds, debit, cost FROM astpp.cdrs WHERE accountid != 0 ORDER BY billseconds DESC LIMIT 12;'
+-----------+-----------------+-------------+------------+------------+
| accountid | disposition     | billseconds | debit      | cost       |
+-----------+-----------------+-------------+------------+------------+
|         8 | NORMAL_CLEARING |        7200 |   1.000000 | 768.000000 |
|         8 | NORMAL_CLEARING |        6361 |   1.000000 | 678.510000 |
|         8 | NORMAL_CLEARING |        5624 |   1.000000 | 599.890000 |
|         8 | NORMAL_CLEARING |        5282 |   1.000000 | 563.410000 |
|         8 | NORMAL_CLEARING |        5269 |   1.000000 | 562.030000 |
|         8 | NORMAL_CLEARING |        4901 |   1.000000 | 522.770000 |
|         8 | NORMAL_CLEARING |        4781 |   1.000000 | 509.970000 |
|        10 | NORMAL_CLEARING |        4332 | 902.500000 | 462.080000 |
|         8 | NORMAL_CLEARING |        4112 | 890.930000 | 438.610000 |
|        10 | NORMAL_CLEARING |        4105 | 855.210000 | 437.870000 |
|         8 | NORMAL_CLEARING |        4100 | 888.330000 | 437.330000 |
|         8 | NORMAL_CLEARING |        4079 | 883.780000 | 435.090000 |
+-----------+-----------------+-------------+------------+------------+

**Comment by smrdoshi** [comment]
We do not have any condition to calculate debit value. It's purly depends
on your origination rates and duration of calls.

Provide your call log astpp.log to check the calculation which is happening
with your calls.




<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

<https://mailtrack.io/trace/link/25781ca25997fa2c8c94aa1292f8ea6d636c91b8?url=http%3A%2F%2F%2F&userId=1840855&signature=9ec2fe60691ebd29>Best
Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com
<https://mailtrack.io/trace/link/782ff540a10e8d4b7c5b04db7da8159e31b3e1c4?url=http%3A%2F%2Fwww.inextrix.com&userId=1840855&signature=1044ed86e837198f>


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.
