### ISSUE TITLE
Can't Disable Low Balance Response - "you do not have enough credit"

### ISSUE THREAD

**Issue by slango-im** [iNextrix/ASTPP#279]
In the global and calling card settings, we have disabled the "Balance Announcement" setting.

But when our customer makes a call with no balance, they still receive this message.

We want to simply reject the call and not play this message for them. How can it be disabled?

**Comment by smrdoshi** [comment]
That option will only disable balance playback but not error / alert / notifications playback. 

If you want to disable all the audio notifications then you can disable it from Settings -> Global -> Playback Audio Notification * to disable.

**Comment by slango-im** [comment]
Thank you @smrdoshi . I did that but it still seems to playback. 

Perhaps I should update date this setting in the database?

**Comment by smrdoshi** [comment]
Is your customer connecting using calling card access number or by registering extension?

**Comment by slango-im** [comment]
@smrdoshi, this is customer accessing our switch via IP. He buys routes from us on wholesale.

**Comment by devangn** [comment]
Please get the patch or update the source and verify, the issue is resolved.
