### ISSUE TITLE
Post Dial Delay goes to Error 487 instead of 500

### ISSUE THREAD

**Issue by slango-im** [iNextrix/ASTPP#291]
How can we change our routing setting so that when PDD (post dial delay) is over 2 seconds, ASTPP can send error 500?

Right now, it can go 7 seconds and the user will simply hang up.

On a large scale, the slow routing causes us to to lose money.

**Comment by slango-im** [comment]
Is this something that can be changed in the dialplan, perhaps?

**Comment by slango-im** [comment]
How can we get rid of this PDD (log below) ...?


![image](https://user-images.githubusercontent.com/25807874/34419737-69455fda-ebba-11e7-8c83-0f2b8c036d43.png)

**Comment by smrdoshi** [comment]
Is that PDD from gateway end?

**Comment by slango-im** [comment]
It seems yes.

**Comment by smrdoshi** [comment]
Is it sorted out?
