### ISSUE TITLE
Late Translation In Search Of Did

### ISSUE THREAD

**Issue by eduardofoliveira** [iNextrix/ASTPP#297]
Destination number is translated only after searching for did, this way it did not find the correct did in search since there is still the prefix

![latetranslation](https://user-images.githubusercontent.com/20446658/34419182-94a9a7f6-ebe9-11e7-83a5-69b1f08ab0df.png)

Is it possible to do search by did after the translation?

**Comment by smrdoshi** [comment]
If you want to apply translation on DID then you must configure DID global translation from settings module. That will translate number before looking into DID table.

**Comment by eduardofoliveira** [comment]
Thank you, this solution solved the problems with incoming calls.
