### ISSUE TITLE
Search by prefix returns wrong client

### ISSUE THREAD

**Issue by eduardofoliveira** [iNextrix/ASTPP#298]
The customer search returned wrong due to the search for the largest prefix.

![prefix 1 errado](https://user-images.githubusercontent.com/20446658/34419571-c3c3a8f0-ebeb-11e7-9256-268c82732567.png)

When I changed the query to return two results the correct client is in the second position.

![prefix 2 errado](https://user-images.githubusercontent.com/20446658/34419603-e783c41e-ebeb-11e7-895f-26f2a288aa21.png)

Is it possible to change the search by the first few characters of the destination number to actually use the number prefix?

The query was taken from the freeswitch log.

**Comment by devangn** [comment]
Please get the patch or update the source and verify, the issue is resolved.
