### ISSUE TITLE
Opensips and creation account 

### ISSUE THREAD

**Issue by Levadiani** [iNextrix/ASTPP#3]
Hello. Have a problem: when I switch off opensips function, and create new customer I have a error: 
`A PHP Error was encountered

Severity: Notice

Message: Undefined variable: account

Filename: libraries/accounts_form.php

Line Number: 81`
and then when finish creation new customer, account id was blank. When I switch on opensips, all work fine. The same problem in demo on the your website.
![2016-08-02](https://cloud.githubusercontent.com/assets/20800615/17340733/8e186cae-5902-11e6-95db-e2bda1434547.png)
![2016-08-02 1](https://cloud.githubusercontent.com/assets/20800615/17340736/91e2a12e-5902-11e6-8256-3153c5ab0715.png)

**Comment by smrdoshi** [comment]
It has been resolved now in pull request #4 .
