### ISSUE TITLE
db error on edit invoice

### ISSUE THREAD

**Issue by eightsixeight** [iNextrix/ASTPP#302]
edit invoice , change nothing, submit.

A Database Error Occurred
Error Number: 1054

Unknown column 'item_type' in 'where clause'

SELECT currency FROM (`currency`) WHERE `item_type` = 'TAX' AND `id` IS NULL AND `id` = '139'

Filename: /var/www/html/astpp/models/db_model.php

Line Number: 79

**Comment by smrdoshi** [comment]
It has been resolved in v3.6.
