### ISSUE TITLE
CPU Usage high at 200 concurrent call limit

### ISSUE THREAD

**Issue by slango-im** [iNextrix/ASTPP#303]
At 200 calls, I see our ASTPP is getting laggy. We we're a server with 8 cores and 64 GB of memory. 

Here is our "top" reading from putty. Am I reading this correctly?

What can we do to resolve this?

![image](https://user-images.githubusercontent.com/25807874/34497301-e524f214-efb1-11e7-85d3-c4d8e9381f76.png)

**Comment by devangn** [comment]
@slango-im Are you concerned about load average numbers?
Check the decent content here, http://blog.scoutapp.com/articles/2009/07/31/understanding-load-averages by @andre

**Comment by slango-im** [comment]
Thank you, it's clear.

But in general, is ASTPP having load/lag issues once there are 200 concurrent calls? I'm reading in Github and it seems a few others have had a similar issue.

Are there any optimizations for this?

**Comment by devangn** [comment]
You may try something from here,
http://astpp.readthedocs.io/en/v3.5/Improving_performance/improving_performance.html
http://astpp.readthedocs.io/en/v3.5/FAQ/faq.html

You may use and go through our google group for this kind of query as well,
https://groups.google.com/d/forum/astpp
