### ISSUE TITLE
Invoice Generation

### ISSUE THREAD

**Issue by shadikur** [iNextrix/ASTPP#311]
Dear Samir/ ASTPP Support Team,

I have updated my script with latest git. Invoices are rounding all the subscription charges correctly. But, It has been added Packages Call charges though, I have setup 400 Minutes should be free of charge. So, I can see on my invoice that charges has been added to invoice for few calls where it should be Zero (0) charges.

I look forward to hearing from you. Thanks for your cooperation.

Kind Regards,
Shadikur

**Comment by smrdoshi** [comment]
Fixed.
