### ISSUE TITLE
Reports by "Code"

### ISSUE THREAD

**Issue by slango-im** [iNextrix/ASTPP#316]
Would it be able to generate CDR reports by codes? Then we could see how many minutes by code.

For example:

1949  --- 242:12 min
1508  --- 211:44 min
1508  --- 533:01 min

Not to see each call, but a breakdown by code. Surely this must be possible, yes?

**Comment by devangn** [comment]
Check Call Reports > Summary Reports

**Comment by slango-im** [comment]
Yes, but this is not enough.

I mean, I'd like to the summary total of each code. Like, have code a +44, total minutes stat. Right now, I see each individual call of +44. How can we see this?

**Comment by smrdoshi** [comment]
Select group by code in summary report and you will get the result which
you are expecting.



<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance on the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by slango-im** [comment]
I see now. Thank you very much.
