### ISSUE TITLE
Setup Signaling Details so customer can choose different Rate Group?

### ISSUE THREAD

**Issue by slango-im** [iNextrix/ASTPP#322]
I have a use case that I can't figure out it ASTPP.

I have 2 Rate Groups, and I would like our customer to choose which Rate Group he wants to dial into based on a prefix or IP or something. For example:

We have Rate Group X and Rate Group Y. 

Is there a way we can setup different signaling details so one customer account can choose between rate groups?

**Comment by eduardofoliveira** [comment]
You can create different prefixes within the same rate group.

For example:

55113588 ... - without a prefix
4654 55113588 ... - with prefix

where the origination rate 5511 ... matches only the termination rate of Trunk A
Where 4654 ... matches only the termination rate of Trunk B

And in the Rate Group you should add Trunks A and B

This way 5511 ... will have a price and 4654 ... will have another price per minute

**Comment by slango-im** [comment]
Thank you, @eduardofoliveira.

Can you please clarify though. I though the prefix on our Trunks were the prefixes required by our termination partners? 

Can you please point out where the prefix should be added?

**Comment by eduardofoliveira** [comment]
In the Edit Termination Rate you can remove the prefix used for internal control and add the prefix of your termination.

In this example the prefix 10 that is before 55 ... is used when my client sends the call to my gateway. To remove it, simply fill in the "Strip" field with the value of the prefix.

This prefix is removed and if I need to add another one to send to my termination in the "Prepend"

![termination](https://user-images.githubusercontent.com/20446658/35363869-6e02c5a4-0153-11e8-82a8-aea22b6fc921.png)
