### ISSUE TITLE
OPUS codec supported?

### ISSUE THREAD

**Issue by slango-im** [iNextrix/ASTPP#324]
We are trying to send calls to ASTPP with the opus codec but it's telling us that the calls are rejected.

Does ASTPP support opus? 

You can write 

We are getting Reason: Q.850; cause=88; text= "INCOMPATIBLE_DESTINATION" Error

**Comment by ketan-kothari** [comment]
@slango-im 
Yes ASTPP support opus codec.

You need to configure opus codec in sip-profile as well as load that module in freeswitch.
