### ISSUE TITLE
opensips config is outdated

### ISSUE THREAD

**Issue by basitengr** [iNextrix/ASTPP#326]
Hi team, 
I am trying to setup **opensips v2.3** along with **ASTPP 3.5** by following 
http://astpp.readthedocs.io/en/v3.5/Integrations/opensips.html

The **opensips v1.7** default configuration is currently present on git.
Has someone done this before for some newer version of opensips like 2.1 or 2.2?
If this integration is currently not active then why its available there?

**Comment by powerpbx** [comment]
I have a config file that is working more or less with v2.4 of opensips after some modifications.  However, I ran into other problems that go well beyond just the config file. It appears to be looking for some non-existent tables in the opensips DB.  There is no mention of that in the install guide so not sure what is going on there.  I haven't decided if I want to spend more time working on this or doing it some other way independent of ASTPP.  It seems there aren't a lot of eyes on this feature so it's not being worked on and tested.  

Another problem is that it's not set up for multiple OpenSips servers and I think it probably should be.

**Comment by devangn** [comment]
You may review #431 PR by @powerpbx
