### ISSUE TITLE
when try to export big rate list I receive 504 Gateway Time-out

### ISSUE THREAD

**Issue by velislaviliev** [iNextrix/ASTPP#329]
Hello, I have astppbilling v.3.5 and when I try to export big rate list I receive "504 Gateway Time-out" error.
If I do more specific serach and result is few lines, export is OK.

**Comment by devangn** [comment]
Upload_max_filesize
Max_input_time 
Memory_limit
Max_execution_time 
Post_max_size

These params of php.ini affects upload/download file size. Set them accordingly.
