### ISSUE TITLE
Quick Install script is full of bugs, and does not install

### ISSUE THREAD

**Issue by tcreek** [iNextrix/ASTPP#330]
I have tried the script on both CentOS 7, and Debian 8 on minimal installs. On both it failures miserable.  There are no guidelines on what the starting system should have on it.  Was any testing done with that script?

This is what I am seeing on Debian 8

cp: cannot stat ‘/usr/src/latest/misc/odbc/deb_odbc.ini’: No such file or directory
cp: cannot stat ‘/usr/src/latest/misc/odbc/deb_odbcinst.ini’: No such file or directory
Make sure Short Open Tag is switched On
sed: can't read /etc/php5/fpm/php.ini: No such file or directory
sed: can't read /etc/php5/fpm/php.ini: No such file or directory
sed: can't read /etc/php5/fpm/php.ini: No such file or directory
sed: can't read /etc/php5/fpm/php.ini: No such file or directory
sed: can't read /etc/php5/fpm/php.ini: No such file or directory
sed: can't read /etc/php5/fpm/php.ini: No such file or directory
Failed to restart php5-fpm.service: Unit php5-fpm.service failed to load: No such file or directory.
Failed to restart nginx.service: Unit nginx.service failed to load: No such file or directory.
/bin/cp: cannot stat ‘/usr/src/latest/freeswitch/conf/autoload_configs/*’: No such file or directory
sed: can't read /var/lib/astpp/astpp-config.conf: No such file or directory
sed: can't read /var/lib/astpp/astpp.lua: No such file or directory
sed: can't read /var/lib/astpp//astpp-config.conf: No such file or directory
./install.sh: line 334: chkconfig: command not found
./install.sh: line 335: chkconfig: command not found
./install.sh: line 336: chkconfig: command not found
./install.sh: line 337: chkconfig: command not found
Failed to restart mysql.service: Unit mysql.service failed to load: No such file or directory.
Failed to restart nginx.service: Unit nginx.service failed to load: No such file or directory.
Failed to restart freeswitch.service: Unit freeswitch.service failed to load: No such file or directory.
(In this case, FreeSwitch was not even selected to install)

In the end, there is not even anything listening on port 8089;

**Comment by tcreek** [comment]
Addendum:

For the CentOS attempt, the script just keeps restarting over, and over.

Was this even tested?

**Comment by smrdoshi** [comment]
Aww Problem!! Doesn't looks like well. 

If you can fix and contribute to project then that will be great. 
Will appreciate that.

**Comment by tcreek** [comment]
I am sorry, but I am already too busy to mess with this. 

I guess I have to move on to another billing system to evaluate

**Comment by liveincan** [comment]
I have some suggestions:
- Use Debian 8 Standard. (not minimum)
- apt-get update && apt-get upgrade
- apt-get install systemd
- apt-get install systemd-sysv
- reboot & try script
Hope this helps.

**Comment by tcreek** [comment]
Thank you for that advice. After installing a regular Debian install, I tried what you suggested. The items you wanted me to install were already installed.

This time there was no errors however, according to netstat, there is nothing listening on port 8089. Which means the script is still bugged.

**Comment by devangn** [comment]
@tcreek Was there any web server already running before you installed ASTPP through script?

**Comment by tcreek** [comment]
No, but is seems the script now functions after seeing some advice about installing a Desktop with Debian.

**Comment by alexmed** [comment]
have exactly the same problem (Quick install scripts for ASTPP 3.6 and 3.5) , multiple times tried on AWS with clean images of Centos7 Debian8 and on other VPS providers - no luck, console shows lot of errors executing commands like "git, chkconfig..."... etc, install finishes very fast with "Success" message. 

Have no way (and acutally no reason) of installing Debian with Desktop on VPS to have server app run but looks like its the only way?

**Comment by tcreek** [comment]
It is odd they do not include notes like this in the docs (requirements for the script). After many tried on virtual machines, ASTPP will not successfully install on Debian 8 without those three  items selected to install. So technically the script is still broken so I am not sure why this was closed out.

You can install it to a VPS if, and only if, you have access to the console. However, there is another option. Digital Ocean now supports custom VPS images. You can do the install locally on VirtualBox, for example, then upload that image to Digital Ocean for use.

**Comment by alexmed** [comment]
i beg a pardon, probably i did smth wrong before, on my recent try the quick-install script worked flawlessly. here are the steps in case this may help someone:

- aws lightsail, OS only, debian 8.7
- attached static IP
- this https://astpp.readthedocs.io/en/v3.6/Installation/quick_installation.html
each quick install command prefixed with sudo (not sure if is important, probably)
- keep in mind to add ASTPP additional ports to Instance:Networking/Firewall

cheers!
