### ISSUE TITLE
Package not working with INBOUND calls 

### ISSUE THREAD

**Issue by ChaudharyG** [iNextrix/ASTPP#331]
Team, 

We would like to implement combined package for Inbound and Outbound  but PACKAGE option is working only in Outbound calls and we have already enabled package for both IN/OUT 
1. Inbound secs not deducting from Package.
2. Inbound account goes to (-)ve and calls are still connecting.
3. Can we implement the concept of Expiry date of package ?

**Comment by smrdoshi** [comment]
1.  Fixed. 
2. We do not have limit for receiving calls. 
3. Contact to sales@inextrix.com.
