### ISSUE TITLE
Termination Rates Showing $0.00

### ISSUE THREAD

**Issue by slango-im** [iNextrix/ASTPP#332]
It seems there is a major issue.

After importing in bulk new termination rates (several times), the rate still shows up as 0.00. 

Please see below:
![image](https://user-images.githubusercontent.com/25807874/36650461-b5dde32a-1ab4-11e8-9b04-9cd817c347f5.png)

**Comment by smrdoshi** [comment]
We confirmed with 3.6 and its working fine. 
Please update version and confirm.
