### ISSUE TITLE
Custom website Header and Footer not appearing on customer login

### ISSUE THREAD

**Issue by liveincan** [iNextrix/ASTPP#336]
Performed two clean installs of quick installation script on Debian 8 with the same result. Both Website Header and Website Footer are not appearing on customer website. Website Domain in Company Personalization is the same as baseurl in /var/lib/astpp/astpp-config.conf. This issue seems to have appeared recently after a update. Thanks.

**Comment by smrdoshi** [comment]
I just tested feature and it seems to be working fine. 
Sharing the configuration which I did. 

![admin_company_profile](https://user-images.githubusercontent.com/958577/36787870-b7df31d4-1cb1-11e8-9b8d-4d1bb8ecb94e.png)
![admin_login_page](https://user-images.githubusercontent.com/958577/36787873-bba397a6-1cb1-11e8-9c6a-187ab0a8298e.png)

Hope this will sort out the issue. 
​

**Comment by liveincan** [comment]
I have done exactly as suggested on the forum. Tried using domain both with
and without port number (:8089) but no success. Here is my configuration:

[image: Inline image 3]

[image: Inline image 2]


[image: Inline image 1]
[image: Inline image 4]

**Comment by smrdoshi** [comment]
Not images are attached. Please send it.

**Comment by liveincan** [comment]
![image](https://user-images.githubusercontent.com/12475692/36852882-efe2e718-1d3a-11e8-9c93-3b052d80e935.png)
![image](https://user-images.githubusercontent.com/12475692/36852906-030bc7ba-1d3b-11e8-9c27-2b770d270cc6.png)
![image](https://user-images.githubusercontent.com/12475692/36852922-0c2cc9f2-1d3b-11e8-84d8-70a9b4dfb31e.png)
![image](https://user-images.githubusercontent.com/12475692/36852966-18d78610-1d3b-11e8-9140-7324fac7bfd5.png)

**Comment by smrdoshi** [comment]
Can you put http://?



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance on the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by liveincan** [comment]
Website Domain: http://astpp.soft-sol.net:8089
Not Working

**Comment by smrdoshi** [comment]
Just tried same thing. In Website Domain configured admin.astppbilling.com:8081 and its working fine. Send me your server information off the list on samir.doshi@inextrix.com.

**Comment by smrdoshi** [comment]
No further information. Closing the issue.
