### ISSUE TITLE
 DID monthly charge going off as 0.00

### ISSUE THREAD

**Issue by plettonline** [iNextrix/ASTPP#338]
Steps to re-create.

1. Setup Reseller account
2. Log in to Reseller account
3. Purchase DID and then assign monthly cost to DID
4. As the reseller, setup a customer as prepaid with billing date on 1st of the month
5. Assign a monthly cost to DID
6. At the beginning of the month, the monthly cost for the DID will be processed but as 0.00
7. The invoice for the client is also generated with a 0.00 value and the due date of 1970-01-01

I have not yet tested this as a "non reseller" account, however, the issue is defiantly consistent on reseller accounts.

**Comment by plettonline** [comment]
Should this be solved in 3.6 ?

**Comment by smrdoshi** [comment]
Yeah. Please confirm.

**Comment by plettonline** [comment]
Hi guys,

Seems like this issue still persists exactly as before... The Monthly DID charge went off this month however the amount went off as "0" instead of "80" as it should have. The price of the DID has been set at a monthly price of "80" yet the system still charges "0"

**Comment by plettonline** [comment]
1. Direct customer DID charges seem to be going off as expected. 

2. Reseller DID charges and the Customers of the Resellers are not being charged.. (Value shows "0" and invoice due date shows 1970-01-01)

3. Monthly Charge for DID is configured as 80.00 on the reseller's panel ... 

Screen shots below or recent occurrence taken from within resellers panel
  
![screen shot 2018-05-11 at 19 07 03](https://user-images.githubusercontent.com/17046363/39937135-14db3ac4-554f-11e8-97ca-80b094472ab5.png)
![screen shot 2018-05-11 at 19 08 44](https://user-images.githubusercontent.com/17046363/39937136-150c664e-554f-11e8-8de5-25fc636811e1.png)

**Comment by plettonline** [comment]
Hi Samir,

Details have been emailed.. 
Thank you
