### ISSUE TITLE
Inbound to header 

### ISSUE THREAD

**Issue by eightsixeight** [iNextrix/ASTPP#339]
When inbound call comes in , we get 
<action application="bridge" data="[leg_timeout=0]user/<SIPGWNUMBER>@${domain_name}"/>

and no to-header, therefore we can't filter on DID on the other side i get a to of 
<SIPGWNUMBER>@${domain_name}"/>

is there a place i can pad effective_destination_number to a to-header or request-line ?

**Comment by eightsixeight** [comment]
meaning i need to use LOCALY reg'ed user but send the did

user/crappyname/did

**Comment by devangn** [comment]
@eightsixeight Frank, please elaborate the concern, I don't find details enough to understand your request.
