### ISSUE TITLE
Ringback Not Supported in Passthrough (g.729)

### ISSUE THREAD

**Issue by slango-im** [iNextrix/ASTPP#345]
Hello,

We are using g.279 and we have the instant ringback enabled. But it does't go through.

How can we have instant ringback with g.729?

Please see below:

2018-03-16 16:34:58.537197 [WARNING] switch_ivr_originate.c:1252 sofia/default/ - Ringback not supported in passthrough codec mode

**Comment by FozzyGo4** [comment]
Ringback is media and requires transcoding. You need the commercial G.729 licence from FreeSWITCH installed.

**Comment by N1ck3l** [comment]
Even if the codec G729 is now a patent-free codec, according to [this ](https://en.wikipedia.org/wiki/G.729) link and more detailed [here](https://en.wikipedia.org/wiki/G.729#Licensing) ?

IMO it's a commercial decision to maintain those codecs and charging for its usage. I understand that freeswitch  needs to make money or invested money to have those codecs while the licensing was mandatory. I wonder what will happen now that the codec is royalty-free.

**Comment by devangn** [comment]
@N1ck3l Freeswitch guys are keep suggesting to use licensed version only and till now transcoding needs license.
