### ISSUE TITLE
IP MAP with sip_profile binding

### ISSUE THREAD

**Issue by legionnet** [iNextrix/ASTPP#347]
You can binding sip_profile to IP MAP

update DB:
`ALTER TABLE `ip_map` ADD `sip_profile_id` INT(4) NOT NULL DEFAULT '0' AFTER `id`;`

change astpp.dialplan.lua in line 117 to
`
    variable_sofia_profile_name = ""
    variable_sofia_profile_name = params:getHeader('variable_sofia_profile_name')

    authinfo = doauthentication(destination_number,from_ip,variable_sofia_profile_name)
`

update astpp.functions.lua in functions
doauthentication:
-- Do Authentication
function doauthentication (destination_number,from_ip, sofia_profile_name)
    return ipauthentication (destination_number,from_ip, sofia_profile_name)
end

ipauthentication:
function ipauthentication(destination_number,from_ip, sofia_profile_name)
     local query = "SELECT "..TBL_IP_MAP..".*, (SELECT number FROM "..TBL_USERS.." where id="..TBL_IP_MAP..".accountid AND status=0 AND deleted=0) AS account_code FROM "..TBL_IP_MAP..", "..TBL_SIP_PROFIL
ES.." WHERE "..TBL_IP_MAP..".sip_profile_id="..TBL_SIP_PROFILES..".id AND "..TBL_SIP_PROFILES..".name='"..sofia_profile_name.."' AND INET_ATON(\"" ..from_ip.. "\") BETWEEN(INET_ATON(SUBSTRING_INDEX(`ip`
, '/', 1)) & 0xffffffff ^((0x1 <<(32 -  SUBSTRING_INDEX(`ip`, '/', -1))) -1 )) AND(INET_ATON(SUBSTRING_INDEX(`ip`, '/', 1)) |((0x100000000 >> SUBSTRING_INDEX(`ip`,'/', -1)) -1))  AND \"" .. destination_
number .. "\"  LIKE CONCAT(prefix,'%') ORDER BY LENGTH(prefix) DESC LIMIT 1"

add to constant.lua:
`TBL_SIP_PROFILES = "sip_profiles"`

And do web interface changes

**Comment by legionnet** [comment]
I think sip registration is needed to binding sip_profiles too

**Comment by smrdoshi** [comment]
Hi @legionnet 

What will be the use case to bind sip profile with ip map?

**Comment by legionnet** [comment]
It`s more secure. Bind ip auth to sip profile (ip+port). 
May use 1 client IP for different rate groups.
First rate group for first sip profile and second rate group for second sip profile.

**Comment by legionnet** [comment]
And update please  freeswitch/fs/lib/astpp.xml.php on line 183
change $query to
$query = "SELECT username,dir_params,dir_vars,number as accountcode,sip_devices.accountid FROM sip_devices,accounts,sip_profiles WHERE sip_profiles.id=sip_devices.sip_profile_id AND sip_devices.
status=0 AND accounts.status=0 AND accounts.deleted=0 AND accounts.id=sip_devices.accountid AND username='" . $_REQUEST ['user'] . "' AND sip_profiles.name='" . $_REQUEST ['sip_profile'] . "' limit 1";

**Comment by smrdoshi** [comment]
We are still unsure about this improvements. Changing milestone to 4.0.

**Comment by smrdoshi** [comment]
This will not useful as rate group is linked to main account.
