### ISSUE TITLE
freeswitch_form.php

### ISSUE THREAD

**Issue by legionnet** [iNextrix/ASTPP#348]
Please change:
'name' => 'from_domain',
'name' => 'from_user',

to 
'name' => 'from-domain',
'name' => 'from-user',

**Comment by smrdoshi** [comment]
Thanks. We already resolved that in v3.6-dev branch. We are finalizing v3.6
source code for release. Some testing and changes are going on.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance on the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.
