### ISSUE TITLE
Change Default Language

### ISSUE THREAD

**Issue by leandrowcampos** [iNextrix/ASTPP#353]
For change the default language, I change in file: astpp/application/libraries/locale.php
the line:
  function set_lang($lang = FALSE) {
                $current_locale = $this->CI->session->userdata ( 'user_language' );
                if (empty ( $current_locale )) {
                        $current_locale = 'en_US';

to

  function set_lang($lang = FALSE) {
                $current_locale = $this->CI->session->userdata ( 'user_language' );
                if (empty ( $current_locale )) {
                        $current_locale = 'pt_BR';

This works fine. But when I use the footer flags to change language to English, the language don't change to english. Change to French and Spanish, but to english no.

I thinks is something with url: 
/application/modules/user/language/' . $lang . '/LC_MESSAGES/messages.mo

In thie folder /application/modules/user/language/ don't have folder en_US.

**Comment by smrdoshi** [comment]
We are going to release this feature by default in v3.6. 

You can check  commits : 
https://github.com/iNextrix/ASTPP/commit/6055c852e4363fffde42c139cc15eaa2679738c7
https://github.com/iNextrix/ASTPP/commit/3a078d0cd040b05c358a8f376b992dde01e1b6a1
