### ISSUE TITLE
DID TollFree Billing with Source Prefix (Mobile/Landline)

### ISSUE THREAD

**Issue by leandrowcampos** [iNextrix/ASTPP#354]
I think in some countries, the billing for DID has diferrents rates between mobile lines and landlines.

Today, the ASTPP allow only a unique billing.

I think all providers want billing based on source number.

Examples:

55329 -> This Prefix is from Brazil, city of Juiz de Fora and the 9 indicate is mobile line.
5532 -> This prefix is from Brazil, city of Juiz de Fora and is fixed line.

If I receive a call from 55329xxxxxxxx will billing US$1.00/minute
If I receive a call from 5532XXXXXXXX will billing US$0,50/minute

Is can possible add this feature?

**Comment by smrdoshi** [comment]
Yes, we are planning to add that in V4.0. That will be named Inbound Rates and it will be associated with DIDs.

**Comment by leandronvoip** [comment]
Thanks Samir. When v4.0 release, I will donate some amount to project. This feature will save a lot for me.

**Comment by smrdoshi** [comment]
We are behind the schedule but targetting to release it before this year end.

**Comment by Hemdip** [comment]
@leandrowcampos We will implement addon in Next V-5.0 version
