### ISSUE TITLE
Doubt about CallerID Translation 

### ISSUE THREAD

**Issue by eduardofoliveira** [iNextrix/ASTPP#363]
I am using the following rule to do the translation of CallerID:

![4](https://user-images.githubusercontent.com/20446658/38279390-7104424c-3776-11e8-9376-71200196d5a5.png)

To translate this call:

![1](https://user-images.githubusercontent.com/20446658/38279302-00b28b0c-3776-11e8-9e16-555d11fb93e9.png)

But the output is not replacing the previous CallerID, but adding:

![2](https://user-images.githubusercontent.com/20446658/38279278-f1bca2cc-3775-11e8-8e85-49b60710d243.png)

I am wanting this result:

![3](https://user-images.githubusercontent.com/20446658/38279340-3ca0ec1c-3776-11e8-8453-48f8f6ec5dfd.png)

What should be the rule for substituting everything independent of CallerID received?

**Comment by smrdoshi** [comment]
Caller id translation will either replace the prefix or append a new one. It is not designed to replace entire number like which you are looking for.

It looks like you want to override the caller id for all calls. If so then you can use force caller id feature.

**Comment by eduardofoliveira** [comment]
How can I use the force caller id on calls arriving through IP MAP(ACL) ?

**Comment by devangn** [comment]
@eduardofoliveira which ever account you bind with added ip in IP MAP, change force caller id name and number of it as per your usage and you will get that name and number to UAS side

**Comment by eduardofoliveira** [comment]
@devangn Where can I change to make this CallerID change?
