### ISSUE TITLE
install script wrong for CentOS and Apache

### ISSUE THREAD

**Issue by powerpbx** [iNextrix/ASTPP#368]
In the install script you have `systemctl stop apache2` and `systemctl disable apache2` globally.  However, that only works for Debian. 

For CentOS it is `systemctl stop httpd` and `systemctl disable httpd`.

**Comment by ketan-kothari** [comment]
@powerpbx 

`systemctl stop apache2` and `systemctl disable apache2` are working for CentOS 7 also.
So verify it on CentOS 7.
