### ISSUE TITLE
DID - Orgination Rates not found.

### ISSUE THREAD

**Issue by countrdd** [iNextrix/ASTPP#374]
I understand that In order to use a DID. You have to set up the DID in the Origination Rates Table.

I think the following changes would vastly improve the issues with Origination rates not found when dealing with DIDs.

1. When a DID is assigned to a customer, make sure the system automatically creates the DID code in the origination rates table with the rate group of the customer that owns the DID.

2. If you change the rate group on the customer account, automatically update the Origination Rates of all the customers DID to the new rate group.

3. On the DID's section of a customer account - If the DID is not in the Origination Rates table at all or if there is not a record in the Origination Rates Table with the did AND the rate group of the customer - Show an Error Message on this screen, and maybe an auto fix button that will generate the rate.

4. Optimized Call Routing - Also since ASTPP knows where the DID lives. It would be nice if you select force trunk option, the system would present a list of all the rate groups and allow you to select the rate groups you want an record inserted into with the force trunk. This would then make it so the system would not utilize a provider trunk to call out, but would keep the call on-net and there by reducing any costs that would be incurred by dialing out to the pstn and back in.

**Comment by kristapsdravnieks** [comment]
in file /var/lib/astpp/astpp.lua add line INB_FREE="TRUE" and you will not need Origination rates for DID calls.  Unless you bill for inbound calls

**Comment by countrdd** [comment]
Thanks. But we bill for certain inbound calls….I.E. 800 inbound

**Comment by devangn** [comment]
@countrdd 
for 1,2,3
There may be chance that admin doesn't use rate as whole DID number as rate code instead they are having prefix same as outbound call and prefix length could be anything from 1 digit to whole DID number length
So as an open soure we need to provide the liberty to admin for different kind of usage scenarios.
The same thing applicable to 4
If you configure DID with correct call type and set correct destination then there is no chance of using other flow of other provider.
