### ISSUE TITLE
SIP device edit shows wrong account assignment when account is provider

### ISSUE THREAD

**Issue by powerpbx** [iNextrix/ASTPP#390]
This is in v3.5 and v3.6 branches. 

 In GUI > Switch > SIP Devices,  SIP device list indicates correct account assignments regardless of whether the account type is provider or customer.

Select Edit action for a SIP device assigned to a provider account, **Account shows the wrong account assignment.**

If you save that it will now be assigned to the wrong account.  The reason appears to be because the drop down menu only shows customer accounts not provider accounts.

**Comment by powerpbx** [comment]
If you comment out this line it corrects the problem.  Need to add a filter to not include accounts that are not Customer or Provider.

https://github.com/iNextrix/ASTPP/blob/v3.6/web_interface/astpp/application/modules/freeswitch/libraries/freeswitch_form.php#L2793

**Comment by smrdoshi** [comment]
Issue has been resolved.
