### ISSUE TITLE
Deleting accounts in GUI does not delete them in the database

### ISSUE THREAD

**Issue by powerpbx** [iNextrix/ASTPP#391]
To reproduce on v3.5 or v3.6

Create an account via GUI.  Verify it is in `accounts` table in DB.

Delete account in GUI.  The account is still in the DB.

**Comment by smrdoshi** [comment]
We do not do hard delete for accounts. When you delete the account, we simply change the field value from 0 to 1 in database and keep it in database.

**Comment by powerpbx** [comment]
What is the reasoning behind this.

I am finding that this creates problems.  For example, if I have an IP setting for an account I delete.. 
 Not only does the account remain in the DB but it appears other related settings remain.  Those settings then interfere with adding new settings.

For example, if there are SIP devices and IP settings associated with a deleted account.  They also remain in the DB and become orphaned.  When I try add a new SIP device or IP with the same number it fails validation because it already exists in the DB.  This doesn't seem to be a very good situation.
