### ISSUE TITLE
SIP Devices Not Loading

### ISSUE THREAD

**Issue by slango-im** [iNextrix/ASTPP#395]
Hello!

Under the customer profile, when clicking "SIP Devices", it just hangs and keeps loading. There is no way to see the list of SIP devices. 

It's happened on 3 different installations now. How can it be fixed?

![image](https://user-images.githubusercontent.com/25807874/38617214-a851bf88-3d96-11e8-8246-0229b029ae14.png)

**Comment by powerpbx** [comment]
What version are you running?

**Comment by slango-im** [comment]
I'm running 3.5.

And this is what I'm getting under "SIP Devices" in the main menu....

![image](https://user-images.githubusercontent.com/25807874/38618855-0d1fbce0-3d9b-11e8-8669-39a11c8f0d26.png)

**Comment by smrdoshi** [comment]
Change environment variable from development to production. That will resolve your issue.

**Comment by slango-im** [comment]
Thank you, it's fixed.
