### ISSUE TITLE
pagination not working

### ISSUE THREAD

**Issue by powerpbx** [iNextrix/ASTPP#397]
On v3.6

If you go to Switch > SIP Profiles > and select default profile it show all 48 records even though pagination defaults to 10 records.  Clicking from page 1 of 5 to 5 of 5 does not change anything.

**Comment by smrdoshi** [comment]
That's not a bug. 

We disabled paging for sip profile as sip profile have a lot of variables and when you work on that, you want to see all variables value at the same time to make the correct decision and to avoid any impact on calls.
