### ISSUE TITLE
recordings in customer cand be set to no

### ISSUE THREAD

**Issue by isrlgb** [iNextrix/ASTPP#40]
i created a new customer and set recording to no and goes back to yes

besides that i think the default should be no

**Comment by dev-astpp** [comment]
Fixed. Please take latest source and test it out.

**Comment by rayedbs** [comment]
please can you make it to NO by default!

**Comment by smrdoshi** [comment]
You must need to do that from code.


Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com



*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance of the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.
