### ISSUE TITLE
Make External Call with ASTPP integrated  Freeswitch

### ISSUE THREAD

**Issue by waichiu8520** [iNextrix/ASTPP#405]
I installed the ASTPP v3.6 and freeswitch together. I have a another sip server which connects the PSTN gateway. 

Previously, I can set in default.xml in conf folder. 
           <extension name="demo">
              <condition field="destination_number" expression="^(.*)$">
	             <action application="bridge" data="sofia/external/sip:$1@<another sip server:port>"/>
              </condition>
               </extension>
Above is work.

After installation of ASTPP, the default.xml disappear, just have astpp.xml which includes empty content. 

Does ASTPP web can make the external call ?

**Comment by waichiu8520** [comment]
default.xml
<extension name="demo">
<condition field="destination_number" expression="^(.*)$">
<action application="bridge" data="sofia/external/sip:$1@<another sip server:port>"/>
</condition>
 </extension>

**Comment by waichiu8520** [comment]
defalut.xml

extension name="demo"
              condition field="destination_number" expression="^(.*)$"
	             action application="bridge" data="sofia/external/sip:$1@<another sip server:port>"
              condition
              extension

**Comment by smrdoshi** [comment]
It will not considered any other .xml files. It will generate its own .xml in realtime and process the calls.
