### ISSUE TITLE
I need SipCallId

### ISSUE THREAD

**Issue by eduardofoliveira** [iNextrix/ASTPP#408]
Good afternoon,

Is it possible to make any changes to save the SipCallID of calls in the cdrs table of the ASTPP database?

**Comment by MrSupaMike** [comment]
Hi,
I noticed that since I upgraded v3.5 to v3.6 callerID number was missing from the CDR records. Only callerID name was saved. 
I don't know if this is the same issue you're referring to, but I made a quick fix for it:

https://github.com/iNextrix/ASTPP/pull/410

**Comment by eduardofoliveira** [comment]
Good evening,

Actually need this information to relate the log of another PBX that is behind the ASTPP.

**Comment by smrdoshi** [comment]
You can send custom variable from your PBX to ASTPP and then capture it in CDR process. That should do your job.

**Comment by eduardofoliveira** [comment]
Hello Samir,

This would help me a lot, how can I make this setup?

Or where can I find a tutorial or material to study on this subject?

**Comment by eduardofoliveira** [comment]
Hi,

I was able to solve the problem using the esl interface.

Once the call is terminated with the HANGUP_COMPLETE event I get the variable_sip_call_id and Unique-ID fields and in this way I can relate the Astpp records to my PBX.

Regards,

Eduardo.
