### ISSUE TITLE
[ERR] switch_xml.c:1695 Error[[error near line 70]: unexpected closing tag </head>]

### ISSUE THREAD

**Issue by Jasonong1025** [iNextrix/ASTPP#412]
After install Astpp with freeswitch using debian 8 freeswitch has return error once start up the statement below is the error return. I have check this file which don't think having this error at line 70.
 
[ERR] switch_xml.c:1695 Error[[error near line 70]: unexpected closing tag </head>]

This is that part of code at line 70 in switch_xml.c
typedef struct {
        size_t gl_pathc;                        /* Count of total paths so far. */
        size_t gl_matchc;                       /* Count of paths matching pattern. */
        size_t gl_offs;                         /* Reserved at beginning of gl_pathv. */              <<<< line 70
        int gl_flags;                           /* Copy of flags parameter to glob. */
        char **gl_pathv;                        /* List of paths matching pattern. */
        /* Copy of errfunc parameter to glob. */
        int (*gl_errfunc) (const char *, int);
} glob_t;

**Comment by smrdoshi** [comment]
That's not an issue of ASTPP. Also we are in discussion in google group. Closing this issue.
