### ISSUE TITLE
latest version bug in reports

### ISSUE THREAD

**Issue by eightsixeight** [iNextrix/ASTPP#413]
http://prntscr.com/jazka6

You can see all successfull are now fails as well , 

but in the details they are all NORMAL_CLEARING [16]

**Comment by MrSupaMike** [comment]
I have something similar:

Calls work fine, everything works as before update. But on the main report it shows all calls as failed.

https://prnt.sc/jb1vdl

**Comment by plettonline** [comment]
I can confirm the same...

**Comment by pacomms** [comment]
i confirm bug as well
