### ISSUE TITLE
Max call length appears to be calculated wrong depending on settings

### ISSUE THREAD

**Issue by powerpbx** [iNextrix/ASTPP#415]
The system Call Max Length that is set in Configuration > Settings defaults to 144000 (24 minutes).  However, it appears to interact with Origination rates to cause an incorrect calculation above a certain amount depending on the origination rate.

If the call origination rate is 0.0200 6/6 then max_call_length is correctly calculated as 24 minutes which can be seen from `fs_cli` while making the call.

However, if I increase Call Max Length to 6000000 then the max_call_length is now calculated around 5000 minutes if I have $50 credit in the prepay account.

These appear to be two different variables for different purposes that are being combined.  The system max call length (which should be a fixed number) and the max possible call length based on the origination rate and account balance.

It appears the problem code is located here;
https://github.com/iNextrix/ASTPP/blob/46f16a598b093842a1d8ca16a385dcb3d6f71bd2/freeswitch/scripts/astpp/lib/astpp.functions.lua#L326

```
if (tonumber(rates['cost']) > 0 ) then
		      maxlength = ( balance -  rates['connectcost'] ) / rates['cost']
		      
		      if ( config['call_max_length'] and (tonumber(maxlength) > tonumber(config['call_max_length']) / 1000)) then
				maxlength = config['call_max_length'] / 1000 / 60
			      Logger.info("[FIND_MAXLENGTH] LIMITING CALL TO CONFIG MAX LENGTH "..maxlength.."!!!")
		      end
		else
		      Logger.info("[FIND_MAXLENGTH] Call is free - assigning max length!!! :: " .. config['max_free_length'] )
		      maxlength = config['max_free_length']
		end      
```
It appears that when the calculation sets `maxlength = config['call_max_length'] / 1000 / 60` that is the correct system max call length.  Otherwise it is set to `maxlength = ( balance -  rates['connectcost'] ) / rates['cost']` which is based on the account and the rates and not related to system max call length, even though the same variable is being used for some reason.

**Comment by smrdoshi** [comment]
Found the problem and it is fixed now in latest source.
