### ISSUE TITLE
Problem with failover trunks

### ISSUE THREAD

**Issue by DigiDaz** [iNextrix/ASTPP#419]
When a trunk has failover configured, eg gateway1, gateway2, gateway3 I notice that if a call is rejected at the remote end and sends back a 486 busy then each of the failover gayeways is tried and the called party has to reject the call three times.

**Comment by smrdoshi** [comment]
Yes, it will try as we have set continue_on_fail=true in code, that means in do failover for all not successful calls. 

You can either change code from call script or configure that parameter in gateway. 

Reference doc : https://wiki.freeswitch.org/wiki/Variable_continue_on_fail

**Comment by devangn** [comment]
@DigiDaz 
https://github.com/iNextrix/ASTPP/commit/7eb4a7db3ef8e7718f695e739387759cae1183ab#diff-b4ed7e9120fc034f6024af3c5f1f52f0
Check above commit for not to get failover when user is busy or whatever configuration you want.
