### ISSUE TITLE
Graph of Monthly Stat

### ISSUE THREAD

**Issue by ManuellaC** [iNextrix/ASTPP#420]
I'm having a problem with the graph of Monthly Stat, the value of Failed Calls is equal the value of Total Calls and this is wrong. How do we fix this?

**Comment by MrSupaMike** [comment]
@ManuellaC , This issue has been reported before and a pull request with the fix has been submitted:

https://github.com/iNextrix/ASTPP/pull/418

**Comment by MrSupaMike** [comment]
If you want to fix the issue right away:

find the file dashboard_model.php which should be in: astpp/application/modules/dashboard/models/
and edit line 56

Line 56 currently looks like this:
count(CASE WHEN disposition NOT IN ('NORMAL_CLEARING','SUCCESS') THEN 1 END) as failed,

Fix it by adding 'NORMAL_CLEARING [16]' like this:
count(CASE WHEN disposition NOT IN ('NORMAL_CLEARING','SUCCESS','NORMAL_CLEARING [16]') THEN 1 END) as failed,

Remember to backup before any changes, good luck.

**Comment by smrdoshi** [comment]
Request merged.
