### ISSUE TITLE
Usage Report doesn't open

### ISSUE THREAD

**Issue by ManuellaC** [iNextrix/ASTPP#421]
I can't open the Usage Report, that is on the way **Tariffs > Packages > Usage Report**. When I press to open this page, it is loading and doesn't open. Does anyone have the same problem?

**Comment by powerpbx** [comment]
The menu loads for me but the table is empty.  I tried creating a package but it's still empty.  Is there anything else we are supposed to configure?

**Comment by smrdoshi** [comment]
It will display records when your customer will make calls using that
package.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality4&>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance on the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.
