### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by whitesparrowbd** [iNextrix/ASTPP#435]
When i would like to update a customer this error occured from ADMIN PANNEL 
and could not update anything, please give me a solution

Error Number: 1054

Unknown column 'cps' in 'field list'

UPDATE `accounts` SET `id` = '3', `type` = '3', `password` = 'gaiaRg3lAZI$nTbTjVVe4Z0-hFxXrxCzQTOIug0SHow', `pin` = '320736', `first_name` = 'default', `last_name` = 'provider', `company_name` = 'ASTPP', `telephone_1` = '', `telephone_2` = '', `email` = 'yourprovider@test.com', `address_1` = 'adress', `address_2` = '', `city` = '', `province` = '', `postal_code` = '', `country_id` = '85', `timezone_id` = '49', `currency_id` = '59', `status` = '0', `is_recording` = '0', `allow_ip_management` = '1', `dialed_modify` = '', `std_cid_translation` = '', `did_cid_translation` = '', `maxchannels` = '0', `cps` = '', `first_used` = '0000-00-00 00:00:00', `validfordays` = '0', `expiry` = '2026-07-26 15:12:18', `pricelist_id` = '1', `sweep_id` = '2', `invoice_day` = '1', `credit_limit` = '0', `local_call` = '0', `charge_per_min` = '', `tax_number` = '' WHERE `id` = '3'

Filename: /var/www/html/astpp/modules/accounts/models/accounts_model.php

Line Number: 320

**Comment by smrdoshi** [comment]
Your database looks like with version 3.5. Please update it.
