### ISSUE TITLE
Greek characters support on email

### ISSUE THREAD

**Issue by pscomgr** [iNextrix/ASTPP#439]
Hi,

i m getting ???? when i try to right to greek ver. 3.6 on email templates

**Comment by devangn** [comment]
You need to modify DEFAULT CHARSET value for the responsible mysql tables which are default_templates and mail_details

**Comment by pscomgr** [comment]
i did but nothing changed, i tried to change to UTF8_unicode_ci , UTF_general_ci , greek_general_ci.

**Comment by devangn** [comment]
@pscomgr May be this can help, [PHP MySQL Greek letters showing like ???? marks](https://stackoverflow.com/questions/11806319/php-mysql-greek-letters-showing-like-marks)

**Comment by smrdoshi** [comment]
Hi @pscomgr 

Is your issue resolved?

**Comment by pscomgr** [comment]
Yes ,
thank you.
i modify DEFAULT CHARSET value for the responsible mysql tables which are default_templates and mail_details
