### ISSUE TITLE
Signup - empty rate group on customer

### ISSUE THREAD

**Issue by pscomgr** [iNextrix/ASTPP#440]
I just enable signup and i select from setting the default rate group.
when the client registers he can't see the rate group into his account

**Comment by devangn** [comment]
That newly create account will be under 'default' rate group and rates will be applied accordingly.
Customer portal wont need/have rate group information, its for admin/reseller's use.

**Comment by pscomgr** [comment]
but as you can see in the picture i have set default rate group for new accounts.
![capture](https://user-images.githubusercontent.com/38977346/41339041-89952bb0-6efc-11e8-9d33-904cce388c4f.PNG)

so probably the client must have some rates in his account.
correct?

in admin panel i can't see the rates for the new account it's empty.

**Comment by devangn** [comment]
Yeah, then new account(client/customer) will have the rates which are assigned to 'default' rate group.
![signup-cust-rg](https://user-images.githubusercontent.com/11748910/41394801-fb7901da-6fc8-11e8-83cf-79990e02e71f.png)

**Comment by pscomgr** [comment]
Correct, that's what i thought. But in my installation i can't see rate group when a client signed up!

**Comment by devangn** [comment]
@pscomgr You mean in customer portal?
You will see it in admin portal and can change it also.
From customer portal you wont see it, it just applied to that customer. In customer portal they just see 'My Rates' as per the rate group assign to them.
