### ISSUE TITLE
Edit Contact Param On Invite

### ISSUE THREAD

**Issue by eduardofoliveira** [iNextrix/ASTPP#444]
Good afternoon,

Can someone help me with a question?

How do I change the contact field of an INVITE

I need to remove the prefix "gw+"

Because my termination determines the client based on the contact header

Regards,

Eduardo.

**Comment by scoobydoowru** [comment]
There was a recent commit on v3.6 that added "Extension-In-Contact" setting in Gateway settings.  I think if you set that to true it will accomplish that.

https://freeswitch.org/confluence/display/FREESWITCH/Sofia+Gateway+Authentication+Params

**Comment by powerpbx** [comment]
There was a recent commit on v3.6 that added "Extension-In-Contact" setting in Gateway settings. I think if you set that to true it will accomplish that.

https://freeswitch.org/confluence/display/FREESWITCH/Sofia+Gateway+Authentication+Params

**Comment by devangn** [comment]
@eduardofoliveira PR #434
