### ISSUE TITLE
Currency import broken by retired API (again)

### ISSUE THREAD

**Issue by AlexHeylin** [iNextrix/ASTPP#445]
Shortly after this was kindly rewritten in v3.6, fixer.io retired the old API and the new one only allows the base currency to be EUR in the free plan. Doh!

I'm working on changing to a new API.  I'll probably use https://1forge.com/forex-data-api/pricing unless anyone has better suggestion? Needs to allow a choice of base currency, and be free then very cheap for low usage. We'll encourage users to pay, but ideally not require them to in order to use the feature.

I'm also looking to add ability to allow for a percentage to be lost in currency conversion, so rate in ASTPP DB is closer to the rate you actually get and not the "wholesale" rate from the API.  This can cover bank charges etc.

I'll submit PR when ready.

**Comment by AlexHeylin** [comment]
PR issued https://github.com/iNextrix/ASTPP/pull/446

**Comment by smrdoshi** [comment]
Closing this issue as we are going to merge PR #446 when you ready.
