### ISSUE TITLE
rates allow ability to start billing only after x seconds 

### ISSUE THREAD

**Issue by isrlgb** [iNextrix/ASTPP#45]
i have calls that i bill only after a half minute is there anyway to do that here?

**Comment by dev-astpp** [comment]
Set 30 seoncds in 

> Included Seconds

It should work

**Comment by isrlgb** [comment]
well i tried that thinking it might be and it doesnt work


i have 
code | connect | included | sell | first increment| increment
144 0.0000	25	3.0000	60	1	

and im billed 3.000 for 8 seconds

**Comment by dev-astpp** [comment]
Where you have specified Termination or Origination rates?

It should be specified in Origination rates to give free first 30 seconds

**Comment by isrlgb** [comment]
Of course origination

בתאריך 11 באוג׳ 2016 3:57 PM,‏ "ASTPP Development" <notifications@github.com>
כתב:

**Comment by smrdoshi** [comment]
Fixed now. Please confirm.
