### ISSUE TITLE
Origination & Termination Rate import sample files states currency is USD, if base currency not USD

### ISSUE THREAD

**Issue by AlexHeylin** [iNextrix/ASTPP#452]
Header row is 

Code | Destination | Connect Cost(USD) | Included Seconds | Per Minute Cost(USD) | Initial Increment | Increment
-- | -- | -- | -- | -- | -- | --

Should either state base currency, or not mention currency at all.  Will remove mentions of currency and submit PR when I have time.

**Comment by smrdoshi** [comment]
That's a bug. It should not have any currency in header. 
Please submit PR.
