### ISSUE TITLE
Dashboard top graph - profit scaling not optimum

### ISSUE THREAD

**Issue by AlexHeylin** [iNextrix/ASTPP#453]
Currently total calls goes to the left yAxis, while answered calls, unanswered calls, and profit goes to the right yAxis.  This doesn't make sense to me, and in high-value currencies like GBP the profit is scaled to virtually invisible because the right yAxis scales to the number of calls.
![22-dashboard-without-gma-patch](https://user-images.githubusercontent.com/270973/42469795-abf13398-83b0-11e8-9acb-81fc431d44fa.PNG)
Note how the profit line is so close to zero as to be of little use. 

I propose moving all calls to the left yAxis as they all share the same scaling, and leaving just the profit on the right yAxis which allows it to scale to suit the currency, and show the differences per day much more clearly, like this. 
![22-dashboard-after-gma-patch](https://user-images.githubusercontent.com/270973/42469926-fd0bcd56-83b0-11e8-89be-092cdfbe4002.PNG)
Ignore the actual profit values, as both of these are from different test systems with different rate cards - look at the scale on the right, and notice that the profit line in the graph is clearly visible and much more useful.

Does this seem like an improvement to other people?
If so, I can submit PR for the minor changes required.

**Comment by smrdoshi** [comment]
I like the idea. +1
