### ISSUE TITLE
Reverse config of OpenSIP / Freeswitch setup

### ISSUE THREAD

**Issue by FozzyGo4** [iNextrix/ASTPP#46]
When configuring the main settings in ASTPP, if OpenSIP is set to **disable** then if I add a new customer an option to create a new **OpenSIP device** is given. If OpenSIP in settings is set to **Enable** then the Option of create new **SIP device** is given when adding a new customer.

**Comment by FozzyGo4** [comment]
I fixed this by editing the following file and change value from 1 to 0:
/astpp/application/modules/accounts/libraries/accounts_form.php

`if (common_model::$global_config['system_config']['opensips'] == **1**) {`

change to 

`if (common_model::$global_config['system_config']['opensips'] == **0**) {`

There are two instances of this code in the file to change.

**Comment by FozzyGo4** [comment]
Not sure why I closed this issue but re-opened so you can confirm it is a bug.

**Comment by dev-astpp** [comment]
This issue has been fixed. Please take updated source.
