### ISSUE TITLE
JQuery version error

### ISSUE THREAD

**Issue by powerpbx** [iNextrix/ASTPP#460]
Browsing to any page in the GUI results in the following jQuery errors when viewing Chrome or FireFox element inspection console view.

```
(index):101 Uncaught ReferenceError: SyntaxHighlighter is not defined
    at (index):101
(anonymous) @ (index):101
maxcdn_bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher
    at maxcdn_bootstrap.min.js:6
    at maxcdn_bootstrap.min.js:6
```

**Comment by AlexHeylin** [comment]
I also see this issue.

**Comment by AlexHeylin** [comment]
This appears to be a duplicate of #170 
https://github.com/iNextrix/ASTPP/issues/170

**Comment by smrdoshi** [comment]
That's right. Its duplicate of #170 

Closing this bug.
