### ISSUE TITLE
Feature request - Disable customer from adding/editing their Caller Ids

### ISSUE THREAD

**Issue by marcozink** [iNextrix/ASTPP#463]
Hi, this ASTPP is a great tool, thank you for your work.

It would be great to be able to block users from adding or editing their Caller IDs. It would allow the admin to set the pool they can use and avoid the client to use an unauthorized number as their CID.

Thanks in advance!

Regards

**Comment by rgazetta** [comment]
Feature request - Permissions User #458

**Comment by pscomgr** [comment]
Hi ,
a little bit of help for now...

[Web interface user changes.txt](https://github.com/iNextrix/ASTPP/files/2775629/Web.interface.user.changes.txt)
[disable user create sip account .txt](https://github.com/iNextrix/ASTPP/files/2775631/disable.user.create.sip.account.txt)

Kind Regards

**Comment by Hemdip** [comment]
@marcozink , We have implemented Roles & Permission module for Admin/Subadmin & Reseller in V-4.0
You can update your version and verify. We also going to implement for Customer in V-5.0
