### ISSUE TITLE
Changing Balance View in Email

### ISSUE THREAD

**Issue by eduardofoliveira** [iNextrix/ASTPP#464]
How can I change to have only 2 digits after the point in the balance warning.

For today the balance is displayed as follows: 40.35900

I need you to get it: 40.35

But only in balance warning emails

**Comment by smrdoshi** [comment]
Its centralized in entire system. If you want to do it in balance warning
email only then you will need to do modification in code and if you want to
do it in entire system then check settings -> Global. You will find decimal
field.

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance on the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by eduardofoliveira** [comment]
Thank You @smrdoshi
