### ISSUE TITLE
Logs do not show the details of calls

### ISSUE THREAD

**Issue by John91000** [iNextrix/ASTPP#466]
Why can not see the caller id? before that was good

https://cdn1.savepice.ru/uploads/2018/9/4/a9312dc66abbee7f49b9d47dea09f2c5-full.jpg

**Comment by smrdoshi** [comment]
What do you mean by "before that was good?"

In which version was it working? and which version are you using at the moment?

**Comment by John91000** [comment]
3.6 it work good, but when edit sip devices id logs dont show callers

**Comment by Hemdip** [comment]
Closing it, as it seems softphone issue and no update since very long.
