### ISSUE TITLE
SIP-DID return USER_NOT_REGISTERED, but DID-local is working

### ISSUE THREAD

**Issue by eduardofoliveira** [iNextrix/ASTPP#473]
Good night,

I updated ASTPP but I have a problem:

Recently all calls that are with the DID set to call-type SIP-DID are returning USER_NOT_REGISTERED.

When we test as DID-Local the call is received by the PBX normally.

But this way I can not determine which DID this call belongs to.

How can we find the error in this case?

Regards,

Eduardo.

**Comment by eduardofoliveira** [comment]
![did-config](https://user-images.githubusercontent.com/20446658/49632225-1679c300-f9dc-11e8-8b98-18da2f157ace.png)

My current configuration is according to the image above, where one works and the other does not.

**Comment by smrdoshi** [comment]
Hi,

Provide your call fs_cli log for SIP-DID.
Also, run the following command in fs_cli and give its output

> eval ${domain_name}

Thanks,

Samir Doshi

iNextrix Technologies Pvt. Ltd.

https://www.inextrix.com

https://www.astppbilling.org

Disclaimer:

The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance on the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
12/07/18,
5:00:42 PM

**Comment by eltonbahiabc** [comment]
no log conta que o ramal não está registrado.
Rode o comando show registrations on CLI do freeswitch e verifica se ele contra-se conectado na lista.

**Comment by eduardofoliveira** [comment]
Esta registrado, tem sessão:

Call-ID:        242dcda0a4664de2b45583e12ea7dc10
User:           TSingular@172.31.6.59
Contact:        "TSingular" <sip:TSingular@192.168.4.10:64491;ob;fs_nat=yes;fs_path=sip%3ATSingular%40177.189.208.91%3A64491%3Bob>
Agent:          MicroSIP/3.19.7
Status:         Registered(UDP-NAT)(unknown) EXP(2018-12-07 12:07:02) EXPSECS(110)
Ping-Status:    Reachable
Ping-Time:      0.00
Host:           ip-172-31-6-59
IP:             177.189.208.91
Port:           64491
Auth-User:      TSingular
Auth-Realm:     singular.cloudcom.com.br
MWI-Account:    TSingular@172.31.6.59

Mas o freeswitch não esta conseguindo encontrar.

**Comment by eduardofoliveira** [comment]
Hi Samir

I found what was causing the problem.

![sip profiles](https://user-images.githubusercontent.com/20446658/49661560-82861680-fa30-11e8-8b11-38db0ce0f5fb.png)

I had two profiles enabled.

When I disabled the profile that was not in use and stopped it, the SIP-DID calls started again.

Regards,

Eduardo.

**Comment by smrdoshi** [comment]
Ok Great.

Thanks,

Samir Doshi

iNextrix Technologies Pvt. Ltd.

https://www.inextrix.com

https://www.astppbilling.org

Disclaimer:

The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance on the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
12/10/18,
6:31:41 PM
