### ISSUE TITLE
Feature Request - Changing notification system

### ISSUE THREAD

**Issue by voztovoice** [iNextrix/ASTPP#479]
Hello,
Currently ASTPP sends notifications related to the low credit, according to the predefined cron configuration, once per day. The idea is to change the cron configuration and the code so that it checks more often but does not send the notification to the same client more than once per day.
Thank you.

**Comment by devangn** [comment]
@voztovoice Not more often we get this request so we may not plan to add it soon, but thanks for the suggestion; if you add it on your own please send merge request.
