### ISSUE TITLE
Problem using CPS

### ISSUE THREAD

**Issue by eduardofoliveira** [iNextrix/ASTPP#485]
Good afternoon,

Whenever I use the CPS fields of the account or Trunk the calls stop completing.

In the freeswitch log I found this error:

2019-01-31 19: 39: 47.308430 [DEBUG] switch_limit.c: 43 Unable to locate limit backend: hash
2019-01-31 19: 39: 47.308430 [ERR] switch_limit.c: 122 Limit subsystem hash not found!

Do I need to enable anything to use the feature?

Regards,

Eduardo.

https://pastebin.freeswitch.org/view/47593cdc

**Comment by devangn** [comment]
@eduardofoliveira 
Please, check mod_hash is loaded in FS or not.

**Comment by eduardofoliveira** [comment]
@devangn 
Thanks for the help, the module is disabled.
I'll enable and start the tests.
