### ISSUE TITLE
Feature Request - Test/Debug Routing LCR/Cost

### ISSUE THREAD

**Issue by spchester** [iNextrix/ASTPP#486]
Unless I'm just missing it, I don't see a way to test the routing for an outbound call without making a call. I'd like to be able to type in a number and then see the logic that astpp is using to route the call. Ideally it would show matching termination rates, including possible alternative rates, and the provider that the call would be sent out.

**Comment by devangn** [comment]
@spchester 
Yes, rate simulator is there in the list. May not be added sometime soon but thanks.
