### ISSUE TITLE
Bug: Searching for invoices doesn't work - browser console shows 500 error from server, GUI 

### ISSUE THREAD

**Issue by AlexHeylin** [iNextrix/ASTPP#489]
May (or may not) be related to #170 
Search calls a URL for JSON which returns 500 internal server error and no content. 
GUI shows "Processing, please wait ..." forever - so timeout / error trapping is not good either. 

For example, searching for invoice numbers starting with "T011" calls this URL 
```
jquery-1.7.1.js:8102 
GET http://SERVER_DNS:8089/invoices/invoice_list_json?page=1&rp=10&sortname=undefined&sortorder=undefined&query=&qtype= 
500 (Internal Server Error)
```

Which I notice doesn't contain the search term. I cannot load this directly from browser.

If I refresh page and then change pagination to 50 it calls
```
http://SERVER_DNS:8089/invoices/invoice_list_json?page=1&rp=50&sortname=undefined&sortorder=undefined&query=&qtype=
```
which loads fine, and I can load directly from browser.

Those are basically the same URL, just with different rp values - so try 
```
http://SERVER_DNS:8089/invoices/invoice_list_json?page=1&rp=10&sortname=undefined&sortorder=undefined&query=&qtype= 
```
directly in browser again and it loads fine.  At this point, I'm confused why this doen't work in first instance but works fine in second instance.  However first instance doesn't contain search term, so won't work as expected anyway. 

Of course the expected console messages show up:
```
(index):165 Uncaught ReferenceError: SyntaxHighlighter is not defined
    at (index):165
(anonymous) @ (index):165
maxcdn_bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher
    at maxcdn_bootstrap.min.js:6
    at maxcdn_bootstrap.min.js:6
(anonymous) @ maxcdn_bootstrap.min.js:6
(anonymous) @ maxcdn_bootstrap.min.js:6
jquery-1.7.1.js:8068 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery-1.7.1.js:8068
ajax @ jquery-1.7.1.js:7580
gettext_custom @ generate_grid.js:640
build_collumns @ generate_grid.js:246
build_grid @ generate_grid.js:190
(anonymous) @ (index):104
fire @ jquery-1.7.1.js:1046
fireWith @ jquery-1.7.1.js:1164
ready @ jquery-1.7.1.js:435
DOMContentLoaded @ jquery-1.7.1.js:923
DevTools failed to parse SourceMap: http://SERVER_DNS:8089/assets/css/bootstrap.min.css.map
DevTools failed to parse SourceMap: http://SERVER_DNS:8089/assets/css/bootstrap-select.css.map
```
but as far as I know these are all covered by #170

**Comment by Hemdip** [comment]
@AlexHeylin Please verify on V-4.0 it has been fixed, In case of any issue you may reopen or report new issue
