### ISSUE TITLE
Can't Search Termination Rates for Is Equal To

### ISSUE THREAD

**Issue by spchester** [iNextrix/ASTPP#493]
<img width="526" alt="Screen Shot 2019-03-26 at 5 32 04 PM" src="https://user-images.githubusercontent.com/47045934/55042075-3960cf00-4fed-11e9-984e-6dd7191fc410.png">
<img width="543" alt="Screen Shot 2019-03-26 at 5 31 54 PM" src="https://user-images.githubusercontent.com/47045934/55042082-3cf45600-4fed-11e9-8b21-4c89f23783a8.png">

I believe this was also an issue in 3.0, but you can’t seem to search termination rates for code is equal to. For example, search 1201200 with begins with and you’ll find two matches. Change the search to is equal to and no results are found. Maybe I misunderstand this, but there are times you want to be able to search for “1” and not find the other 673,184 records that start with 1.

**Comment by Hemdip** [comment]
Verified and It will be fixed in upcoming version

**Comment by Hemdip** [comment]
@spchester Issue has been fixed in V-4.0 as per my previous comment, You can verify by updating your ASTPP version
