### ISSUE TITLE
"DESTINATION_OUT_OF_ORDER" records not showing in Web UI

### ISSUE THREAD

**Issue by watoan** [iNextrix/ASTPP#494]
I have total 41 records in "cdrs" table, Customer CDRs view are showing 18, and Provider CDRs view are showing 18, then I found the remain 5 of them in DB are not showing in Web UI, and all of them with disposition = 'DESTINATION_OUT_OF_ORDER [27]'

I am logged in the Web UI with admin account, and there is no special criteria when I search the CDRs, only date range and leave others blank.

I tried to search only "DESTINATION_OUT_OF_ORDER" records in Web UI, but no result found.

Note: Fresh install Freeswitch with tarball and install ASTPP using the source download from Github on 20 Feb, is there any new version fixed this issue after that?

Thanks.

**Comment by Hemdip** [comment]
@watoan 
Can you please verify this thing : in your cdrs run this query select * from cdrs where accountid=0; and share your result

**Comment by watoan** [comment]
@Hemdip 
Sorry for delay, Just ran the query, I got total 23 result (those 5 records with "DESTINATION_OUT_OF_ORDER" included).
However, those 5 records are not showing in the web.

**Comment by Hemdip** [comment]
@watoan ,

Thanks, Got your point. It will be fixed in upcoming version release.

**Comment by Hemdip** [comment]
@watoan , Please upgrade V-4.0, issue has been fixed now. If you face any new issue then report again or reopen for same issue
