### ISSUE TITLE
CDR report is not displayed correctly.

### ISSUE THREAD

**Issue by Madji** [iNextrix/ASTPP#498]
Call Report -> Detail Report-> Customer.
In the Debit and Cost columns, NaN is displayed. In the user interface in the reports everything is set down normally. An example of the screen.
![IMG_20190419_200345](https://user-images.githubusercontent.com/2238714/56435306-af044600-62e0-11e9-8d8d-09a1167d253b.jpg)

**Comment by Madji** [comment]
This becomes possible if you use a currency other than usd.

**Comment by hardikinextrix** [comment]
Hi Madji

As we have launched new version of ASTPP 4.0 Please confirm the problem has been resolved in new release.
