### ISSUE TITLE
Prepay to Post pay

### ISSUE THREAD

**Issue by aparajey** [iNextrix/ASTPP#501]
cant change customer account type from prepay to postpay once account is created. i have to change it from database to convert running customer from prepay to postpay

**Comment by smrdoshi** [comment]
Yes, we are not allowing to change it once account has been created. If you
do it after creating account then it will mess up the billing process.

Thanks,

Samir Doshi

iNextrix Technologies Pvt. Ltd.

https://www.inextrix.com

https://www.astppbilling.org

Disclaimer:

The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance on the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/21/19,
8:06:55 AM

**Comment by aparajey** [comment]
i have installed ASTPP with multiple freeswitch everything working fine but live calls are not showing in ASTPP UI, i did allowed 0.0.0.0 in even_socket.conf.xml and result are same also ASTPP is not able to send emails to customers below is astpp_email.log

Your message has been successfully sent using the following protocol: mail<br />Date : May 18, 2019, 4:43 pm
 From :helpdesk@incorpus.in
 To :xcast@123.com
 Subject :Sip device added successfully
 Attachment :
Error : 
<pre>hello: </pre>The following SMTP error was encountered: <br />Unable to send data: AUTH LOGIN<br />Failed to send AUTH LOGIN command. Error: <br />Unable to send data: MAIL FROM:<helpdesk@incorpus.in><br /><pre>from: </pre>The following SMTP error was encountered: <br />Unable to send data: RCPT TO:<xcast@123.com><br /><pre>to: </pre>The following SMTP error was encountered: <br />Unable to send data: DATA<br /><pre>data: </pre>Unable to send data: .<br /><br />The following SMTP error was encountered: <br />Unable to send email using PHP SMTP.  Your server might not be configured to send mail using this method.<br />Date : May 18, 2019, 4:44 pm
 From :helpdesk@company.com
 To :vendor@123.com
 Subject :Sip device added successfully
 Attachment :
Error : 
<pre>hello: </pre>The following SMTP error was encountered: <br />Unable to send data: AUTH LOGIN<br />Failed to send AUTH LOGIN command. Error: <br />Unable to send data: MAIL FROM:<helpdesk@company.com><br /><pre>from: </pre>The following SMTP error was encountered: <br />Unable to send data: RCPT TO:<vendor@123.com><br /><pre>to: </pre>The following SMTP error was encountered: <br />Unable to send data: DATA<br /><pre>data: </pre>Unable to send data: .<br /><br />The following SMTP error was encountered: <br />Unable to send email using PHP SMTP.  Your server might not be configured to send mail using this method.<br />Date : May 18, 2019, 4:44 pm
 
PLease Note: i have modified FROM and TO here to keep company names private.

**Comment by hardikinextrix** [comment]
To generate live call report data you  must have to add Freeswitch server details.

Please confirm the details for Freeswitch server, you have added on ASTPP GUI it must be correct.

**Comment by aparajey** [comment]
yes it is correct as i said CDR are is generating fine customer is getting billed fine it is just that on live calls its nothing.

![Screenshot 2019-05-29 at 1 06 10 PM](https://user-images.githubusercontent.com/23430485/58538408-b9d0c580-8212-11e9-8a20-f323ddb5b36f.png)
