### ISSUE TITLE
Invoice Generation error ASTPP4.0

### ISSUE THREAD

**Issue by aparajey** [iNextrix/ASTPP#503]
when clicking on confirm in manual Invoice generation ASTPP 4.0 gives Database error.

![Screenshot 2019-05-29 at 1 42 17 AM](https://user-images.githubusercontent.com/23430485/58509120-6a0ee180-81b3-11e9-9f1f-8be452e0fcf9.png)

**Comment by Hemdip** [comment]
@aparajey , Are you using centos? If yes then will you please restart mysql service and check same.

**Comment by Hemdip** [comment]
@aparajey 
We have verified and not found such issue, might be your source not updated/permission related problem on server. Closing this issue If you face again then reopen it.
