### ISSUE TITLE
Signup - Captcha Does Not Display ASTPP 4.0

### ISSUE THREAD

**Issue by baloeng** [iNextrix/ASTPP#505]
Hello All,

Still exploring the new version. Awesome work by the ASTPP team.

On the signup page, the Captcha does not display, hence, new customer cannot register.

**Comment by meshtask** [comment]
Same issue. I cannot see Captcha at signup page after installation. No captcha stting is present in ASTPP Settings page too.

**Comment by Hemdip** [comment]
@baloeng @meshtask 

Which OS you have used? Have you check any error log?

**Comment by meshtask** [comment]
Problem is solved by changing owner and group to apache for directory /opt/ASTPP.
https://github.com/iNextrix/ASTPP/issues/518#issuecomment-500208283

**Comment by Hemdip** [comment]
@meshtask Noted 

As your issue has been fixed "#518 (comment)" so closing this issue
