### ISSUE TITLE
It's more of a question than an issue. 

### ISSUE THREAD

**Issue by Madji** [iNextrix/ASTPP#506]
Hello, I can not understand the meaning of the possibility of adding a translation. when you create a user account, you cannot select a translation . Am I looking in the wrong place? Maybe I don't understand. Thanks

![изображение](https://user-images.githubusercontent.com/2238714/58664015-70799680-8336-11e9-82d3-03255f48cfc6.png)

**Comment by plettonline** [comment]
From what I can see,
You now need to create the Localization first under 👍 
Switch --> Localizations

Thereafter, you can assign it where you need to...

**Comment by plettonline** [comment]
What would be nice is a way to create a default Localization for new accounts... something that is preselected for all new accounts...

**Comment by Madji** [comment]
> From what I can see,
> You now need to create the Localization first under 
> Switch --> Localizations
> 
> Thereafter, you can assign it where you need to...
It's not working. language created, updated. translation added. when you select a language from the bottom of the drop-down list. the page is simply updated and that's it. language is English

**Comment by Hemdip** [comment]
@Madji You can set global localization for your customer from Configuration > Settings > Signup

**Comment by Madji** [comment]
Thanks.
