### ISSUE TITLE
Call Recordings Not Displaying in CDRs

### ISSUE THREAD

**Issue by meshtask** [iNextrix/ASTPP#507]
Calls are being recorded properly and i can see the recordings in folder /var/lib/freeswitch/recordings
But in CDRs I only see 2 red X in Call Recordings Column.

**Comment by Hemdip** [comment]
@meshtask Please verify that folder is having 755 permission if not then give and check once

**Comment by meshtask** [comment]
Changed the permission of the call recordings folder. Problem solved with this. Now I can see call recordings audio files link in CDRs. Thanks

**Comment by meshtask** [comment]
I did a fresh install of ASTPP v4 today multiple times on CentOS 7 64 bit minimal  VPS. Default owner and group of recordings folder was freeswitch:daemon and permission was 0750.
I changed permission to 755 and restarted VPS. But this time i am unable to see Call Recordings on CDRs. I just see red X in Recordings column. Every time i make calls, call recordings wav files are being correctly generated in the recordings folder. What am i doing wrong this time? How can i resolve this issue please?

**Comment by meshtask** [comment]
I did a fresh install of ASTPP v4 today multiple times on CentOS 7 64 bit minimal VPS. Default owner and group of recordings folder was freeswitch:daemon and permission was 0750.
I changed permission to 755 and restarted VPS. But this time i am unable to see Call Recordings on CDRs. I just see red X in Recordings column. Every time i make calls, call recordings wav files are being correctly generated in the recordings folder. What am i doing wrong this time? How can i resolve this issue please?

**Comment by meshtask** [comment]
Issue resolved by changing permission to 755 for the directory /var/lib/freeswitch/ instead of /var/lib/freeswitch/recordings/
