### ISSUE TITLE
Selling price of DID under reseller

### ISSUE THREAD

**Issue by plettonline** [iNextrix/ASTPP#508]
Main admin account set DID selling price at a monthly cost of $X.
The reseller purchases DID for $X.
Reseller sets selling price to $Y.

ERROR --> Resellers customer gets charged $X instead of $Y when purchasing DID.
The same issue occurs with subreseller as well as its customers.

I tested the method when logged into the main admin account and used "quick logins" to resellers and customers to make purchases.

I edited the "reseller" permission to allow the reseller to edit DID to allow them to set selling price.

It seems the problem extends anything below main admin account.

**Comment by Hemdip** [comment]
@plettonline 
Your reseller is distributor? If yes then only $Y price apply else it will apply $X price.

You can share screenshot or small video to get clear idea about your issue.

**Comment by plettonline** [comment]
Hi there,

This is for a Reseller (not a distributor)

1. Main account account sets price of DID at 10.00
2. Main account creates RESELLER
3. Reseller purchases DID from main accoutn at 10.00
4. Reseller sets selling price of DID as 25.00
5. Reseller creates customer
6. Reseller Customer purchases DID from Reseller
7. Reseller Customer gets charged 10.00

The problem is that Reseller customer should be charged 25.00 and not 10.00

I will follow up with a video showing the above.

**Comment by plettonline** [comment]
I think i follow the logic now....
In addition to the role flag, there is also a "Is distributor" flag...
I see that this was set...

If I try and change "Is distributor" to "NO", i get the following error :
An Error Was Encountered
Call to a member function build_charges_list_for_customer() on null

**Comment by plettonline** [comment]
I thnk i will raise the above as a new "issue" as it seems to be consistent.

**Comment by plettonline** [comment]
Hi,

I have recreated the error on your demo version of ASTPP 4... (http://latest.astppbilling.org)

https://www.loom.com/share/c06ffa41b74a4d8aac6723e10741eeda

**Comment by plettonline** [comment]
Have you managed to confirm this on your end as yet?

**Comment by Hemdip** [comment]
Hello @plettonline ,

Yes we have rectify issue, it will be fix soon. [0003478]

**Comment by plettonline** [comment]
Thx Hemdip... I'm glad that you have confirmed the bug :-) ....

**Comment by hardikinextrix** [comment]
New version is released now Please update and verify your concern.
https://astpp.readthedocs.io/en/v4.0.1/Installation/upgrade.html

**Comment by Hemdip** [comment]
@plettonline Above reported issue has been fixed, Please review with latest source and share your feedback.

**Comment by Hemdip** [comment]
@plettonline  Closing this issue if you face any other issue then you can report new.
Thanks!
