### ISSUE TITLE
Visual | GUI | Spelling of recurring on web interface

### ISSUE THREAD

**Issue by plettonline** [iNextrix/ASTPP#511]
The spelling of recurring on GUI is "reccuring"... This should be "recurring"

Have noted this on "Inbound --> DID" ---- Billing type

**Comment by Hemdip** [comment]
@plettonline thank for reporting, It will be fix in future.

**Comment by Hemdip** [comment]
@plettonline Spell issue has been fixed, please verify in updated release (source)
