### ISSUE TITLE
Missing fields in trunks. v.4.0

### ISSUE THREAD

**Issue by tridcatij** [iNextrix/ASTPP#513]
Hey, in v.3 there were number and callerId translation fields for trunks. I cannot find it in v.4. There are fields in the DB though.

ASTPP 3.6
![image](https://user-images.githubusercontent.com/4353590/58940494-4256e500-8782-11e9-8b4a-a8168c4d1dbc.png)

ASTPP 4.0
![image](https://user-images.githubusercontent.com/4353590/58940458-2c492480-8782-11e9-824f-5901c887bd67.png)

**Comment by Hemdip** [comment]
You can do that in 4.0, We have introduce Localization concept 
Switch > Localization here you have to set rules and Give it to your Provider from Accounts module, It will work same as 3.6

**Comment by tridcatij** [comment]
Could you please give an example? In my case, I have 5 trunks for one account. For each of them I need different callerid number translation. Prefixes are not related to the destinations in my case. We're splitting different price/quality strategies with it.

**Comment by watoan** [comment]
Yup, I am having the similar issue with 4.0 for DNIS.
In case I have 2 trunks of 1 provider account, it's used to separate different level of routing, previously I can do it in "Trunks" - prepend prefix, but in 4.0, seems I can have only 1 localization setting for 1 provider account, could you please advise how can I prepend tech prefix for 2 different trunks of same provider account?
Should I do it in "termination rates" > "Prepend"? but it is not ideal way for me, tech prefix should always related to "Trunks" level.
Or should I create 2 provider account in this case? it is not ideal too....
Thanks.

**Comment by Hemdip** [comment]
Not sure about your scenario, But i have one suggestion for you,

In your provider's Rategroup you can select your those 2 trunk, might be it work for you.
