### ISSUE TITLE
Can't install addons in ASTPP 4.0

### ISSUE THREAD

**Issue by timur-v** [iNextrix/ASTPP#518]
Hello,
When I try to install addons "Support Tickets" and "Switch Monitoring" the installation fails (the same way in both cases):
![image](https://user-images.githubusercontent.com/51515806/59150794-2f007f80-89f7-11e9-9bd9-3e3d4b1d56db.png)
The addon "Account Number Range" was installed successfully.
I'm trying ASTPP 4.0 on a virtual machine.

**Comment by meshtask** [comment]
Just tested. Same thing is happening on my install. I cannot install any other plugins except "Account Number Range"

**Comment by timur-v** [comment]
I found what causes this issue. It happens due to incorrect read/write permissions in /var/www/html/astpp/ directory. Owner of those files is root user, so web-server may not write new files there. ASTPP installation script consist this: "chown -Rf www-data.www-data /var/www/html/astpp", but /var/www/html/astpp/  is actually a symbolic link and chown doesn't change symbolic links by default.  Files are actually place in /opt/ASTPP/web_interface/astpp directory. 
So, solution for this issue may be either "chown -LRf www-data.www-data /var/www/html/astpp" or "chown -Rf www-data.www-data /opt/ASTPP/web_interface/astpp".
I did this and was able to install addons then.
But I'd prefer to have developers' confirmation that such a solution doesn't create breach in web server security.

**Comment by Redbehrend** [comment]
can confirm this also fixes importing rates into ASTPP

**Comment by smrdoshi** [comment]
Hi @timur-v 

The solution which you mentioned make sense and as far as I understand, It will not create a security issue. 
However, we will still investigate on it and update script accordingly.

**Comment by devangn** [comment]
Modified permissions in installation script, Commit: 10fb4b69a72f56a7d40e0ed682cca9292a618016
It will work now.

**Comment by Hemdip** [comment]
@timur-v Issue has beed resolve, please take updated source and verify.
