### ISSUE TITLE
Fail call when from customer in resellser account

### ISSUE THREAD

**Issue by juancarlosg6** [iNextrix/ASTPP#52]
Hi, whe create a customer on reseller account, create sip device or ip settings, always received this error, the rate group are create, whe we create a sip device to customer account from the "admin" user, all found very good, thanks for the help.

2016-08-12 02:18:57.667824 [NOTICE] switch_cpp.cpp:1360 [ASTPP] FINDING LIMIT FOR RESELLER: 19
2016-08-12 02:18:57.667824 [DEBUG] switch_cpp.cpp:1360 [ASTPP] [Functions] [DOAUTHORIZATION] Query :SELECT * FROM accounts WHERE (number = "19" OR id="19") AND status=0 AND deleted=0 AND expiry >= '2016-08-12 07:18:57' limit 1                                                                        
2016-08-12 02:18:57.667824 [ERR] mod_lua.cpp:203 **/usr/local/freeswitch/scripts/astpp/lib/astpp.functions.lua:156: attempt to index global 'userinfo' (a string value)                                                                                                                                     
stack traceback:**                                                                                                                                     

2016-08-12 02:18:57.667824 [ERR] mod_lua.cpp:270 LUA script parse/execute error!
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->unloop] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (PASS) [unloop] ${unroll_loops}(true) =~ /^true$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [unloop] ${sip_looped_call}() =~ /^true$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->tod_example] continue=true
Dialplan: sofia/default/50640329559@52.204.115.208 Date/TimeMatch (FAIL) [tod_example] break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->holiday_example] continue=true
Dialplan: sofia/default/50640329559@52.204.115.208 Date/TimeMatch (FAIL) [holiday_example] break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->global-intercept] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [global-intercept] destination_number(50625921111) =~ /^886$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->group-intercept] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [group-intercept] destination_number(50625921111) =~ /^\*8$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->intercept-ext] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [intercept-ext] destination_number(50625921111) =~ /^\*\*(\d+)$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->redial] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [redial] destination_number(50625921111) =~ /^(redial|870)$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->global] continue=true
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [global] ${call_debug}(false) =~ /^true$/ break=never
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (PASS) [global] ${default_password}(1234) =~ /^1234$/ break=never
Dialplan: sofia/default/50640329559@52.204.115.208 Action log(CRIT WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING ) 
Dialplan: sofia/default/50640329559@52.204.115.208 Action log(CRIT Open /usr/local/freeswitch/conf/vars.xml and change the default_password.) 
Dialplan: sofia/default/50640329559@52.204.115.208 Action log(CRIT Once changed type 'reloadxml' at the console.) 
Dialplan: sofia/default/50640329559@52.204.115.208 Action log(CRIT WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING ) 
Dialplan: sofia/default/50640329559@52.204.115.208 Action sleep(10000) 
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [global] ${rtp_has_crypto}() =~ /^(AEAD_AES_256_GCM_8|AEAD_AES_128_GCM_8|AES_CM_256_HMAC_SHA1_80|AES_CM_192_HMAC_SHA1_80|AES_CM_128_HMAC_SHA1_80|AES_CM_256_HMAC_SHA1_32|AES_CM_192_HMAC_SHA1_32|AES_CM_128_HMAC_SHA1_32|AES_CM_128_NULL_AUTH)$/ break=never                                                                                                                                   
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [global] ${endpoint_disposition}(RECEIVED) =~ /^(DELAYED NEGOTIATION)/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->snom-demo-2] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [snom-demo-2] destination_number(50625921111) =~ /^9001$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->snom-demo-1] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [snom-demo-1] destination_number(50625921111) =~ /^9000$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->eavesdrop] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [eavesdrop] destination_number(50625921111) =~ /^88(\d{4})$|^\*0(.*)$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->eavesdrop] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [eavesdrop] destination_number(50625921111) =~ /^779$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->call_return] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [call_return] destination_number(50625921111) =~ /^\*69$|^869$|^lcr$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->del-group] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [del-group] destination_number(50625921111) =~ /^80(\d{2})$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->add-group] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [add-group] destination_number(50625921111) =~ /^81(\d{2})$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->call-group-simo] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [call-group-simo] destination_number(50625921111) =~ /^82(\d{2})$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->call-group-order] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [call-group-order] destination_number(50625921111) =~ /^83(\d{2})$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->extension-intercom] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [extension-intercom] destination_number(50625921111) =~ /^8(10[01][0-9])$/ break=on-false                                                                                                                                                 
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->Local_Extension] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [Local_Extension] destination_number(50625921111) =~ /^(10[01][0-9])$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->Local_Extension_Skinny] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [Local_Extension_Skinny] destination_number(50625921111) =~ /^(11[01][0-9])$/ break=on-false                                                                                                                                              
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->group_dial_sales] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [group_dial_sales] destination_number(50625921111) =~ /^2000$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->group_dial_support] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [group_dial_support] destination_number(50625921111) =~ /^2001$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->group_dial_billing] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [group_dial_billing] destination_number(50625921111) =~ /^2002$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->operator] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [operator] destination_number(50625921111) =~ /^(operator|0)$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->vmain] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [vmain] destination_number(50625921111) =~ /^vmain$|^4000$|^\*98$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->sip_uri] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [sip_uri] destination_number(50625921111) =~ /^sip:(.*)$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->nb_conferences] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [nb_conferences] destination_number(50625921111) =~ /^(30\d{2})$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->wb_conferences] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [wb_conferences] destination_number(50625921111) =~ /^(31\d{2})$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->uwb_conferences] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [uwb_conferences] destination_number(50625921111) =~ /^(32\d{2})$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->cdquality_conferences] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [cdquality_conferences] destination_number(50625921111) =~ /^(33\d{2})$/ break=on-false                                                                                                                                                   
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->cdquality_conferences] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [cdquality_conferences] destination_number(50625921111) =~ /^(35\d{2})$/ break=on-false                                                                                                                                                   
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->freeswitch_public_conf_via_sip] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [freeswitch_public_conf_via_sip] destination_number(50625921111) =~ /^9(888|8888|1616|3232)$/ break=on-false                                                                                                                              
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->mad_boss_intercom] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [mad_boss_intercom] destination_number(50625921111) =~ /^0911$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->mad_boss_intercom] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [mad_boss_intercom] destination_number(50625921111) =~ /^0912$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->mad_boss] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [mad_boss] destination_number(50625921111) =~ /^0913$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->ivr_demo] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [ivr_demo] destination_number(50625921111) =~ /^5000$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->dynamic_conference] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [dynamic_conference] destination_number(50625921111) =~ /^5001$/ break=on-false
Dialplan: sofia/default/50640329559@52.204.115.208 parsing [default->rtp_multicast_page] continue=false
Dialplan: sofia/default/50640329559@52.204.115.208 Regex (FAIL) [rtp_multicast_page] destination_number(50625921111) =~ /^pagegroup$|^7243$/ break=on-false

**Comment by smrdoshi** [comment]
Fixed. You can take latest source and confirm.
