### ISSUE TITLE
Impossible to download sample rates file in ASTPP 4.0

### ISSUE THREAD

**Issue by timur-v** [iNextrix/ASTPP#521]
Carriers -> Termination Rates -> Import. The page consists "Get sample file" section with "Download" button in it. Clicking that button leads to empty page. Meantime the same action on ASTPP demo web site opens actual rate file.

**Comment by Hemdip** [comment]
Seems like permission issue in your setup, Please give 755 permission to your ASTPP directory and verify.

**Comment by timur-v** [comment]
On virtual machine that didn't work. But when I set up ASTPP on a real server it helped and the sample file is now accessable.

**Comment by Redbehrend** [comment]
It might have been permissions they updated the install script to apply them correctly

**Comment by Hemdip** [comment]
@timur-v Great!. As it working for you now so based on that we closing this ticket
