### ISSUE TITLE
Inbound problems.

### ISSUE THREAD

**Issue by amanamonline** [iNextrix/ASTPP#522]
Good afternoon,
I've problems with inbound [WARNING] mod_dptools.c:1809 Accountcode . Dialed number (0zzzzzzzzzz)  origination rates not found!!
i have all configured on astpp4.0 and inb_free=true 
Gateway, localization, rategroups, provider, trunks acl, originator and terminator, refill, didi assigned did... all ok (outbound ok)
The same version on 3.6 seems ok.

</document>
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy parsing [default->0zzzzzzzzzz] continue=false
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Regex (PASS) [0zzzzzzzzzz] destination_number(0zzzzzzzzzz) =~ /0zzzzzzzzzz/ break=on-false
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Action log(WARNING Accountcode . Dialed number (0zzzzzzzzzz)  origination rates not found!!)
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Action set(original_caller_id_name=0xxxxxxxx)
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Action set(original_caller_id_number=0xxxxxxxx)
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Action set(error_cdr=1)
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Action set(callstart=2019-06-14 14:05:42)
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Action set(account_id=18)
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Action set(parent_id=0)
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Action set(call_direction=inbound)
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Action set(calltype=DID)
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Action set(sip_ignore_remote_cause=true)
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Action set(call_processed=internal)
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Action set(effective_destination_number=0zzzzzzzzzz)
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Action set(last_bridge_hangup_cause=ORIGNATION_RATE_NOT_FOUND)
Dialplan: sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Action hangup(ORIGNATION_RATE_NOT_FOUND)
2019-06-14 16:05:42.959872 [DEBUG] switch_core_state_machine.c:286 (sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy) State Change CS_ROUTING -> CS_EXECUTE
2019-06-14 16:05:42.959872 [DEBUG] switch_core_state_machine.c:643 (sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy) State ROUTING going to sleep
2019-06-14 16:05:42.959872 [DEBUG] switch_core_state_machine.c:584 (sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy) Running State Change CS_EXECUTE (Cur 1 Tot 123)
2019-06-14 16:05:42.959872 [DEBUG] switch_core_state_machine.c:650 (sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy) State EXECUTE
2019-06-14 16:05:42.959872 [DEBUG] mod_sofia.c:209 sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy SOFIA EXECUTE
2019-06-14 16:05:42.959872 [DEBUG] switch_core_state_machine.c:328 sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy Standard EXECUTE
EXECUTE [depth=0] sofia/default/0xxxxxxxx@yyy.yyyy.yyy.yyy log(WARNING Accountcode . Dialed number (0zzzzzzzzzz)  origination rates not found!!)
2019-06-14 16:05:42.959872 [WARNING] mod_dptools.c:1809 Accountcode . Dialed number (0zzzzzzzzzz)  origination rates not found!!

**Comment by Redbehrend** [comment]
Have the same problem I found two things
First it always uses rateid 1 which means it'll only use the first rate in the tables.

Second the search query doesn't pull ^+ right like there are illegal characters so if you use inbound calls with + they fail. 

This was my experience installing it on debian and cent7 I stopped there because I didn't feel like fixing it and went back to v3.6 and just consider this a beta release.

Please note we didn't use inb_free=true

**Comment by amanamonline** [comment]
I solved the problem. Configuration > Settings > calls > general > Rate check for DID
