### ISSUE TITLE
Switch Monitoring Add-On v4.0 Registered Devices Not Showing

### ISSUE THREAD

**Issue by meshtask** [iNextrix/ASTPP#524]
Softphone registers successfully every time on any configured SIP Port. But Registered devices
are shown successfully only for SIP Profile name (default) in ASTPP v4.0. Tested on multiple CentOS 7 VPS.

**Comment by Hemdip** [comment]
@meshtask , Have you set event socket password in freeswitch? If yes then you have to set same password in ASTPP portal (Freeswitch profile). It should be display resisted devices there if your configuration proper.

**Comment by meshtask** [comment]
Event Socket password is set correctly 100%. During test i can see live calls in ASTPP,this verifies that event socket password is setup correctly. its just the Monitoring Add-On. it only shows registered devices in ASTPP if i use SIP Profile name "default". If i change it lets say to "ABCD" and reload switch, it no longer shows registered devices but device registeres successfully. By changing SIP Profile name back to "default", ASTPP starts showing devices again.

**Comment by Hemdip** [comment]
@meshtask ,

Issue has been rectify, It showing that error when only 1 sip device is register. Meanwhile you can register more then 1 sip device and check, It will we fixed in next release

**Comment by Hemdip** [comment]
@meshtask This issue has been fixed, please upgrade your source and check

https://astpp.readthedocs.io/en/v4.0.1/Installation/quick_installation.html
