### ISSUE TITLE
Error when trying to install International Credits

### ISSUE THREAD

**Issue by miorar** [iNextrix/ASTPP#525]
I received this error when trying to install International Credits Addon:

Copying file to web directories...
Copy process completed for web directories!!

Copying file for freeswitch call scripts...
Failed!! Unable to copy files to /usr/share/freeswitch/scripts/astpp/lib/ folder!!!

How to overcome this issue? Please help.

**Comment by Hemdip** [comment]
@miorar Its seems permission issue, Can you please give your 755 permission to /opt/ASTPP

**Comment by miorar** [comment]
Dear Sir,
Thanks for the fast reply. Seem both of opt and ASTPP folders are in 755 permission. But the error is still there when I try to install the International Credits addon.
Copying file to web directories...
Copy process completed for web directories!!

Copying file for freeswitch call scripts...
Failed!! Unable to copy files to /usr/share/freeswitch/scripts/astpp/lib/ folder!!!

Back
Hope you could assist resolving this error so that my technical team could test the ASTPP.

Thank you.



Best Regards,


 
Mior Ahmad RidzuanChief Technical OfficerNeu Node Sdn. Bhd. (1153535-P)No. 14-2, Jalan Keluli 7/109, Pusat Perindustrian Seksyen 7,
40000 Shah Alam,Selangor Darul Ehsan,MALAYSIA.
Mobile : (6013) 243 2013


Tel : (603) 3358 4555
 Fax : (603) 3358 4666

Skype ID : mior.ahmad
 

    On Thursday, June 20, 2019, 08:46:22 PM GMT+8, Hemdip <notifications@github.com> wrote:  
 
 
@miorar Its seems permission issue, Can you please give your 755 permission to /opt/ASTPP

**Comment by Hemdip** [comment]
@miorar, I would suggest you try once with 777 permission 

Apart from that have you checked in our demo portal? If not then please have looks and share your feedback

http://latest.astppbilling.org/

**Comment by miorar** [comment]
Dear Sir,
We have bought ASTPP Essential package for our company. Everything is ok now. We are in the process of doing training for ASTPP.

Thank you.




Best Regards,


 
Mior Ahmad RidzuanChief Technical OfficerNeu Node Sdn. Bhd. (1153535-P)No. 14-2, Jalan Keluli 7/109, Pusat Perindustrian Seksyen 7,
40000 Shah Alam,Selangor Darul Ehsan,MALAYSIA.
Mobile : (6013) 243 2013


Tel : (603) 3358 4555
 Fax : (603) 3358 4666

Skype ID : mior.ahmad
 

    On Monday, July 8, 2019, 02:42:17 PM GMT+8, Hemdip <notifications@github.com> wrote:  
 
 
@miorar, I would suggest you try once with 777 permission

Apart from that have you checked in our demo portal? If not then please have looks and share your feedback

http://latest.astppbilling.org/

**Comment by Hemdip** [comment]
@miorar That's great. Hope you enjoy to explore system. 

Closing this issue as your concern is solved.
