### ISSUE TITLE
Inbound calls from provider should not be rated through origination rates

### ISSUE THREAD

**Issue by FozzyGo4** [iNextrix/ASTPP#54]
Calls that are inbound via a provider should not get rated using the origination rates. These calls should only get rated via the DID table.

Further more the CDR for inbound is inserting 2 records into the table and should only insert the CDR for the customer and not the provider.

This is causing inaccurate reporting for the provider and customers.

**Comment by FozzyGo4** [comment]
I have made the following changes in /html/fs/lib/astpp.cdr.php that prevents the outbound CDR entry being added to CDR of the provider when the call is inbound from provider. Please let me know if this makes sense.

At line: 118

```
+ if($account_type != 3)
+	{
	$query = "INSERT INTO cdrs (uniqueid,accountid,type,callerid,callednum,billseconds,trunk_id,trunkip,callerip,disposition,callstart,debit,cost,provider_id,pricelist_id,package_id,pattern,notes,rate_cost,reseller_id,reseller_code,reseller_code_destination,reseller_cost,provider_code,provider_code_destination,provider_cost,provider_call_cost,call_direction,calltype,profile_start_stamp,answer_stamp,bridge_stamp,progress_stamp,progress_media_stamp,end_stamp,billmsec,answermsec,waitmsec,progress_mediamsec,flow_billmsec)  values ($cdr_string)";
	$logger->log($query);
	$db->run($query);
+	}
```

**Comment by FozzyGo4** [comment]
I have further modified the IF statement as follows:
`if($account_type == 0 && $dataVariable['provider_id'] != 0)`

This now works correctly on CDR reports. It does the following:

- If the call is inbound from provider, the CDR record is entered into the DB as 1 record for the customer.

- If the call is inbound from customer A to customer B using a DID, the same applies to the CDR record as above.

- No CDR record of outbound is sent to the DB if the call is a DID call.

**Comment by FozzyGo4** [comment]
After doing some further testing I have come to the following conclusion and some scenarios:

I now understand the principle of the inbound call being rated through origination rates based on the fact that if a provider charges for inbound calls then you would want to pass that charge onto the customer. If not then you can simply add the DID to the origination rate and the call will not be billed but this still adds extra records to the CDR table which still makes the duration total inaccurate. The solution to this is to remove the extra DID entry from the CDR table but the record for the CDR from the provider will have a disposition of "STANDARD" and not DID. This also adds room for error if one adds a DID to a customer and forgets to add the DID to all the origination rates. So my conclusion is this is not practical.

Another scenario and this is more practical but I feel needs extra work done on the DID rating system else it does not give the ability to have inbound charges calculated to the provider.
As mentioned in the above posts I feel the inbound calls should not be rated through an origination rate and rather be rated through the DID entry.

Currently you can add a per min charge and intervals to the DID but this will bill the customer who owns the DID. perhaps add a cost field to the DID for the provider or a checkbox to enable or disable billing of the provider.

Hope this makes sense to everyone. At this point as we are not charging for inbound calls in my country, I have made the following changes the the astpp.cdr.php file that makes my scenario work for me.

```
	// *** Function by Fozzy ***
	if($account_type == 0 && $dataVariable['provider_id'] != 0)
	{
	$query = "INSERT INTO cdrs (uniqueid,accountid,type,callerid,callednum,billseconds,trunk_id,trunkip,callerip,disposition,callstart,debit,cost,provider_id,pricelist_id,package_id,pattern,notes,rate_cost,reseller_id,reseller_code,reseller_code_destination,reseller_cost,provider_code,provider_code_destination,provider_cost,provider_call_cost,call_direction,calltype,profile_start_stamp,answer_stamp,bridge_stamp,progress_stamp,progress_media_stamp,end_stamp,billmsec,answermsec,waitmsec,progress_mediamsec,flow_billmsec)  values ($cdr_string)";
	$logger->log($query);
	$db->run($query);
	} // End Function by Foz
    //Update customer balance
	//if($debit > 0 && $dataVariable['calltype'] != "FREE") 
	
// Function modified my Fozzy 
	if($debit > 0 && $dataVariable['calltype'] != "FREE" && $account_type == 0 && $dataVariable['provider_id'] != 0)
	{
		update_balance($accountid, $debit, 0, $logger, $db);
	}
```

**Comment by smrdoshi** [comment]
We made it configurable. If you want to avoid it then you need to set variable INB_FREE="true" in /var/lib/astpp/astpp.lua. That will avoid billing of DID calls for provider. 

Update to ASTPP 3.5 and test it out.

**Comment by eightsixeight** [comment]
i have same issue as fuzzy, i need to know my COST from provider on the DID...

right now inbound call never show any cost in /reports/customerReport/

**Comment by smrdoshi** [comment]
We do not have DID buy rate option at the moment. Becuase of that you will not be able to get any value in COST field in DID calls. 

If you want to know the cost for the provider then you can create origination rate with DID prefix and define the amount in that. Then assign that rate group to provider. So whenever, we will get call from that provider, system will check origination rates and then route the call to DID. 

That way you will get 2 entries. 1 with provider account with debit value and 2nd with customer to whom DID is assigned. 

Note: Make sure you do not have INB_FREE configured in astpp-config.lua.

**Comment by eightsixeight** [comment]
i did that put the full DID in the originator rate, i get this as cdr

http://prntscr.com/ipo08k

and astpp logs


action application="set" data="fax_enable_t38_request=true"/>
<action application="set" data="origination_rates_did=ID:5|CODE:^.1418xxxxxx.*|DESTINATION:1418xxxxxx|CONNECTIONCOST:0.00000|INCLUDEDSECONDS:0|COST:0.01875|INC:0|INITIALBLOCK:0|RATEGROUP:0|MARKUP:150|ACCID:5"/>
<action application="set" data="origination_rates=ID:371167|CODE:^1418xxxxxx.*|DESTINATION:DID|CONNECTIONCOST:0.00000|INCLUDEDSECONDS:0|COST:0.0125|INC:6|INITIALBLOCK:6|RATEGROUP:1|MARKUP:150|ACCID:4"/>

but doesnt show in cost still.. any other idea ?

hard to figure my costs when all inbound shows no cost

**Comment by smrdoshi** [comment]
Again, for DID calls, you will never get cost field. Cost field will have
value when call will be routed via any trunk / carrier. For inbound calls,
we are not routing call via trunk / carrier, so that field will never get
populated.





<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>

Best Regards
--
Samir Doshi
*iNextrix Technologie**s Pvt. Ltd*.
http://www.inextrix.com


*Disclaimer:*
The information contained in this communication is confidential and may be
legally privileged. It is intended solely for the use of the individual or
entity to whom it is addressed and others authorized to receive it. If you
are not the intended recipient you are hereby notified that any disclosure,
copying, distribution or taking action in reliance on the contents of this
information is strictly prohibited and may be unlawful. Please notify the
sender immediately and destroy all copies of this message and any
attachments contained in it.

**Comment by eightsixeight** [comment]
its a call from trunk..

landline --> telco --> pri -->provider SIP as 14185551212@astppIP  (astpp) gets this from trunk provider aka gateway etc
