### ISSUE TITLE
Forget Password Doesn't update customer profile

### ISSUE THREAD

**Issue by ricky560** [iNextrix/ASTPP#57]
The Forget password process work fine but...

The flow allows for the customer to change their password and sends the success email with the password but the customer can't login after the change.

because the customer profile doesn't update hence the customer can't login

**Comment by ricky560** [comment]
I just ran the /usr/src/latest/update.sh script and tried again with the same results as the bug.  Is there some thing that I am missing.

**Comment by dev-astpp** [comment]
Issue has been fixed.

Please update latest source using update script

**Comment by ricky560** [comment]
Tested and works great.  Thank you

**Comment by dev-astpp** [comment]
Great. :+1:
