### ISSUE TITLE
Accountcode  is not authenticated

### ISSUE THREAD

**Issue by heintonny** [iNextrix/ASTPP#62]
We are not able to dial out from a successful registered SIP-endpoint.

The logfile shows:
Accountcode  is not authenticated

But the wireshark trace shows that it is.

I have included the trace from freeswithc, pcap from the endpoint (Bria Stretto).

**Comment by juancarlosg6** [comment]
You must create a SIP device into the account and use the information created for the system to log SIP device.

**Comment by heintonny** [comment]
The account 33994110 alreaddy have a sip-device named 33994110, and the pcap shows that we have a successfull SIP login.

**Comment by smrdoshi** [comment]
Please share fs_cli log. use http://pastebin.com/

**Comment by heintonny** [comment]
Here it is. It includes the SIP login and first call attempt.
http://pastebin.com/023W1D6h

**Comment by smrdoshi** [comment]
Hi Hein, 

It seems the sip device ip address is already added in ACL and not linked with proper account. That is causing the issue. 

2016-08-16 09:33:35.927162 [DEBUG] sofia.c:9488 IP 10.20.50.100 Approved by acl "default[]". Access Granted.

Please remove this ip from acl OR link it with correct account to get account code.

**Comment by smrdoshi** [comment]
We assume the issue has been resolved from your end. So we are closing the ticket.
