### ISSUE TITLE
ASTPP Documentation -cron broadcast email missing-

### ISSUE THREAD

**Issue by Neurotec** [iNextrix/ASTPP#63]
https://astppdoc.atlassian.net/wiki/display/ASTPP/Debian+8+Installation+v3.0

Hi is missing the line :

~~~
0 0 * * * cd /var/www/html/astpp/cron/ && php cron.php BroadcastEmail
~~~

for sending emails

**Comment by dev-astpp** [comment]
Fixed.

You can check in script as well as in document also.
https://astppdoc.atlassian.net/wiki/display/ASTPP/Debian+8+Installation+v3.0
