### ISSUE TITLE
 Notification Error - Wrong information on body e-mail

### ISSUE THREAD

**Issue by juancarlosg6** [iNextrix/ASTPP#65]
When the cron generate the email, the body of email not show the amount in the database, this is an example whe received and email.

Example 1:

Subject: Account credited Succesfully 

HI Juan Gonzalez, Your account has been succesfully credited with #REFILLBALANCE# due to recharge of the #ENTITY# account.() For more info, Please visit on our website www.neurotec.co or contact to our support department at info@neurotec.co. Thanks, Neurotec Tecnologia S.A.S 

Example 2:

Subjetc: Low Balance notification #NUMBER#   

Hi Juan Gonzalez, This is a quick notification about the low balance of #AMOUNT# in your account. Please refill you account from our website to ensure your services will remain consistent. You can login into customer portal and refill your account. For more info, Please visit on our website www.neurotec.co or contact to our support at info@neurotec.co Thanks, Neurotec Tecnologia S.A.S 

The same event, for all emails, not show the correct content, thanks.

**Comment by smrdoshi** [comment]
Issue has been fixed in version v3.5. Upgrade to latest version and test it out.
