### ISSUE TITLE
home page "Top 10 Accounts" 'By Minutes' option, pie chart shows Seconds NOT Minutes.

### ISSUE THREAD

**Issue by kujina** [iNextrix/ASTPP#68]
The astpp admin home page "Top 10 Accounts" 'By Minutes' option **pie chart** shows seconds not minutes.

![screenshot](https://s4.postimg.org/4jd61jekt/astpp1.gif)

**Comment by dev-astpp** [comment]
Issue is fixed now

**Comment by dev-astpp** [comment]
Issue has been fixed.

Please update latest source using update script
