### ISSUE TITLE
Version 3 Backup and Restore issue

### ISSUE THREAD

**Issue by ricky560** [iNextrix/ASTPP#69]
I am testing backup and restore on the database.  I have create some customers and backed up the database and to test the restore I deleted a customer and restored from the previous database but the customer I deleted was not restored.  Is this the normal behaviour or a  bug.

The deleted customer was done after the backup and NO I didn't see the deleted customer after the restore.

**Comment by dev-astpp** [comment]
Fixed. Please take latest source and test it out.
