### ISSUE TITLE
To strict validation of name and text fields

### ISSUE THREAD

**Issue by heintonny** [iNextrix/ASTPP#70]
It's to strict validation of name and adress fields.

Firstname field don't allow space, so persons with more than one firstname can't use both.
No text fields allow local letters who is part of code page 865, example: æøå.

![image](https://cloud.githubusercontent.com/assets/20846272/17742953/5b9d64ea-64a2-11e6-8058-b8216ccdc870.png)

**Comment by dev-astpp** [comment]
Will remove validation for above mention fields and also different language chars are also not accepting so fix it

**Comment by dev-astpp** [comment]
Issue is fixed now.

**Comment by dev-astpp** [comment]
Issue has been fixed.

Please update latest source using update script
