### ISSUE TITLE
Can't change language in admin and custumer panel

### ISSUE THREAD

**Issue by Levadiani** [iNextrix/ASTPP#80]
Can't change language with button in footer in admin and custumer panel
`<button class="btn no-padding" title="Español" id="close-image" type="button" name="es_ES" value="es_ES" onclick="get_lang('es_ES')" ;="">`
`<button class="btn no-padding" title="Français" id="close-image" type="button" name="fr_FR" value="fr_FR" onclick="get_lang('fr_FR')" ;="">`

**Comment by dev-astpp** [comment]
Not understand your exalt point.

Are you tell that language is not working? Please provide some more info and if possible then also attach image.

**Comment by lexisvar** [comment]
when I choose the Spanish flag the language don't change.

![screen shot 2016-08-26 at 1 55 33 am](https://cloud.githubusercontent.com/assets/1506853/17996768/797e962a-6b30-11e6-9971-5bfbb2bf23bf.png)

**Comment by dev-astpp** [comment]
Okay will work on it. it not translate some words

**Comment by QQ110902** [comment]
Run the command "locale -a" to verify the list of available locales
Run "dpkp-reconfigure locales" and select  "es_ES" and "fr_FR". press "OK" to generate locale.gen file.
