### ISSUE TITLE
email field on customer not editable

### ISSUE THREAD

**Issue by ergyspapa** [iNextrix/ASTPP#87]
Hi, I tried to modify the email address of one of customers and it did not update. It says that update is done successfully but if you open it again it is still old email address.

Version of ASTPP 3.0

Using google SMTP emails are not send to customers.

Regards,
Ergys PAPA

**Comment by dev-astpp** [comment]
Regarding customer email address update from edit its working fine, So you can check from updated source.

For SMTP email we will fix it soon

**Comment by ergyspapa** [comment]
Sorry for writing again.
But I tried many ways to make email works, but still I have emails with NOT SENT. I am using smtp.gmail.com

Do I have to do any thing to make email work? Or it is a bug and it can not work?

Regards,
Ergys PAPA

**Comment by dev-astpp** [comment]
No its not working will fix it soon and update you for same.

**Comment by smrdoshi** [comment]
Issue has been fixed in version v3.5. Upgrade to latest version and test it out.
