### ISSUE TITLE
customer details cant search and cant export

### ISSUE THREAD

**Issue by isrlgb** [iNextrix/ASTPP#90]
i updated to the latest and the search button doesnt work also export stopped working for me

**Comment by dev-astpp** [comment]
You mean customer list? if yes then please one more time update your source and check because its working correct as we tested.

**Comment by isrlgb** [comment]
no, customer detail report (sorry for missing words)
i click on search and choose any change but clicking on the green search button doesnt do anything
also clicking on export while the search dialog is open throws a 500

**Comment by dev-astpp** [comment]
Its ok. I check in customer detail report searching is not working correct will fix it.

But export is work for us it export all records which we have in report.

**Comment by FozzyGo4** [comment]
Hey dev, i pointed this out a while ago and showed you the issue in the code. If you remove or comment out lines 42 and 43 on web_interface/astpp/application/modules/reports/models/reports_model.php then search in reports works again.

42        $types = array('0','3');
43        $this->db->or_where_in('type', $types);    

See my commit on my folk 36f2c58.

**Comment by smrdoshi** [comment]
Yeah. This has been resolved and under testing. It will be merged to v3.0 branch soon.

**Comment by dev-astpp** [comment]
Fixed. Please take latest source and test it out.
