### ISSUE TITLE
No sip-port in profile XML

### ISSUE THREAD

**Issue by eduararley** [iNextrix/ASTPP#91]
I've tried to create a new profile and see that it didn't work. When starting from web interface, FS complains:
```
2016-08-28 19:12:32.271206 [ERR] sofia.c:3036 Error Creating SIP UA for profile: agtech_providers (sip:mod_sofia@208.43.235.37:5060;transport=udp,tcp)
The likely causes for this are:
1) Another application is already listening on the specified address.
2) The IP the profile is attempting to bind to is not local to this system.
```
I've enabled xml_curl debug in fs_cli to check the XML generated, and I see that sip-port is not anywhere in that file. I've created a new name-value pair with the sip port, and then after that, the new profile worked as expected. Seems the SIP Port setting at the beggining of the page is ignored. Also, I don't see the sip-ip setting in the XML file. Maybe it's a related issue.

**Comment by smrdoshi** [comment]
Fixed. Please take latest source and test it out.
